// Generated by Scripts/sync_compliance_tests.py
// Source: toml-test commit local-fixtures (spec 1.0.0)

import Testing

extension Tag {
    @Tag static var array: Self
    @Tag static var bool: Self
    @Tag static var comment: Self
    @Tag static var control: Self
    @Tag static var datetime: Self
    @Tag static var encoding: Self
    @Tag static var float: Self
    @Tag static var inline_table: Self
    @Tag static var integer: Self
    @Tag static var key: Self
    @Tag static var local_date: Self
    @Tag static var local_datetime: Self
    @Tag static var local_time: Self
    @Tag static var spec_1_0_0: Self
    @Tag static var string: Self
    @Tag static var table: Self
}
