#!/bin/bash

mkdir -p Docs

TOMLDECODER_DOCS=1 swift package \
  --allow-writing-to-directory Docs \
  generate-documentation \
  --target TOMLDecoder \
  --transform-for-static-hosting \
  --output-path Docs

# Sort keys of all JSON objects generated by DocC recursively and minify
# This prevents noise from random reordering of keys from Swift.
find Docs -name "*.json" -type f -exec sh -c 'jq -c "walk(if type == \"object\" then . | to_entries | sort_by(.key) | from_entries else . end)" "$1" > "$1.tmp" && mv "$1.tmp" "$1"' _ {} \;
