#!/bin/bash

swift build --target TOMLDecoder \
  -Xswiftc -emit-symbol-graph \
  -Xswiftc -emit-symbol-graph-dir \
  -Xswiftc .build/symbol-graphs

xcrun docc convert Sources/TOMLDecoder/TOMLDecoder.docc \
  --fallback-display-name TOMLDecoder \
  --fallback-bundle-version 1.0 \
  --additional-symbol-graph-dir .build/symbol-graphs \
  --transform-for-static-hosting \
  --output-path Docs

# Sort keys of all JSON objects generated by DocC recursively and minify
# This prevents noise from random reordering of keys from Swift.
find Docs -name "*.json" -type f -exec sh -c 'jq -c "walk(if type == \"object\" then . | to_entries | sort_by(.key) | from_entries else . end)" "$1" > "$1.tmp" && mv "$1.tmp" "$1"' _ {} \;
