#!/bin/bash

BUILD_DOCS=1 swift build --target TOMLDecoder \
  -Xswiftc -emit-symbol-graph \
  -Xswiftc -emit-symbol-graph-dir \
  -Xswiftc .build/symbol-graphs

BUILD_DOCS=1 swift package --allow-writing-to-directory Docs \
    generate-documentation --target TOMLDecoder \
    --disable-indexing \
    --transform-for-static-hosting \
    --hosting-base-path /TOMLDecoder/ \
    --output-path Docs

rm Package.resolved

# Sort all JSON files generated by DocC (recursively sort all objects and arrays) and minify
find Docs -name "*.json" -type f -exec sh -c 'jq -c "walk(if type == \"object\" then . | to_entries | sort_by(.key) | from_entries elif type == \"array\" then sort else . end)" "$1" > "$1.tmp" && mv "$1.tmp" "$1"' _ {} \;
