// Generated by Scripts/generate-tests.py
// Source: toml-test commit 0ee318ae97ae5dec5f74aeccafbdc75f435580e2 (spec 1.1.0)

import Foundation
import Testing
import TOMLDecoder

@Suite
struct TOMLInvalidationTests {
    private var directoryURL: URL {
        URL(fileURLWithPath: #filePath)
            .deletingLastPathComponent()
            .appendingPathComponent("invalid_fixtures")
    }

    private func invalidate(pathComponents: [String], sourceLocation: SourceLocation = #_sourceLocation) throws {
        let baseURL = pathComponents.reduce(directoryURL) { $0.appendingPathComponent($1) }
        let tomlURL = baseURL.appendingPathExtension("toml")
        try TOMLComplianceSupport.verifyInvalidFixture(tomlURL: tomlURL, sourceLocation: sourceLocation)
    }

    @Test("[array] double comma 01", .tags(.array))
    func array__double_comma_01() throws {
        try invalidate(pathComponents: ["array", "double-comma-01"])
    }

    @Test("[array] double comma 02", .tags(.array))
    func array__double_comma_02() throws {
        try invalidate(pathComponents: ["array", "double-comma-02"])
    }

    @Test("[array] extend defined aot", .tags(.array))
    func array__extend_defined_aot() throws {
        try invalidate(pathComponents: ["array", "extend-defined-aot"])
    }

    @Test("[array] extending table", .tags(.array))
    func array__extending_table() throws {
        try invalidate(pathComponents: ["array", "extending-table"])
    }

    @Test("[array] missing separator 01", .tags(.array))
    func array__missing_separator_01() throws {
        try invalidate(pathComponents: ["array", "missing-separator-01"])
    }

    @Test("[array] missing separator 02", .tags(.array))
    func array__missing_separator_02() throws {
        try invalidate(pathComponents: ["array", "missing-separator-02"])
    }

    @Test("[array] no close 01", .tags(.array))
    func array__no_close_01() throws {
        try invalidate(pathComponents: ["array", "no-close-01"])
    }

    @Test("[array] no close 02", .tags(.array))
    func array__no_close_02() throws {
        try invalidate(pathComponents: ["array", "no-close-02"])
    }

    @Test("[array] no close 03", .tags(.array))
    func array__no_close_03() throws {
        try invalidate(pathComponents: ["array", "no-close-03"])
    }

    @Test("[array] no close 04", .tags(.array))
    func array__no_close_04() throws {
        try invalidate(pathComponents: ["array", "no-close-04"])
    }

    @Test("[array] no close 05", .tags(.array))
    func array__no_close_05() throws {
        try invalidate(pathComponents: ["array", "no-close-05"])
    }

    @Test("[array] no close 06", .tags(.array))
    func array__no_close_06() throws {
        try invalidate(pathComponents: ["array", "no-close-06"])
    }

    @Test("[array] no close 07", .tags(.array))
    func array__no_close_07() throws {
        try invalidate(pathComponents: ["array", "no-close-07"])
    }

    @Test("[array] no close 08", .tags(.array))
    func array__no_close_08() throws {
        try invalidate(pathComponents: ["array", "no-close-08"])
    }

    @Test("[array] no close table 01", .tags(.array))
    func array__no_close_table_01() throws {
        try invalidate(pathComponents: ["array", "no-close-table-01"])
    }

    @Test("[array] no close table 02", .tags(.array))
    func array__no_close_table_02() throws {
        try invalidate(pathComponents: ["array", "no-close-table-02"])
    }

    @Test("[array] no comma 01", .tags(.array))
    func array__no_comma_01() throws {
        try invalidate(pathComponents: ["array", "no-comma-01"])
    }

    @Test("[array] no comma 02", .tags(.array))
    func array__no_comma_02() throws {
        try invalidate(pathComponents: ["array", "no-comma-02"])
    }

    @Test("[array] no comma 03", .tags(.array))
    func array__no_comma_03() throws {
        try invalidate(pathComponents: ["array", "no-comma-03"])
    }

    @Test("[array] only comma 01", .tags(.array))
    func array__only_comma_01() throws {
        try invalidate(pathComponents: ["array", "only-comma-01"])
    }

    @Test("[array] only comma 02", .tags(.array))
    func array__only_comma_02() throws {
        try invalidate(pathComponents: ["array", "only-comma-02"])
    }

    @Test("[array] tables 01", .tags(.array))
    func array__tables_01() throws {
        try invalidate(pathComponents: ["array", "tables-01"])
    }

    @Test("[array] tables 02", .tags(.array))
    func array__tables_02() throws {
        try invalidate(pathComponents: ["array", "tables-02"])
    }

    @Test("[array] text after array entries", .tags(.array))
    func array__text_after_array_entries() throws {
        try invalidate(pathComponents: ["array", "text-after-array-entries"])
    }

    @Test("[array] text before array separator", .tags(.array))
    func array__text_before_array_separator() throws {
        try invalidate(pathComponents: ["array", "text-before-array-separator"])
    }

    @Test("[array] text in array", .tags(.array))
    func array__text_in_array() throws {
        try invalidate(pathComponents: ["array", "text-in-array"])
    }

    @Test("[bool] almost false", .tags(.bool))
    func bool__almost_false() throws {
        try invalidate(pathComponents: ["bool", "almost-false"])
    }

    @Test("[bool] almost false with extra", .tags(.bool))
    func bool__almost_false_with_extra() throws {
        try invalidate(pathComponents: ["bool", "almost-false-with-extra"])
    }

    @Test("[bool] almost true", .tags(.bool))
    func bool__almost_true() throws {
        try invalidate(pathComponents: ["bool", "almost-true"])
    }

    @Test("[bool] almost true with extra", .tags(.bool))
    func bool__almost_true_with_extra() throws {
        try invalidate(pathComponents: ["bool", "almost-true-with-extra"])
    }

    @Test("[bool] capitalized false", .tags(.bool))
    func bool__capitalized_false() throws {
        try invalidate(pathComponents: ["bool", "capitalized-false"])
    }

    @Test("[bool] capitalized true", .tags(.bool))
    func bool__capitalized_true() throws {
        try invalidate(pathComponents: ["bool", "capitalized-true"])
    }

    @Test("[bool] just f", .tags(.bool))
    func bool__just_f() throws {
        try invalidate(pathComponents: ["bool", "just-f"])
    }

    @Test("[bool] just t", .tags(.bool))
    func bool__just_t() throws {
        try invalidate(pathComponents: ["bool", "just-t"])
    }

    @Test("[bool] mixed case", .tags(.bool))
    func bool__mixed_case() throws {
        try invalidate(pathComponents: ["bool", "mixed-case"])
    }

    @Test("[bool] mixed case false", .tags(.bool))
    func bool__mixed_case_false() throws {
        try invalidate(pathComponents: ["bool", "mixed-case-false"])
    }

    @Test("[bool] mixed case true", .tags(.bool))
    func bool__mixed_case_true() throws {
        try invalidate(pathComponents: ["bool", "mixed-case-true"])
    }

    @Test("[bool] starting same false", .tags(.bool))
    func bool__starting_same_false() throws {
        try invalidate(pathComponents: ["bool", "starting-same-false"])
    }

    @Test("[bool] starting same true", .tags(.bool))
    func bool__starting_same_true() throws {
        try invalidate(pathComponents: ["bool", "starting-same-true"])
    }

    @Test("[bool] wrong case false", .tags(.bool))
    func bool__wrong_case_false() throws {
        try invalidate(pathComponents: ["bool", "wrong-case-false"])
    }

    @Test("[bool] wrong case true", .tags(.bool))
    func bool__wrong_case_true() throws {
        try invalidate(pathComponents: ["bool", "wrong-case-true"])
    }

    @Test("[control] bare cr", .tags(.control))
    func control__bare_cr() throws {
        try invalidate(pathComponents: ["control", "bare-cr"])
    }

    @Test("[control] bare formfeed", .tags(.control))
    func control__bare_formfeed() throws {
        try invalidate(pathComponents: ["control", "bare-formfeed"])
    }

    @Test("[control] bare null", .tags(.control))
    func control__bare_null() throws {
        try invalidate(pathComponents: ["control", "bare-null"])
    }

    @Test("[control] bare vertical tab", .tags(.control))
    func control__bare_vertical_tab() throws {
        try invalidate(pathComponents: ["control", "bare-vertical-tab"])
    }

    @Test("[control] comment cr", .tags(.control))
    func control__comment_cr() throws {
        try invalidate(pathComponents: ["control", "comment-cr"])
    }

    @Test("[control] comment del", .tags(.control))
    func control__comment_del() throws {
        try invalidate(pathComponents: ["control", "comment-del"])
    }

    @Test("[control] comment ff", .tags(.control))
    func control__comment_ff() throws {
        try invalidate(pathComponents: ["control", "comment-ff"])
    }

    @Test("[control] comment lf", .tags(.control))
    func control__comment_lf() throws {
        try invalidate(pathComponents: ["control", "comment-lf"])
    }

    @Test("[control] comment null", .tags(.control))
    func control__comment_null() throws {
        try invalidate(pathComponents: ["control", "comment-null"])
    }

    @Test("[control] comment us", .tags(.control))
    func control__comment_us() throws {
        try invalidate(pathComponents: ["control", "comment-us"])
    }

    @Test("[control] multi cr", .tags(.control))
    func control__multi_cr() throws {
        try invalidate(pathComponents: ["control", "multi-cr"])
    }

    @Test("[control] multi del", .tags(.control))
    func control__multi_del() throws {
        try invalidate(pathComponents: ["control", "multi-del"])
    }

    @Test("[control] multi lf", .tags(.control))
    func control__multi_lf() throws {
        try invalidate(pathComponents: ["control", "multi-lf"])
    }

    @Test("[control] multi null", .tags(.control))
    func control__multi_null() throws {
        try invalidate(pathComponents: ["control", "multi-null"])
    }

    @Test("[control] multi us", .tags(.control))
    func control__multi_us() throws {
        try invalidate(pathComponents: ["control", "multi-us"])
    }

    @Test("[control] only ff", .tags(.control))
    func control__only_ff() throws {
        try invalidate(pathComponents: ["control", "only-ff"])
    }

    @Test("[control] only null", .tags(.control))
    func control__only_null() throws {
        try invalidate(pathComponents: ["control", "only-null"])
    }

    @Test("[control] only vt", .tags(.control))
    func control__only_vt() throws {
        try invalidate(pathComponents: ["control", "only-vt"])
    }

    @Test("[control] rawmulti cr", .tags(.control))
    func control__rawmulti_cr() throws {
        try invalidate(pathComponents: ["control", "rawmulti-cr"])
    }

    @Test("[control] rawmulti del", .tags(.control))
    func control__rawmulti_del() throws {
        try invalidate(pathComponents: ["control", "rawmulti-del"])
    }

    @Test("[control] rawmulti lf", .tags(.control))
    func control__rawmulti_lf() throws {
        try invalidate(pathComponents: ["control", "rawmulti-lf"])
    }

    @Test("[control] rawmulti null", .tags(.control))
    func control__rawmulti_null() throws {
        try invalidate(pathComponents: ["control", "rawmulti-null"])
    }

    @Test("[control] rawmulti us", .tags(.control))
    func control__rawmulti_us() throws {
        try invalidate(pathComponents: ["control", "rawmulti-us"])
    }

    @Test("[control] rawstring cr", .tags(.control))
    func control__rawstring_cr() throws {
        try invalidate(pathComponents: ["control", "rawstring-cr"])
    }

    @Test("[control] rawstring del", .tags(.control))
    func control__rawstring_del() throws {
        try invalidate(pathComponents: ["control", "rawstring-del"])
    }

    @Test("[control] rawstring lf", .tags(.control))
    func control__rawstring_lf() throws {
        try invalidate(pathComponents: ["control", "rawstring-lf"])
    }

    @Test("[control] rawstring null", .tags(.control))
    func control__rawstring_null() throws {
        try invalidate(pathComponents: ["control", "rawstring-null"])
    }

    @Test("[control] rawstring us", .tags(.control))
    func control__rawstring_us() throws {
        try invalidate(pathComponents: ["control", "rawstring-us"])
    }

    @Test("[control] string bs", .tags(.control))
    func control__string_bs() throws {
        try invalidate(pathComponents: ["control", "string-bs"])
    }

    @Test("[control] string cr", .tags(.control))
    func control__string_cr() throws {
        try invalidate(pathComponents: ["control", "string-cr"])
    }

    @Test("[control] string del", .tags(.control))
    func control__string_del() throws {
        try invalidate(pathComponents: ["control", "string-del"])
    }

    @Test("[control] string lf", .tags(.control))
    func control__string_lf() throws {
        try invalidate(pathComponents: ["control", "string-lf"])
    }

    @Test("[control] string null", .tags(.control))
    func control__string_null() throws {
        try invalidate(pathComponents: ["control", "string-null"])
    }

    @Test("[control] string us", .tags(.control))
    func control__string_us() throws {
        try invalidate(pathComponents: ["control", "string-us"])
    }

    @Test("[datetime] day zero", .tags(.datetime))
    func datetime__day_zero() throws {
        try invalidate(pathComponents: ["datetime", "day-zero"])
    }

    @Test("[datetime] feb 29", .tags(.datetime))
    func datetime__feb_29() throws {
        try invalidate(pathComponents: ["datetime", "feb-29"])
    }

    @Test("[datetime] feb 30", .tags(.datetime))
    func datetime__feb_30() throws {
        try invalidate(pathComponents: ["datetime", "feb-30"])
    }

    @Test("[datetime] hour over", .tags(.datetime))
    func datetime__hour_over() throws {
        try invalidate(pathComponents: ["datetime", "hour-over"])
    }

    @Test("[datetime] mday over", .tags(.datetime))
    func datetime__mday_over() throws {
        try invalidate(pathComponents: ["datetime", "mday-over"])
    }

    @Test("[datetime] mday under", .tags(.datetime))
    func datetime__mday_under() throws {
        try invalidate(pathComponents: ["datetime", "mday-under"])
    }

    @Test("[datetime] minute over", .tags(.datetime))
    func datetime__minute_over() throws {
        try invalidate(pathComponents: ["datetime", "minute-over"])
    }

    @Test("[datetime] month over", .tags(.datetime))
    func datetime__month_over() throws {
        try invalidate(pathComponents: ["datetime", "month-over"])
    }

    @Test("[datetime] month under", .tags(.datetime))
    func datetime__month_under() throws {
        try invalidate(pathComponents: ["datetime", "month-under"])
    }

    @Test("[datetime] no date time sep", .tags(.datetime))
    func datetime__no_date_time_sep() throws {
        try invalidate(pathComponents: ["datetime", "no-date-time-sep"])
    }

    @Test("[datetime] no leads", .tags(.datetime))
    func datetime__no_leads() throws {
        try invalidate(pathComponents: ["datetime", "no-leads"])
    }

    @Test("[datetime] no leads month", .tags(.datetime))
    func datetime__no_leads_month() throws {
        try invalidate(pathComponents: ["datetime", "no-leads-month"])
    }

    @Test("[datetime] no leads with milli", .tags(.datetime))
    func datetime__no_leads_with_milli() throws {
        try invalidate(pathComponents: ["datetime", "no-leads-with-milli"])
    }

    @Test("[datetime] no t", .tags(.datetime))
    func datetime__no_t() throws {
        try invalidate(pathComponents: ["datetime", "no-t"])
    }

    @Test("[datetime] no year month sep", .tags(.datetime))
    func datetime__no_year_month_sep() throws {
        try invalidate(pathComponents: ["datetime", "no-year-month-sep"])
    }

    @Test("[datetime] offset minus minute 1digit", .tags(.datetime))
    func datetime__offset_minus_minute_1digit() throws {
        try invalidate(pathComponents: ["datetime", "offset-minus-minute-1digit"])
    }

    @Test("[datetime] offset minus no hour minute", .tags(.datetime))
    func datetime__offset_minus_no_hour_minute() throws {
        try invalidate(pathComponents: ["datetime", "offset-minus-no-hour-minute"])
    }

    @Test("[datetime] offset minus no hour minute sep", .tags(.datetime))
    func datetime__offset_minus_no_hour_minute_sep() throws {
        try invalidate(pathComponents: ["datetime", "offset-minus-no-hour-minute-sep"])
    }

    @Test("[datetime] offset minus no minute", .tags(.datetime))
    func datetime__offset_minus_no_minute() throws {
        try invalidate(pathComponents: ["datetime", "offset-minus-no-minute"])
    }

    @Test("[datetime] offset overflow hour", .tags(.datetime))
    func datetime__offset_overflow_hour() throws {
        try invalidate(pathComponents: ["datetime", "offset-overflow-hour"])
    }

    @Test("[datetime] offset overflow minute", .tags(.datetime))
    func datetime__offset_overflow_minute() throws {
        try invalidate(pathComponents: ["datetime", "offset-overflow-minute"])
    }

    @Test("[datetime] offset plus minute 1digit", .tags(.datetime))
    func datetime__offset_plus_minute_1digit() throws {
        try invalidate(pathComponents: ["datetime", "offset-plus-minute-1digit"])
    }

    @Test("[datetime] offset plus no hour minute", .tags(.datetime))
    func datetime__offset_plus_no_hour_minute() throws {
        try invalidate(pathComponents: ["datetime", "offset-plus-no-hour-minute"])
    }

    @Test("[datetime] offset plus no hour minute sep", .tags(.datetime))
    func datetime__offset_plus_no_hour_minute_sep() throws {
        try invalidate(pathComponents: ["datetime", "offset-plus-no-hour-minute-sep"])
    }

    @Test("[datetime] offset plus no minute", .tags(.datetime))
    func datetime__offset_plus_no_minute() throws {
        try invalidate(pathComponents: ["datetime", "offset-plus-no-minute"])
    }

    @Test("[datetime] only T", .tags(.datetime))
    func datetime__only_T() throws {
        try invalidate(pathComponents: ["datetime", "only-T"])
    }

    @Test("[datetime] only TZ", .tags(.datetime))
    func datetime__only_TZ() throws {
        try invalidate(pathComponents: ["datetime", "only-TZ"])
    }

    @Test("[datetime] only Tdot", .tags(.datetime))
    func datetime__only_Tdot() throws {
        try invalidate(pathComponents: ["datetime", "only-Tdot"])
    }

    @Test("[datetime] second over", .tags(.datetime))
    func datetime__second_over() throws {
        try invalidate(pathComponents: ["datetime", "second-over"])
    }

    @Test("[datetime] second trailing dot", .tags(.datetime))
    func datetime__second_trailing_dot() throws {
        try invalidate(pathComponents: ["datetime", "second-trailing-dot"])
    }

    @Test("[datetime] second trailing dotz", .tags(.datetime))
    func datetime__second_trailing_dotz() throws {
        try invalidate(pathComponents: ["datetime", "second-trailing-dotz"])
    }

    @Test("[datetime] time no leads", .tags(.datetime))
    func datetime__time_no_leads() throws {
        try invalidate(pathComponents: ["datetime", "time-no-leads"])
    }

    @Test("[datetime] trailing x", .tags(.datetime))
    func datetime__trailing_x() throws {
        try invalidate(pathComponents: ["datetime", "trailing-x"])
    }

    @Test("[datetime] y10k", .tags(.datetime))
    func datetime__y10k() throws {
        try invalidate(pathComponents: ["datetime", "y10k"])
    }

    @Test("[encoding] bad codepoint", .tags(.encoding))
    func encoding__bad_codepoint() throws {
        try invalidate(pathComponents: ["encoding", "bad-codepoint"])
    }

    @Test("[encoding] bad utf8 at end", .tags(.encoding))
    func encoding__bad_utf8_at_end() throws {
        try invalidate(pathComponents: ["encoding", "bad-utf8-at-end"])
    }

    @Test("[encoding] bad utf8 in array", .tags(.encoding))
    func encoding__bad_utf8_in_array() throws {
        try invalidate(pathComponents: ["encoding", "bad-utf8-in-array"])
    }

    @Test("[encoding] bad utf8 in comment", .tags(.encoding))
    func encoding__bad_utf8_in_comment() throws {
        try invalidate(pathComponents: ["encoding", "bad-utf8-in-comment"])
    }

    @Test("[encoding] bad utf8 in multiline", .tags(.encoding))
    func encoding__bad_utf8_in_multiline() throws {
        try invalidate(pathComponents: ["encoding", "bad-utf8-in-multiline"])
    }

    @Test("[encoding] bad utf8 in multiline literal", .tags(.encoding))
    func encoding__bad_utf8_in_multiline_literal() throws {
        try invalidate(pathComponents: ["encoding", "bad-utf8-in-multiline-literal"])
    }

    @Test("[encoding] bad utf8 in string", .tags(.encoding))
    func encoding__bad_utf8_in_string() throws {
        try invalidate(pathComponents: ["encoding", "bad-utf8-in-string"])
    }

    @Test("[encoding] bad utf8 in string literal", .tags(.encoding))
    func encoding__bad_utf8_in_string_literal() throws {
        try invalidate(pathComponents: ["encoding", "bad-utf8-in-string-literal"])
    }

    @Test("[encoding] bom not at start 01", .tags(.encoding))
    func encoding__bom_not_at_start_01() throws {
        try invalidate(pathComponents: ["encoding", "bom-not-at-start-01"])
    }

    @Test("[encoding] bom not at start 02", .tags(.encoding))
    func encoding__bom_not_at_start_02() throws {
        try invalidate(pathComponents: ["encoding", "bom-not-at-start-02"])
    }

    @Test("[encoding] ideographic space", .tags(.encoding))
    func encoding__ideographic_space() throws {
        try invalidate(pathComponents: ["encoding", "ideographic-space"])
    }

    @Test("[encoding] utf16 bom", .tags(.encoding))
    func encoding__utf16_bom() throws {
        try invalidate(pathComponents: ["encoding", "utf16-bom"])
    }

    @Test("[encoding] utf16 comment", .tags(.encoding))
    func encoding__utf16_comment() throws {
        try invalidate(pathComponents: ["encoding", "utf16-comment"])
    }

    @Test("[encoding] utf16 key", .tags(.encoding))
    func encoding__utf16_key() throws {
        try invalidate(pathComponents: ["encoding", "utf16-key"])
    }

    @Test("[float] double dot 01", .tags(.float))
    func float__double_dot_01() throws {
        try invalidate(pathComponents: ["float", "double-dot-01"])
    }

    @Test("[float] double dot 02", .tags(.float))
    func float__double_dot_02() throws {
        try invalidate(pathComponents: ["float", "double-dot-02"])
    }

    @Test("[float] exp dot 01", .tags(.float))
    func float__exp_dot_01() throws {
        try invalidate(pathComponents: ["float", "exp-dot-01"])
    }

    @Test("[float] exp dot 02", .tags(.float))
    func float__exp_dot_02() throws {
        try invalidate(pathComponents: ["float", "exp-dot-02"])
    }

    @Test("[float] exp dot 03", .tags(.float))
    func float__exp_dot_03() throws {
        try invalidate(pathComponents: ["float", "exp-dot-03"])
    }

    @Test("[float] exp double e 01", .tags(.float))
    func float__exp_double_e_01() throws {
        try invalidate(pathComponents: ["float", "exp-double-e-01"])
    }

    @Test("[float] exp double e 02", .tags(.float))
    func float__exp_double_e_02() throws {
        try invalidate(pathComponents: ["float", "exp-double-e-02"])
    }

    @Test("[float] exp double us", .tags(.float))
    func float__exp_double_us() throws {
        try invalidate(pathComponents: ["float", "exp-double-us"])
    }

    @Test("[float] exp leading us", .tags(.float))
    func float__exp_leading_us() throws {
        try invalidate(pathComponents: ["float", "exp-leading-us"])
    }

    @Test("[float] exp trailing us", .tags(.float))
    func float__exp_trailing_us() throws {
        try invalidate(pathComponents: ["float", "exp-trailing-us"])
    }

    @Test("[float] exp trailing us 01", .tags(.float))
    func float__exp_trailing_us_01() throws {
        try invalidate(pathComponents: ["float", "exp-trailing-us-01"])
    }

    @Test("[float] exp trailing us 02", .tags(.float))
    func float__exp_trailing_us_02() throws {
        try invalidate(pathComponents: ["float", "exp-trailing-us-02"])
    }

    @Test("[float] inf capital", .tags(.float))
    func float__inf_capital() throws {
        try invalidate(pathComponents: ["float", "inf-capital"])
    }

    @Test("[float] inf incomplete 01", .tags(.float))
    func float__inf_incomplete_01() throws {
        try invalidate(pathComponents: ["float", "inf-incomplete-01"])
    }

    @Test("[float] inf incomplete 02", .tags(.float))
    func float__inf_incomplete_02() throws {
        try invalidate(pathComponents: ["float", "inf-incomplete-02"])
    }

    @Test("[float] inf incomplete 03", .tags(.float))
    func float__inf_incomplete_03() throws {
        try invalidate(pathComponents: ["float", "inf-incomplete-03"])
    }

    @Test("[float] inf underscore", .tags(.float))
    func float__inf_underscore() throws {
        try invalidate(pathComponents: ["float", "inf_underscore"])
    }

    @Test("[float] leading dot", .tags(.float))
    func float__leading_dot() throws {
        try invalidate(pathComponents: ["float", "leading-dot"])
    }

    @Test("[float] leading dot neg", .tags(.float))
    func float__leading_dot_neg() throws {
        try invalidate(pathComponents: ["float", "leading-dot-neg"])
    }

    @Test("[float] leading dot plus", .tags(.float))
    func float__leading_dot_plus() throws {
        try invalidate(pathComponents: ["float", "leading-dot-plus"])
    }

    @Test("[float] leading us", .tags(.float))
    func float__leading_us() throws {
        try invalidate(pathComponents: ["float", "leading-us"])
    }

    @Test("[float] leading zero", .tags(.float))
    func float__leading_zero() throws {
        try invalidate(pathComponents: ["float", "leading-zero"])
    }

    @Test("[float] leading zero neg", .tags(.float))
    func float__leading_zero_neg() throws {
        try invalidate(pathComponents: ["float", "leading-zero-neg"])
    }

    @Test("[float] leading zero plus", .tags(.float))
    func float__leading_zero_plus() throws {
        try invalidate(pathComponents: ["float", "leading-zero-plus"])
    }

    @Test("[float] nan capital", .tags(.float))
    func float__nan_capital() throws {
        try invalidate(pathComponents: ["float", "nan-capital"])
    }

    @Test("[float] nan incomplete 01", .tags(.float))
    func float__nan_incomplete_01() throws {
        try invalidate(pathComponents: ["float", "nan-incomplete-01"])
    }

    @Test("[float] nan incomplete 02", .tags(.float))
    func float__nan_incomplete_02() throws {
        try invalidate(pathComponents: ["float", "nan-incomplete-02"])
    }

    @Test("[float] nan incomplete 03", .tags(.float))
    func float__nan_incomplete_03() throws {
        try invalidate(pathComponents: ["float", "nan-incomplete-03"])
    }

    @Test("[float] nan underscore", .tags(.float))
    func float__nan_underscore() throws {
        try invalidate(pathComponents: ["float", "nan_underscore"])
    }

    @Test("[float] trailing dot", .tags(.float))
    func float__trailing_dot() throws {
        try invalidate(pathComponents: ["float", "trailing-dot"])
    }

    @Test("[float] trailing dot 01", .tags(.float))
    func float__trailing_dot_01() throws {
        try invalidate(pathComponents: ["float", "trailing-dot-01"])
    }

    @Test("[float] trailing dot 02", .tags(.float))
    func float__trailing_dot_02() throws {
        try invalidate(pathComponents: ["float", "trailing-dot-02"])
    }

    @Test("[float] trailing dot min", .tags(.float))
    func float__trailing_dot_min() throws {
        try invalidate(pathComponents: ["float", "trailing-dot-min"])
    }

    @Test("[float] trailing dot plus", .tags(.float))
    func float__trailing_dot_plus() throws {
        try invalidate(pathComponents: ["float", "trailing-dot-plus"])
    }

    @Test("[float] trailing exp", .tags(.float))
    func float__trailing_exp() throws {
        try invalidate(pathComponents: ["float", "trailing-exp"])
    }

    @Test("[float] trailing exp dot", .tags(.float))
    func float__trailing_exp_dot() throws {
        try invalidate(pathComponents: ["float", "trailing-exp-dot"])
    }

    @Test("[float] trailing exp minus", .tags(.float))
    func float__trailing_exp_minus() throws {
        try invalidate(pathComponents: ["float", "trailing-exp-minus"])
    }

    @Test("[float] trailing exp plus", .tags(.float))
    func float__trailing_exp_plus() throws {
        try invalidate(pathComponents: ["float", "trailing-exp-plus"])
    }

    @Test("[float] trailing us", .tags(.float))
    func float__trailing_us() throws {
        try invalidate(pathComponents: ["float", "trailing-us"])
    }

    @Test("[float] trailing us exp 01", .tags(.float))
    func float__trailing_us_exp_01() throws {
        try invalidate(pathComponents: ["float", "trailing-us-exp-01"])
    }

    @Test("[float] trailing us exp 02", .tags(.float))
    func float__trailing_us_exp_02() throws {
        try invalidate(pathComponents: ["float", "trailing-us-exp-02"])
    }

    @Test("[float] us after dot", .tags(.float))
    func float__us_after_dot() throws {
        try invalidate(pathComponents: ["float", "us-after-dot"])
    }

    @Test("[float] us before dot", .tags(.float))
    func float__us_before_dot() throws {
        try invalidate(pathComponents: ["float", "us-before-dot"])
    }

    @Test("[inline-table] bad key syntax", .tags(.inline_table))
    func inline_table__bad_key_syntax() throws {
        try invalidate(pathComponents: ["inline-table", "bad-key-syntax"])
    }

    @Test("[inline-table] double comma", .tags(.inline_table))
    func inline_table__double_comma() throws {
        try invalidate(pathComponents: ["inline-table", "double-comma"])
    }

    @Test("[inline-table] duplicate key 01", .tags(.inline_table))
    func inline_table__duplicate_key_01() throws {
        try invalidate(pathComponents: ["inline-table", "duplicate-key-01"])
    }

    @Test("[inline-table] duplicate key 02", .tags(.inline_table))
    func inline_table__duplicate_key_02() throws {
        try invalidate(pathComponents: ["inline-table", "duplicate-key-02"])
    }

    @Test("[inline-table] duplicate key 03", .tags(.inline_table))
    func inline_table__duplicate_key_03() throws {
        try invalidate(pathComponents: ["inline-table", "duplicate-key-03"])
    }

    @Test("[inline-table] duplicate key 04", .tags(.inline_table))
    func inline_table__duplicate_key_04() throws {
        try invalidate(pathComponents: ["inline-table", "duplicate-key-04"])
    }

    @Test("[inline-table] empty 01", .tags(.inline_table))
    func inline_table__empty_01() throws {
        try invalidate(pathComponents: ["inline-table", "empty-01"])
    }

    @Test("[inline-table] empty 02", .tags(.inline_table))
    func inline_table__empty_02() throws {
        try invalidate(pathComponents: ["inline-table", "empty-02"])
    }

    @Test("[inline-table] empty 03", .tags(.inline_table))
    func inline_table__empty_03() throws {
        try invalidate(pathComponents: ["inline-table", "empty-03"])
    }

    @Test("[inline-table] no close 01", .tags(.inline_table))
    func inline_table__no_close_01() throws {
        try invalidate(pathComponents: ["inline-table", "no-close-01"])
    }

    @Test("[inline-table] no close 02", .tags(.inline_table))
    func inline_table__no_close_02() throws {
        try invalidate(pathComponents: ["inline-table", "no-close-02"])
    }

    @Test("[inline-table] no comma 01", .tags(.inline_table))
    func inline_table__no_comma_01() throws {
        try invalidate(pathComponents: ["inline-table", "no-comma-01"])
    }

    @Test("[inline-table] no comma 02", .tags(.inline_table))
    func inline_table__no_comma_02() throws {
        try invalidate(pathComponents: ["inline-table", "no-comma-02"])
    }

    @Test("[inline-table] overwrite 01", .tags(.inline_table))
    func inline_table__overwrite_01() throws {
        try invalidate(pathComponents: ["inline-table", "overwrite-01"])
    }

    @Test("[inline-table] overwrite 02", .tags(.inline_table))
    func inline_table__overwrite_02() throws {
        try invalidate(pathComponents: ["inline-table", "overwrite-02"])
    }

    @Test("[inline-table] overwrite 03", .tags(.inline_table))
    func inline_table__overwrite_03() throws {
        try invalidate(pathComponents: ["inline-table", "overwrite-03"])
    }

    @Test("[inline-table] overwrite 04", .tags(.inline_table))
    func inline_table__overwrite_04() throws {
        try invalidate(pathComponents: ["inline-table", "overwrite-04"])
    }

    @Test("[inline-table] overwrite 05", .tags(.inline_table))
    func inline_table__overwrite_05() throws {
        try invalidate(pathComponents: ["inline-table", "overwrite-05"])
    }

    @Test("[inline-table] overwrite 06", .tags(.inline_table))
    func inline_table__overwrite_06() throws {
        try invalidate(pathComponents: ["inline-table", "overwrite-06"])
    }

    @Test("[inline-table] overwrite 07", .tags(.inline_table))
    func inline_table__overwrite_07() throws {
        try invalidate(pathComponents: ["inline-table", "overwrite-07"])
    }

    @Test("[inline-table] overwrite 08", .tags(.inline_table))
    func inline_table__overwrite_08() throws {
        try invalidate(pathComponents: ["inline-table", "overwrite-08"])
    }

    @Test("[inline-table] overwrite 09", .tags(.inline_table))
    func inline_table__overwrite_09() throws {
        try invalidate(pathComponents: ["inline-table", "overwrite-09"])
    }

    @Test("[inline-table] overwrite 10", .tags(.inline_table))
    func inline_table__overwrite_10() throws {
        try invalidate(pathComponents: ["inline-table", "overwrite-10"])
    }

    @Test("[integer] capital bin", .tags(.integer))
    func integer__capital_bin() throws {
        try invalidate(pathComponents: ["integer", "capital-bin"])
    }

    @Test("[integer] capital hex", .tags(.integer))
    func integer__capital_hex() throws {
        try invalidate(pathComponents: ["integer", "capital-hex"])
    }

    @Test("[integer] capital oct", .tags(.integer))
    func integer__capital_oct() throws {
        try invalidate(pathComponents: ["integer", "capital-oct"])
    }

    @Test("[integer] double sign nex", .tags(.integer))
    func integer__double_sign_nex() throws {
        try invalidate(pathComponents: ["integer", "double-sign-nex"])
    }

    @Test("[integer] double sign plus", .tags(.integer))
    func integer__double_sign_plus() throws {
        try invalidate(pathComponents: ["integer", "double-sign-plus"])
    }

    @Test("[integer] double us", .tags(.integer))
    func integer__double_us() throws {
        try invalidate(pathComponents: ["integer", "double-us"])
    }

    @Test("[integer] incomplete bin", .tags(.integer))
    func integer__incomplete_bin() throws {
        try invalidate(pathComponents: ["integer", "incomplete-bin"])
    }

    @Test("[integer] incomplete hex", .tags(.integer))
    func integer__incomplete_hex() throws {
        try invalidate(pathComponents: ["integer", "incomplete-hex"])
    }

    @Test("[integer] incomplete oct", .tags(.integer))
    func integer__incomplete_oct() throws {
        try invalidate(pathComponents: ["integer", "incomplete-oct"])
    }

    @Test("[integer] invalid bin", .tags(.integer))
    func integer__invalid_bin() throws {
        try invalidate(pathComponents: ["integer", "invalid-bin"])
    }

    @Test("[integer] invalid hex 01", .tags(.integer))
    func integer__invalid_hex_01() throws {
        try invalidate(pathComponents: ["integer", "invalid-hex-01"])
    }

    @Test("[integer] invalid hex 02", .tags(.integer))
    func integer__invalid_hex_02() throws {
        try invalidate(pathComponents: ["integer", "invalid-hex-02"])
    }

    @Test("[integer] invalid hex 03", .tags(.integer))
    func integer__invalid_hex_03() throws {
        try invalidate(pathComponents: ["integer", "invalid-hex-03"])
    }

    @Test("[integer] invalid oct", .tags(.integer))
    func integer__invalid_oct() throws {
        try invalidate(pathComponents: ["integer", "invalid-oct"])
    }

    @Test("[integer] leading us", .tags(.integer))
    func integer__leading_us() throws {
        try invalidate(pathComponents: ["integer", "leading-us"])
    }

    @Test("[integer] leading us bin", .tags(.integer))
    func integer__leading_us_bin() throws {
        try invalidate(pathComponents: ["integer", "leading-us-bin"])
    }

    @Test("[integer] leading us hex", .tags(.integer))
    func integer__leading_us_hex() throws {
        try invalidate(pathComponents: ["integer", "leading-us-hex"])
    }

    @Test("[integer] leading us oct", .tags(.integer))
    func integer__leading_us_oct() throws {
        try invalidate(pathComponents: ["integer", "leading-us-oct"])
    }

    @Test("[integer] leading zero 01", .tags(.integer))
    func integer__leading_zero_01() throws {
        try invalidate(pathComponents: ["integer", "leading-zero-01"])
    }

    @Test("[integer] leading zero 02", .tags(.integer))
    func integer__leading_zero_02() throws {
        try invalidate(pathComponents: ["integer", "leading-zero-02"])
    }

    @Test("[integer] leading zero 03", .tags(.integer))
    func integer__leading_zero_03() throws {
        try invalidate(pathComponents: ["integer", "leading-zero-03"])
    }

    @Test("[integer] leading zero sign 01", .tags(.integer))
    func integer__leading_zero_sign_01() throws {
        try invalidate(pathComponents: ["integer", "leading-zero-sign-01"])
    }

    @Test("[integer] leading zero sign 02", .tags(.integer))
    func integer__leading_zero_sign_02() throws {
        try invalidate(pathComponents: ["integer", "leading-zero-sign-02"])
    }

    @Test("[integer] leading zero sign 03", .tags(.integer))
    func integer__leading_zero_sign_03() throws {
        try invalidate(pathComponents: ["integer", "leading-zero-sign-03"])
    }

    @Test("[integer] negative bin", .tags(.integer))
    func integer__negative_bin() throws {
        try invalidate(pathComponents: ["integer", "negative-bin"])
    }

    @Test("[integer] negative hex", .tags(.integer))
    func integer__negative_hex() throws {
        try invalidate(pathComponents: ["integer", "negative-hex"])
    }

    @Test("[integer] negative oct", .tags(.integer))
    func integer__negative_oct() throws {
        try invalidate(pathComponents: ["integer", "negative-oct"])
    }

    @Test("[integer] positive bin", .tags(.integer))
    func integer__positive_bin() throws {
        try invalidate(pathComponents: ["integer", "positive-bin"])
    }

    @Test("[integer] positive hex", .tags(.integer))
    func integer__positive_hex() throws {
        try invalidate(pathComponents: ["integer", "positive-hex"])
    }

    @Test("[integer] positive oct", .tags(.integer))
    func integer__positive_oct() throws {
        try invalidate(pathComponents: ["integer", "positive-oct"])
    }

    @Test("[integer] text after integer", .tags(.integer))
    func integer__text_after_integer() throws {
        try invalidate(pathComponents: ["integer", "text-after-integer"])
    }

    @Test("[integer] trailing us", .tags(.integer))
    func integer__trailing_us() throws {
        try invalidate(pathComponents: ["integer", "trailing-us"])
    }

    @Test("[integer] trailing us bin", .tags(.integer))
    func integer__trailing_us_bin() throws {
        try invalidate(pathComponents: ["integer", "trailing-us-bin"])
    }

    @Test("[integer] trailing us hex", .tags(.integer))
    func integer__trailing_us_hex() throws {
        try invalidate(pathComponents: ["integer", "trailing-us-hex"])
    }

    @Test("[integer] trailing us oct", .tags(.integer))
    func integer__trailing_us_oct() throws {
        try invalidate(pathComponents: ["integer", "trailing-us-oct"])
    }

    @Test("[integer] us after bin", .tags(.integer))
    func integer__us_after_bin() throws {
        try invalidate(pathComponents: ["integer", "us-after-bin"])
    }

    @Test("[integer] us after hex", .tags(.integer))
    func integer__us_after_hex() throws {
        try invalidate(pathComponents: ["integer", "us-after-hex"])
    }

    @Test("[integer] us after oct", .tags(.integer))
    func integer__us_after_oct() throws {
        try invalidate(pathComponents: ["integer", "us-after-oct"])
    }

    @Test("[key] after array", .tags(.key))
    func key__after_array() throws {
        try invalidate(pathComponents: ["key", "after-array"])
    }

    @Test("[key] after table", .tags(.key))
    func key__after_table() throws {
        try invalidate(pathComponents: ["key", "after-table"])
    }

    @Test("[key] after value", .tags(.key))
    func key__after_value() throws {
        try invalidate(pathComponents: ["key", "after-value"])
    }

    @Test("[key] bare invalid character 01", .tags(.key))
    func key__bare_invalid_character_01() throws {
        try invalidate(pathComponents: ["key", "bare-invalid-character-01"])
    }

    @Test("[key] bare invalid character 02", .tags(.key))
    func key__bare_invalid_character_02() throws {
        try invalidate(pathComponents: ["key", "bare-invalid-character-02"])
    }

    @Test("[key] dot", .tags(.key))
    func key__dot() throws {
        try invalidate(pathComponents: ["key", "dot"])
    }

    @Test("[key] dotdot", .tags(.key))
    func key__dotdot() throws {
        try invalidate(pathComponents: ["key", "dotdot"])
    }

    @Test("[key] dotted redefine table 01", .tags(.key))
    func key__dotted_redefine_table_01() throws {
        try invalidate(pathComponents: ["key", "dotted-redefine-table-01"])
    }

    @Test("[key] dotted redefine table 02", .tags(.key))
    func key__dotted_redefine_table_02() throws {
        try invalidate(pathComponents: ["key", "dotted-redefine-table-02"])
    }

    @Test("[key] duplicate keys 01", .tags(.key))
    func key__duplicate_keys_01() throws {
        try invalidate(pathComponents: ["key", "duplicate-keys-01"])
    }

    @Test("[key] duplicate keys 02", .tags(.key))
    func key__duplicate_keys_02() throws {
        try invalidate(pathComponents: ["key", "duplicate-keys-02"])
    }

    @Test("[key] duplicate keys 03", .tags(.key))
    func key__duplicate_keys_03() throws {
        try invalidate(pathComponents: ["key", "duplicate-keys-03"])
    }

    @Test("[key] duplicate keys 04", .tags(.key))
    func key__duplicate_keys_04() throws {
        try invalidate(pathComponents: ["key", "duplicate-keys-04"])
    }

    @Test("[key] duplicate keys 05", .tags(.key))
    func key__duplicate_keys_05() throws {
        try invalidate(pathComponents: ["key", "duplicate-keys-05"])
    }

    @Test("[key] duplicate keys 06", .tags(.key))
    func key__duplicate_keys_06() throws {
        try invalidate(pathComponents: ["key", "duplicate-keys-06"])
    }

    @Test("[key] duplicate keys 07", .tags(.key))
    func key__duplicate_keys_07() throws {
        try invalidate(pathComponents: ["key", "duplicate-keys-07"])
    }

    @Test("[key] duplicate keys 08", .tags(.key))
    func key__duplicate_keys_08() throws {
        try invalidate(pathComponents: ["key", "duplicate-keys-08"])
    }

    @Test("[key] duplicate keys 09", .tags(.key))
    func key__duplicate_keys_09() throws {
        try invalidate(pathComponents: ["key", "duplicate-keys-09"])
    }

    @Test("[key] empty", .tags(.key))
    func key__empty() throws {
        try invalidate(pathComponents: ["key", "empty"])
    }

    @Test("[key] end in escape", .tags(.key))
    func key__end_in_escape() throws {
        try invalidate(pathComponents: ["key", "end-in-escape"])
    }

    @Test("[key] escape", .tags(.key))
    func key__escape() throws {
        try invalidate(pathComponents: ["key", "escape"])
    }

    @Test("[key] hash", .tags(.key))
    func key__hash() throws {
        try invalidate(pathComponents: ["key", "hash"])
    }

    @Test("[key] multiline key 01", .tags(.key))
    func key__multiline_key_01() throws {
        try invalidate(pathComponents: ["key", "multiline-key-01"])
    }

    @Test("[key] multiline key 02", .tags(.key))
    func key__multiline_key_02() throws {
        try invalidate(pathComponents: ["key", "multiline-key-02"])
    }

    @Test("[key] multiline key 03", .tags(.key))
    func key__multiline_key_03() throws {
        try invalidate(pathComponents: ["key", "multiline-key-03"])
    }

    @Test("[key] multiline key 04", .tags(.key))
    func key__multiline_key_04() throws {
        try invalidate(pathComponents: ["key", "multiline-key-04"])
    }

    @Test("[key] newline 01", .tags(.key))
    func key__newline_01() throws {
        try invalidate(pathComponents: ["key", "newline-01"])
    }

    @Test("[key] newline 02", .tags(.key))
    func key__newline_02() throws {
        try invalidate(pathComponents: ["key", "newline-02"])
    }

    @Test("[key] newline 03", .tags(.key))
    func key__newline_03() throws {
        try invalidate(pathComponents: ["key", "newline-03"])
    }

    @Test("[key] newline 04", .tags(.key))
    func key__newline_04() throws {
        try invalidate(pathComponents: ["key", "newline-04"])
    }

    @Test("[key] newline 05", .tags(.key))
    func key__newline_05() throws {
        try invalidate(pathComponents: ["key", "newline-05"])
    }

    @Test("[key] newline 06", .tags(.key))
    func key__newline_06() throws {
        try invalidate(pathComponents: ["key", "newline-06"])
    }

    @Test("[key] no eol 01", .tags(.key))
    func key__no_eol_01() throws {
        try invalidate(pathComponents: ["key", "no-eol-01"])
    }

    @Test("[key] no eol 02", .tags(.key))
    func key__no_eol_02() throws {
        try invalidate(pathComponents: ["key", "no-eol-02"])
    }

    @Test("[key] no eol 03", .tags(.key))
    func key__no_eol_03() throws {
        try invalidate(pathComponents: ["key", "no-eol-03"])
    }

    @Test("[key] no eol 04", .tags(.key))
    func key__no_eol_04() throws {
        try invalidate(pathComponents: ["key", "no-eol-04"])
    }

    @Test("[key] no eol 05", .tags(.key))
    func key__no_eol_05() throws {
        try invalidate(pathComponents: ["key", "no-eol-05"])
    }

    @Test("[key] no eol 06", .tags(.key))
    func key__no_eol_06() throws {
        try invalidate(pathComponents: ["key", "no-eol-06"])
    }

    @Test("[key] no eol 07", .tags(.key))
    func key__no_eol_07() throws {
        try invalidate(pathComponents: ["key", "no-eol-07"])
    }

    @Test("[key] only float", .tags(.key))
    func key__only_float() throws {
        try invalidate(pathComponents: ["key", "only-float"])
    }

    @Test("[key] only int", .tags(.key))
    func key__only_int() throws {
        try invalidate(pathComponents: ["key", "only-int"])
    }

    @Test("[key] only str", .tags(.key))
    func key__only_str() throws {
        try invalidate(pathComponents: ["key", "only-str"])
    }

    @Test("[key] open bracket", .tags(.key))
    func key__open_bracket() throws {
        try invalidate(pathComponents: ["key", "open-bracket"])
    }

    @Test("[key] partial quoted", .tags(.key))
    func key__partial_quoted() throws {
        try invalidate(pathComponents: ["key", "partial-quoted"])
    }

    @Test("[key] quoted unclosed 01", .tags(.key))
    func key__quoted_unclosed_01() throws {
        try invalidate(pathComponents: ["key", "quoted-unclosed-01"])
    }

    @Test("[key] quoted unclosed 02", .tags(.key))
    func key__quoted_unclosed_02() throws {
        try invalidate(pathComponents: ["key", "quoted-unclosed-02"])
    }

    @Test("[key] single open bracket", .tags(.key))
    func key__single_open_bracket() throws {
        try invalidate(pathComponents: ["key", "single-open-bracket"])
    }

    @Test("[key] space", .tags(.key))
    func key__space() throws {
        try invalidate(pathComponents: ["key", "space"])
    }

    @Test("[key] special character", .tags(.key))
    func key__special_character() throws {
        try invalidate(pathComponents: ["key", "special-character"])
    }

    @Test("[key] start bracket", .tags(.key))
    func key__start_bracket() throws {
        try invalidate(pathComponents: ["key", "start-bracket"])
    }

    @Test("[key] start dot", .tags(.key))
    func key__start_dot() throws {
        try invalidate(pathComponents: ["key", "start-dot"])
    }

    @Test("[key] two equals 01", .tags(.key))
    func key__two_equals_01() throws {
        try invalidate(pathComponents: ["key", "two-equals-01"])
    }

    @Test("[key] two equals 02", .tags(.key))
    func key__two_equals_02() throws {
        try invalidate(pathComponents: ["key", "two-equals-02"])
    }

    @Test("[key] two equals 03", .tags(.key))
    func key__two_equals_03() throws {
        try invalidate(pathComponents: ["key", "two-equals-03"])
    }

    @Test("[key] without value 01", .tags(.key))
    func key__without_value_01() throws {
        try invalidate(pathComponents: ["key", "without-value-01"])
    }

    @Test("[key] without value 02", .tags(.key))
    func key__without_value_02() throws {
        try invalidate(pathComponents: ["key", "without-value-02"])
    }

    @Test("[key] without value 03", .tags(.key))
    func key__without_value_03() throws {
        try invalidate(pathComponents: ["key", "without-value-03"])
    }

    @Test("[key] without value 04", .tags(.key))
    func key__without_value_04() throws {
        try invalidate(pathComponents: ["key", "without-value-04"])
    }

    @Test("[key] without value 05", .tags(.key))
    func key__without_value_05() throws {
        try invalidate(pathComponents: ["key", "without-value-05"])
    }

    @Test("[key] without value 06", .tags(.key))
    func key__without_value_06() throws {
        try invalidate(pathComponents: ["key", "without-value-06"])
    }

    @Test("[key] without value 07", .tags(.key))
    func key__without_value_07() throws {
        try invalidate(pathComponents: ["key", "without-value-07"])
    }

    @Test("[local-date] day 1digit", .tags(.local_date))
    func local_date__day_1digit() throws {
        try invalidate(pathComponents: ["local-date", "day-1digit"])
    }

    @Test("[local-date] feb 29", .tags(.local_date))
    func local_date__feb_29() throws {
        try invalidate(pathComponents: ["local-date", "feb-29"])
    }

    @Test("[local-date] feb 30", .tags(.local_date))
    func local_date__feb_30() throws {
        try invalidate(pathComponents: ["local-date", "feb-30"])
    }

    @Test("[local-date] mday over", .tags(.local_date))
    func local_date__mday_over() throws {
        try invalidate(pathComponents: ["local-date", "mday-over"])
    }

    @Test("[local-date] mday under", .tags(.local_date))
    func local_date__mday_under() throws {
        try invalidate(pathComponents: ["local-date", "mday-under"])
    }

    @Test("[local-date] month over", .tags(.local_date))
    func local_date__month_over() throws {
        try invalidate(pathComponents: ["local-date", "month-over"])
    }

    @Test("[local-date] month under", .tags(.local_date))
    func local_date__month_under() throws {
        try invalidate(pathComponents: ["local-date", "month-under"])
    }

    @Test("[local-date] no leads", .tags(.local_date))
    func local_date__no_leads() throws {
        try invalidate(pathComponents: ["local-date", "no-leads"])
    }

    @Test("[local-date] no leads with milli", .tags(.local_date))
    func local_date__no_leads_with_milli() throws {
        try invalidate(pathComponents: ["local-date", "no-leads-with-milli"])
    }

    @Test("[local-date] trailing t", .tags(.local_date))
    func local_date__trailing_t() throws {
        try invalidate(pathComponents: ["local-date", "trailing-t"])
    }

    @Test("[local-date] y10k", .tags(.local_date))
    func local_date__y10k() throws {
        try invalidate(pathComponents: ["local-date", "y10k"])
    }

    @Test("[local-date] year 3digits", .tags(.local_date))
    func local_date__year_3digits() throws {
        try invalidate(pathComponents: ["local-date", "year-3digits"])
    }

    @Test("[local-datetime] feb 29", .tags(.local_datetime))
    func local_datetime__feb_29() throws {
        try invalidate(pathComponents: ["local-datetime", "feb-29"])
    }

    @Test("[local-datetime] feb 30", .tags(.local_datetime))
    func local_datetime__feb_30() throws {
        try invalidate(pathComponents: ["local-datetime", "feb-30"])
    }

    @Test("[local-datetime] hour over", .tags(.local_datetime))
    func local_datetime__hour_over() throws {
        try invalidate(pathComponents: ["local-datetime", "hour-over"])
    }

    @Test("[local-datetime] mday over", .tags(.local_datetime))
    func local_datetime__mday_over() throws {
        try invalidate(pathComponents: ["local-datetime", "mday-over"])
    }

    @Test("[local-datetime] mday under", .tags(.local_datetime))
    func local_datetime__mday_under() throws {
        try invalidate(pathComponents: ["local-datetime", "mday-under"])
    }

    @Test("[local-datetime] minute over", .tags(.local_datetime))
    func local_datetime__minute_over() throws {
        try invalidate(pathComponents: ["local-datetime", "minute-over"])
    }

    @Test("[local-datetime] month over", .tags(.local_datetime))
    func local_datetime__month_over() throws {
        try invalidate(pathComponents: ["local-datetime", "month-over"])
    }

    @Test("[local-datetime] month under", .tags(.local_datetime))
    func local_datetime__month_under() throws {
        try invalidate(pathComponents: ["local-datetime", "month-under"])
    }

    @Test("[local-datetime] no leads", .tags(.local_datetime))
    func local_datetime__no_leads() throws {
        try invalidate(pathComponents: ["local-datetime", "no-leads"])
    }

    @Test("[local-datetime] no leads with milli", .tags(.local_datetime))
    func local_datetime__no_leads_with_milli() throws {
        try invalidate(pathComponents: ["local-datetime", "no-leads-with-milli"])
    }

    @Test("[local-datetime] no t", .tags(.local_datetime))
    func local_datetime__no_t() throws {
        try invalidate(pathComponents: ["local-datetime", "no-t"])
    }

    @Test("[local-datetime] second over", .tags(.local_datetime))
    func local_datetime__second_over() throws {
        try invalidate(pathComponents: ["local-datetime", "second-over"])
    }

    @Test("[local-datetime] time no leads", .tags(.local_datetime))
    func local_datetime__time_no_leads() throws {
        try invalidate(pathComponents: ["local-datetime", "time-no-leads"])
    }

    @Test("[local-datetime] y10k", .tags(.local_datetime))
    func local_datetime__y10k() throws {
        try invalidate(pathComponents: ["local-datetime", "y10k"])
    }

    @Test("[local-time] hour over", .tags(.local_time))
    func local_time__hour_over() throws {
        try invalidate(pathComponents: ["local-time", "hour-over"])
    }

    @Test("[local-time] minute over", .tags(.local_time))
    func local_time__minute_over() throws {
        try invalidate(pathComponents: ["local-time", "minute-over"])
    }

    @Test("[local-time] second over", .tags(.local_time))
    func local_time__second_over() throws {
        try invalidate(pathComponents: ["local-time", "second-over"])
    }

    @Test("[local-time] time no leads 01", .tags(.local_time))
    func local_time__time_no_leads_01() throws {
        try invalidate(pathComponents: ["local-time", "time-no-leads-01"])
    }

    @Test("[local-time] time no leads 02", .tags(.local_time))
    func local_time__time_no_leads_02() throws {
        try invalidate(pathComponents: ["local-time", "time-no-leads-02"])
    }

    @Test("[local-time] trailing dot", .tags(.local_time))
    func local_time__trailing_dot() throws {
        try invalidate(pathComponents: ["local-time", "trailing-dot"])
    }

    @Test("[local-time] trailing dotdot", .tags(.local_time))
    func local_time__trailing_dotdot() throws {
        try invalidate(pathComponents: ["local-time", "trailing-dotdot"])
    }

    @Test("[spec-1.1.0] common 16 0", .tags(.spec_1_1_0))
    func spec_1_1_0__common_16_0() throws {
        try invalidate(pathComponents: ["spec-1.1.0", "common-16-0"])
    }

    @Test("[spec-1.1.0] common 19 0", .tags(.spec_1_1_0))
    func spec_1_1_0__common_19_0() throws {
        try invalidate(pathComponents: ["spec-1.1.0", "common-19-0"])
    }

    @Test("[spec-1.1.0] common 2", .tags(.spec_1_1_0))
    func spec_1_1_0__common_2() throws {
        try invalidate(pathComponents: ["spec-1.1.0", "common-2"])
    }

    @Test("[spec-1.1.0] common 46 0", .tags(.spec_1_1_0))
    func spec_1_1_0__common_46_0() throws {
        try invalidate(pathComponents: ["spec-1.1.0", "common-46-0"])
    }

    @Test("[spec-1.1.0] common 46 1", .tags(.spec_1_1_0))
    func spec_1_1_0__common_46_1() throws {
        try invalidate(pathComponents: ["spec-1.1.0", "common-46-1"])
    }

    @Test("[spec-1.1.0] common 49 0", .tags(.spec_1_1_0))
    func spec_1_1_0__common_49_0() throws {
        try invalidate(pathComponents: ["spec-1.1.0", "common-49-0"])
    }

    @Test("[spec-1.1.0] common 5", .tags(.spec_1_1_0))
    func spec_1_1_0__common_5() throws {
        try invalidate(pathComponents: ["spec-1.1.0", "common-5"])
    }

    @Test("[spec-1.1.0] common 50 0", .tags(.spec_1_1_0))
    func spec_1_1_0__common_50_0() throws {
        try invalidate(pathComponents: ["spec-1.1.0", "common-50-0"])
    }

    @Test("[string] bad byte escape", .tags(.string))
    func string__bad_byte_escape() throws {
        try invalidate(pathComponents: ["string", "bad-byte-escape"])
    }

    @Test("[string] bad concat", .tags(.string))
    func string__bad_concat() throws {
        try invalidate(pathComponents: ["string", "bad-concat"])
    }

    @Test("[string] bad escape 01", .tags(.string))
    func string__bad_escape_01() throws {
        try invalidate(pathComponents: ["string", "bad-escape-01"])
    }

    @Test("[string] bad escape 02", .tags(.string))
    func string__bad_escape_02() throws {
        try invalidate(pathComponents: ["string", "bad-escape-02"])
    }

    @Test("[string] bad escape 03", .tags(.string))
    func string__bad_escape_03() throws {
        try invalidate(pathComponents: ["string", "bad-escape-03"])
    }

    @Test("[string] bad escape 04", .tags(.string))
    func string__bad_escape_04() throws {
        try invalidate(pathComponents: ["string", "bad-escape-04"])
    }

    @Test("[string] bad escape 05", .tags(.string))
    func string__bad_escape_05() throws {
        try invalidate(pathComponents: ["string", "bad-escape-05"])
    }

    @Test("[string] bad hex esc 01", .tags(.string))
    func string__bad_hex_esc_01() throws {
        try invalidate(pathComponents: ["string", "bad-hex-esc-01"])
    }

    @Test("[string] bad hex esc 02", .tags(.string))
    func string__bad_hex_esc_02() throws {
        try invalidate(pathComponents: ["string", "bad-hex-esc-02"])
    }

    @Test("[string] bad hex esc 03", .tags(.string))
    func string__bad_hex_esc_03() throws {
        try invalidate(pathComponents: ["string", "bad-hex-esc-03"])
    }

    @Test("[string] bad hex esc 04", .tags(.string))
    func string__bad_hex_esc_04() throws {
        try invalidate(pathComponents: ["string", "bad-hex-esc-04"])
    }

    @Test("[string] bad hex esc 05", .tags(.string))
    func string__bad_hex_esc_05() throws {
        try invalidate(pathComponents: ["string", "bad-hex-esc-05"])
    }

    @Test("[string] bad multiline", .tags(.string))
    func string__bad_multiline() throws {
        try invalidate(pathComponents: ["string", "bad-multiline"])
    }

    @Test("[string] bad slash escape", .tags(.string))
    func string__bad_slash_escape() throws {
        try invalidate(pathComponents: ["string", "bad-slash-escape"])
    }

    @Test("[string] bad uni esc 01", .tags(.string))
    func string__bad_uni_esc_01() throws {
        try invalidate(pathComponents: ["string", "bad-uni-esc-01"])
    }

    @Test("[string] bad uni esc 02", .tags(.string))
    func string__bad_uni_esc_02() throws {
        try invalidate(pathComponents: ["string", "bad-uni-esc-02"])
    }

    @Test("[string] bad uni esc 03", .tags(.string))
    func string__bad_uni_esc_03() throws {
        try invalidate(pathComponents: ["string", "bad-uni-esc-03"])
    }

    @Test("[string] bad uni esc 04", .tags(.string))
    func string__bad_uni_esc_04() throws {
        try invalidate(pathComponents: ["string", "bad-uni-esc-04"])
    }

    @Test("[string] bad uni esc 05", .tags(.string))
    func string__bad_uni_esc_05() throws {
        try invalidate(pathComponents: ["string", "bad-uni-esc-05"])
    }

    @Test("[string] bad uni esc 06", .tags(.string))
    func string__bad_uni_esc_06() throws {
        try invalidate(pathComponents: ["string", "bad-uni-esc-06"])
    }

    @Test("[string] bad uni esc 07", .tags(.string))
    func string__bad_uni_esc_07() throws {
        try invalidate(pathComponents: ["string", "bad-uni-esc-07"])
    }

    @Test("[string] bad uni esc ml 01", .tags(.string))
    func string__bad_uni_esc_ml_01() throws {
        try invalidate(pathComponents: ["string", "bad-uni-esc-ml-01"])
    }

    @Test("[string] bad uni esc ml 02", .tags(.string))
    func string__bad_uni_esc_ml_02() throws {
        try invalidate(pathComponents: ["string", "bad-uni-esc-ml-02"])
    }

    @Test("[string] bad uni esc ml 03", .tags(.string))
    func string__bad_uni_esc_ml_03() throws {
        try invalidate(pathComponents: ["string", "bad-uni-esc-ml-03"])
    }

    @Test("[string] bad uni esc ml 04", .tags(.string))
    func string__bad_uni_esc_ml_04() throws {
        try invalidate(pathComponents: ["string", "bad-uni-esc-ml-04"])
    }

    @Test("[string] bad uni esc ml 05", .tags(.string))
    func string__bad_uni_esc_ml_05() throws {
        try invalidate(pathComponents: ["string", "bad-uni-esc-ml-05"])
    }

    @Test("[string] bad uni esc ml 06", .tags(.string))
    func string__bad_uni_esc_ml_06() throws {
        try invalidate(pathComponents: ["string", "bad-uni-esc-ml-06"])
    }

    @Test("[string] bad uni esc ml 07", .tags(.string))
    func string__bad_uni_esc_ml_07() throws {
        try invalidate(pathComponents: ["string", "bad-uni-esc-ml-07"])
    }

    @Test("[string] basic multiline out of range unicode escape 01", .tags(.string))
    func string__basic_multiline_out_of_range_unicode_escape_01() throws {
        try invalidate(pathComponents: ["string", "basic-multiline-out-of-range-unicode-escape-01"])
    }

    @Test("[string] basic multiline out of range unicode escape 02", .tags(.string))
    func string__basic_multiline_out_of_range_unicode_escape_02() throws {
        try invalidate(pathComponents: ["string", "basic-multiline-out-of-range-unicode-escape-02"])
    }

    @Test("[string] basic multiline quotes", .tags(.string))
    func string__basic_multiline_quotes() throws {
        try invalidate(pathComponents: ["string", "basic-multiline-quotes"])
    }

    @Test("[string] basic multiline unknown escape", .tags(.string))
    func string__basic_multiline_unknown_escape() throws {
        try invalidate(pathComponents: ["string", "basic-multiline-unknown-escape"])
    }

    @Test("[string] basic out of range unicode escape 01", .tags(.string))
    func string__basic_out_of_range_unicode_escape_01() throws {
        try invalidate(pathComponents: ["string", "basic-out-of-range-unicode-escape-01"])
    }

    @Test("[string] basic out of range unicode escape 02", .tags(.string))
    func string__basic_out_of_range_unicode_escape_02() throws {
        try invalidate(pathComponents: ["string", "basic-out-of-range-unicode-escape-02"])
    }

    @Test("[string] basic unknown escape", .tags(.string))
    func string__basic_unknown_escape() throws {
        try invalidate(pathComponents: ["string", "basic-unknown-escape"])
    }

    @Test("[string] literal multiline quotes 01", .tags(.string))
    func string__literal_multiline_quotes_01() throws {
        try invalidate(pathComponents: ["string", "literal-multiline-quotes-01"])
    }

    @Test("[string] literal multiline quotes 02", .tags(.string))
    func string__literal_multiline_quotes_02() throws {
        try invalidate(pathComponents: ["string", "literal-multiline-quotes-02"])
    }

    @Test("[string] missing quotes", .tags(.string))
    func string__missing_quotes() throws {
        try invalidate(pathComponents: ["string", "missing-quotes"])
    }

    @Test("[string] missing quotes array", .tags(.string))
    func string__missing_quotes_array() throws {
        try invalidate(pathComponents: ["string", "missing-quotes-array"])
    }

    @Test("[string] missing quotes inline table", .tags(.string))
    func string__missing_quotes_inline_table() throws {
        try invalidate(pathComponents: ["string", "missing-quotes-inline-table"])
    }

    @Test("[string] multiline bad escape 01", .tags(.string))
    func string__multiline_bad_escape_01() throws {
        try invalidate(pathComponents: ["string", "multiline-bad-escape-01"])
    }

    @Test("[string] multiline bad escape 02", .tags(.string))
    func string__multiline_bad_escape_02() throws {
        try invalidate(pathComponents: ["string", "multiline-bad-escape-02"])
    }

    @Test("[string] multiline bad escape 03", .tags(.string))
    func string__multiline_bad_escape_03() throws {
        try invalidate(pathComponents: ["string", "multiline-bad-escape-03"])
    }

    @Test("[string] multiline bad escape 04", .tags(.string))
    func string__multiline_bad_escape_04() throws {
        try invalidate(pathComponents: ["string", "multiline-bad-escape-04"])
    }

    @Test("[string] multiline escape space 01", .tags(.string))
    func string__multiline_escape_space_01() throws {
        try invalidate(pathComponents: ["string", "multiline-escape-space-01"])
    }

    @Test("[string] multiline escape space 02", .tags(.string))
    func string__multiline_escape_space_02() throws {
        try invalidate(pathComponents: ["string", "multiline-escape-space-02"])
    }

    @Test("[string] multiline lit no close 01", .tags(.string))
    func string__multiline_lit_no_close_01() throws {
        try invalidate(pathComponents: ["string", "multiline-lit-no-close-01"])
    }

    @Test("[string] multiline lit no close 02", .tags(.string))
    func string__multiline_lit_no_close_02() throws {
        try invalidate(pathComponents: ["string", "multiline-lit-no-close-02"])
    }

    @Test("[string] multiline lit no close 03", .tags(.string))
    func string__multiline_lit_no_close_03() throws {
        try invalidate(pathComponents: ["string", "multiline-lit-no-close-03"])
    }

    @Test("[string] multiline lit no close 04", .tags(.string))
    func string__multiline_lit_no_close_04() throws {
        try invalidate(pathComponents: ["string", "multiline-lit-no-close-04"])
    }

    @Test("[string] multiline no close 01", .tags(.string))
    func string__multiline_no_close_01() throws {
        try invalidate(pathComponents: ["string", "multiline-no-close-01"])
    }

    @Test("[string] multiline no close 02", .tags(.string))
    func string__multiline_no_close_02() throws {
        try invalidate(pathComponents: ["string", "multiline-no-close-02"])
    }

    @Test("[string] multiline no close 03", .tags(.string))
    func string__multiline_no_close_03() throws {
        try invalidate(pathComponents: ["string", "multiline-no-close-03"])
    }

    @Test("[string] multiline no close 04", .tags(.string))
    func string__multiline_no_close_04() throws {
        try invalidate(pathComponents: ["string", "multiline-no-close-04"])
    }

    @Test("[string] multiline no close 05", .tags(.string))
    func string__multiline_no_close_05() throws {
        try invalidate(pathComponents: ["string", "multiline-no-close-05"])
    }

    @Test("[string] multiline quotes 01", .tags(.string))
    func string__multiline_quotes_01() throws {
        try invalidate(pathComponents: ["string", "multiline-quotes-01"])
    }

    @Test("[string] no close 01", .tags(.string))
    func string__no_close_01() throws {
        try invalidate(pathComponents: ["string", "no-close-01"])
    }

    @Test("[string] no close 02", .tags(.string))
    func string__no_close_02() throws {
        try invalidate(pathComponents: ["string", "no-close-02"])
    }

    @Test("[string] no close 03", .tags(.string))
    func string__no_close_03() throws {
        try invalidate(pathComponents: ["string", "no-close-03"])
    }

    @Test("[string] no close 04", .tags(.string))
    func string__no_close_04() throws {
        try invalidate(pathComponents: ["string", "no-close-04"])
    }

    @Test("[string] no close 05", .tags(.string))
    func string__no_close_05() throws {
        try invalidate(pathComponents: ["string", "no-close-05"])
    }

    @Test("[string] no close 06", .tags(.string))
    func string__no_close_06() throws {
        try invalidate(pathComponents: ["string", "no-close-06"])
    }

    @Test("[string] no close 07", .tags(.string))
    func string__no_close_07() throws {
        try invalidate(pathComponents: ["string", "no-close-07"])
    }

    @Test("[string] no close 08", .tags(.string))
    func string__no_close_08() throws {
        try invalidate(pathComponents: ["string", "no-close-08"])
    }

    @Test("[string] no close 09", .tags(.string))
    func string__no_close_09() throws {
        try invalidate(pathComponents: ["string", "no-close-09"])
    }

    @Test("[string] no close 10", .tags(.string))
    func string__no_close_10() throws {
        try invalidate(pathComponents: ["string", "no-close-10"])
    }

    @Test("[string] no open 01", .tags(.string))
    func string__no_open_01() throws {
        try invalidate(pathComponents: ["string", "no-open-01"])
    }

    @Test("[string] no open 02", .tags(.string))
    func string__no_open_02() throws {
        try invalidate(pathComponents: ["string", "no-open-02"])
    }

    @Test("[string] no open 03", .tags(.string))
    func string__no_open_03() throws {
        try invalidate(pathComponents: ["string", "no-open-03"])
    }

    @Test("[string] no open 04", .tags(.string))
    func string__no_open_04() throws {
        try invalidate(pathComponents: ["string", "no-open-04"])
    }

    @Test("[string] no open 05", .tags(.string))
    func string__no_open_05() throws {
        try invalidate(pathComponents: ["string", "no-open-05"])
    }

    @Test("[string] no open 06", .tags(.string))
    func string__no_open_06() throws {
        try invalidate(pathComponents: ["string", "no-open-06"])
    }

    @Test("[string] no open 07", .tags(.string))
    func string__no_open_07() throws {
        try invalidate(pathComponents: ["string", "no-open-07"])
    }

    @Test("[string] no open 08", .tags(.string))
    func string__no_open_08() throws {
        try invalidate(pathComponents: ["string", "no-open-08"])
    }

    @Test("[string] text after string", .tags(.string))
    func string__text_after_string() throws {
        try invalidate(pathComponents: ["string", "text-after-string"])
    }

    @Test("[string] wrong close", .tags(.string))
    func string__wrong_close() throws {
        try invalidate(pathComponents: ["string", "wrong-close"])
    }

    @Test("[table] append with dotted keys 01", .tags(.table))
    func table__append_with_dotted_keys_01() throws {
        try invalidate(pathComponents: ["table", "append-with-dotted-keys-01"])
    }

    @Test("[table] append with dotted keys 02", .tags(.table))
    func table__append_with_dotted_keys_02() throws {
        try invalidate(pathComponents: ["table", "append-with-dotted-keys-02"])
    }

    @Test("[table] append with dotted keys 03", .tags(.table))
    func table__append_with_dotted_keys_03() throws {
        try invalidate(pathComponents: ["table", "append-with-dotted-keys-03"])
    }

    @Test("[table] append with dotted keys 04", .tags(.table))
    func table__append_with_dotted_keys_04() throws {
        try invalidate(pathComponents: ["table", "append-with-dotted-keys-04"])
    }

    @Test("[table] append with dotted keys 05", .tags(.table))
    func table__append_with_dotted_keys_05() throws {
        try invalidate(pathComponents: ["table", "append-with-dotted-keys-05"])
    }

    @Test("[table] append with dotted keys 06", .tags(.table))
    func table__append_with_dotted_keys_06() throws {
        try invalidate(pathComponents: ["table", "append-with-dotted-keys-06"])
    }

    @Test("[table] append with dotted keys 07", .tags(.table))
    func table__append_with_dotted_keys_07() throws {
        try invalidate(pathComponents: ["table", "append-with-dotted-keys-07"])
    }

    @Test("[table] array empty", .tags(.table))
    func table__array_empty() throws {
        try invalidate(pathComponents: ["table", "array-empty"])
    }

    @Test("[table] array implicit", .tags(.table))
    func table__array_implicit() throws {
        try invalidate(pathComponents: ["table", "array-implicit"])
    }

    @Test("[table] array no close 01", .tags(.table))
    func table__array_no_close_01() throws {
        try invalidate(pathComponents: ["table", "array-no-close-01"])
    }

    @Test("[table] array no close 02", .tags(.table))
    func table__array_no_close_02() throws {
        try invalidate(pathComponents: ["table", "array-no-close-02"])
    }

    @Test("[table] array no close 03", .tags(.table))
    func table__array_no_close_03() throws {
        try invalidate(pathComponents: ["table", "array-no-close-03"])
    }

    @Test("[table] array no close 04", .tags(.table))
    func table__array_no_close_04() throws {
        try invalidate(pathComponents: ["table", "array-no-close-04"])
    }

    @Test("[table] bare invalid character 01", .tags(.table))
    func table__bare_invalid_character_01() throws {
        try invalidate(pathComponents: ["table", "bare-invalid-character-01"])
    }

    @Test("[table] bare invalid character 02", .tags(.table))
    func table__bare_invalid_character_02() throws {
        try invalidate(pathComponents: ["table", "bare-invalid-character-02"])
    }

    @Test("[table] dot", .tags(.table))
    func table__dot() throws {
        try invalidate(pathComponents: ["table", "dot"])
    }

    @Test("[table] dotdot", .tags(.table))
    func table__dotdot() throws {
        try invalidate(pathComponents: ["table", "dotdot"])
    }

    @Test("[table] duplicate key 01", .tags(.table))
    func table__duplicate_key_01() throws {
        try invalidate(pathComponents: ["table", "duplicate-key-01"])
    }

    @Test("[table] duplicate key 02", .tags(.table))
    func table__duplicate_key_02() throws {
        try invalidate(pathComponents: ["table", "duplicate-key-02"])
    }

    @Test("[table] duplicate key 03", .tags(.table))
    func table__duplicate_key_03() throws {
        try invalidate(pathComponents: ["table", "duplicate-key-03"])
    }

    @Test("[table] duplicate key 04", .tags(.table))
    func table__duplicate_key_04() throws {
        try invalidate(pathComponents: ["table", "duplicate-key-04"])
    }

    @Test("[table] duplicate key 05", .tags(.table))
    func table__duplicate_key_05() throws {
        try invalidate(pathComponents: ["table", "duplicate-key-05"])
    }

    @Test("[table] duplicate key 06", .tags(.table))
    func table__duplicate_key_06() throws {
        try invalidate(pathComponents: ["table", "duplicate-key-06"])
    }

    @Test("[table] duplicate key 07", .tags(.table))
    func table__duplicate_key_07() throws {
        try invalidate(pathComponents: ["table", "duplicate-key-07"])
    }

    @Test("[table] duplicate key 08", .tags(.table))
    func table__duplicate_key_08() throws {
        try invalidate(pathComponents: ["table", "duplicate-key-08"])
    }

    @Test("[table] duplicate key 09", .tags(.table))
    func table__duplicate_key_09() throws {
        try invalidate(pathComponents: ["table", "duplicate-key-09"])
    }

    @Test("[table] duplicate key 10", .tags(.table))
    func table__duplicate_key_10() throws {
        try invalidate(pathComponents: ["table", "duplicate-key-10"])
    }

    @Test("[table] empty", .tags(.table))
    func table__empty() throws {
        try invalidate(pathComponents: ["table", "empty"])
    }

    @Test("[table] empty implicit table", .tags(.table))
    func table__empty_implicit_table() throws {
        try invalidate(pathComponents: ["table", "empty-implicit-table"])
    }

    @Test("[table] equals sign", .tags(.table))
    func table__equals_sign() throws {
        try invalidate(pathComponents: ["table", "equals-sign"])
    }

    @Test("[table] llbrace", .tags(.table))
    func table__llbrace() throws {
        try invalidate(pathComponents: ["table", "llbrace"])
    }

    @Test("[table] multiline key 01", .tags(.table))
    func table__multiline_key_01() throws {
        try invalidate(pathComponents: ["table", "multiline-key-01"])
    }

    @Test("[table] multiline key 02", .tags(.table))
    func table__multiline_key_02() throws {
        try invalidate(pathComponents: ["table", "multiline-key-02"])
    }

    @Test("[table] nested brackets close", .tags(.table))
    func table__nested_brackets_close() throws {
        try invalidate(pathComponents: ["table", "nested-brackets-close"])
    }

    @Test("[table] nested brackets open", .tags(.table))
    func table__nested_brackets_open() throws {
        try invalidate(pathComponents: ["table", "nested-brackets-open"])
    }

    @Test("[table] newline 01", .tags(.table))
    func table__newline_01() throws {
        try invalidate(pathComponents: ["table", "newline-01"])
    }

    @Test("[table] newline 02", .tags(.table))
    func table__newline_02() throws {
        try invalidate(pathComponents: ["table", "newline-02"])
    }

    @Test("[table] newline 03", .tags(.table))
    func table__newline_03() throws {
        try invalidate(pathComponents: ["table", "newline-03"])
    }

    @Test("[table] newline 04", .tags(.table))
    func table__newline_04() throws {
        try invalidate(pathComponents: ["table", "newline-04"])
    }

    @Test("[table] newline 05", .tags(.table))
    func table__newline_05() throws {
        try invalidate(pathComponents: ["table", "newline-05"])
    }

    @Test("[table] no close 01", .tags(.table))
    func table__no_close_01() throws {
        try invalidate(pathComponents: ["table", "no-close-01"])
    }

    @Test("[table] no close 02", .tags(.table))
    func table__no_close_02() throws {
        try invalidate(pathComponents: ["table", "no-close-02"])
    }

    @Test("[table] no close 03", .tags(.table))
    func table__no_close_03() throws {
        try invalidate(pathComponents: ["table", "no-close-03"])
    }

    @Test("[table] no close 04", .tags(.table))
    func table__no_close_04() throws {
        try invalidate(pathComponents: ["table", "no-close-04"])
    }

    @Test("[table] no close 05", .tags(.table))
    func table__no_close_05() throws {
        try invalidate(pathComponents: ["table", "no-close-05"])
    }

    @Test("[table] no close 06", .tags(.table))
    func table__no_close_06() throws {
        try invalidate(pathComponents: ["table", "no-close-06"])
    }

    @Test("[table] no close 07", .tags(.table))
    func table__no_close_07() throws {
        try invalidate(pathComponents: ["table", "no-close-07"])
    }

    @Test("[table] no close 08", .tags(.table))
    func table__no_close_08() throws {
        try invalidate(pathComponents: ["table", "no-close-08"])
    }

    @Test("[table] no close 09", .tags(.table))
    func table__no_close_09() throws {
        try invalidate(pathComponents: ["table", "no-close-09"])
    }

    @Test("[table] overwrite array in parent", .tags(.table))
    func table__overwrite_array_in_parent() throws {
        try invalidate(pathComponents: ["table", "overwrite-array-in-parent"])
    }

    @Test("[table] overwrite bool with array", .tags(.table))
    func table__overwrite_bool_with_array() throws {
        try invalidate(pathComponents: ["table", "overwrite-bool-with-array"])
    }

    @Test("[table] overwrite with deep table", .tags(.table))
    func table__overwrite_with_deep_table() throws {
        try invalidate(pathComponents: ["table", "overwrite-with-deep-table"])
    }

    @Test("[table] redefine 01", .tags(.table))
    func table__redefine_01() throws {
        try invalidate(pathComponents: ["table", "redefine-01"])
    }

    @Test("[table] redefine 02", .tags(.table))
    func table__redefine_02() throws {
        try invalidate(pathComponents: ["table", "redefine-02"])
    }

    @Test("[table] redefine 03", .tags(.table))
    func table__redefine_03() throws {
        try invalidate(pathComponents: ["table", "redefine-03"])
    }

    @Test("[table] rrbrace", .tags(.table))
    func table__rrbrace() throws {
        try invalidate(pathComponents: ["table", "rrbrace"])
    }

    @Test("[table] super twice", .tags(.table))
    func table__super_twice() throws {
        try invalidate(pathComponents: ["table", "super-twice"])
    }

    @Test("[table] text after table", .tags(.table))
    func table__text_after_table() throws {
        try invalidate(pathComponents: ["table", "text-after-table"])
    }

    @Test("[table] trailing dot", .tags(.table))
    func table__trailing_dot() throws {
        try invalidate(pathComponents: ["table", "trailing-dot"])
    }

    @Test("[table] whitespace", .tags(.table))
    func table__whitespace() throws {
        try invalidate(pathComponents: ["table", "whitespace"])
    }

    @Test("[table] with pound", .tags(.table))
    func table__with_pound() throws {
        try invalidate(pathComponents: ["table", "with-pound"])
    }
}
