// Generated by Scripts/sync_compliance_tests.py
// Source: toml-test commit 8be0db7469af2d97449e0a06075a1a6ecdc60231 (spec 1.0.0)

import Foundation
import Testing
import TOMLDecoder

@Suite
struct TOMLInvalidationTests {
    private var directoryURL: URL {
        URL(fileURLWithPath: #filePath)
            .deletingLastPathComponent()
            .appendingPathComponent("invalid_fixtures")
    }

    private func invalidate(pathComponents: [String], sourceLocation: SourceLocation = #_sourceLocation) throws {
        let baseURL = pathComponents.reduce(directoryURL) { $0.appendingPathComponent($1) }
        let tomlURL = baseURL.appendingPathExtension("toml")
        try TOMLComplianceSupport.verifyInvalidFixture(tomlURL: tomlURL, sourceLocation: sourceLocation)
    }

    @Test(.tags(.array))
    func `[array] double comma 01`() throws {
        try invalidate(pathComponents: ["array", "double-comma-01"])
    }

    @Test(.tags(.array))
    func `[array] double comma 02`() throws {
        try invalidate(pathComponents: ["array", "double-comma-02"])
    }

    @Test(.tags(.array))
    func `[array] double comma 1`() throws {
        try invalidate(pathComponents: ["array", "double-comma-1"])
    }

    @Test(.tags(.array))
    func `[array] double comma 2`() throws {
        try invalidate(pathComponents: ["array", "double-comma-2"])
    }

    @Test(.tags(.array))
    func `[array] extend defined aot`() throws {
        try invalidate(pathComponents: ["array", "extend-defined-aot"])
    }

    @Test(.tags(.array))
    func `[array] extending table`() throws {
        try invalidate(pathComponents: ["array", "extending-table"])
    }

    @Test(.tags(.array))
    func `[array] missing separator 01`() throws {
        try invalidate(pathComponents: ["array", "missing-separator-01"])
    }

    @Test(.tags(.array))
    func `[array] missing separator 02`() throws {
        try invalidate(pathComponents: ["array", "missing-separator-02"])
    }

    @Test(.tags(.array))
    func `[array] no close 01`() throws {
        try invalidate(pathComponents: ["array", "no-close-01"])
    }

    @Test(.tags(.array))
    func `[array] no close 02`() throws {
        try invalidate(pathComponents: ["array", "no-close-02"])
    }

    @Test(.tags(.array))
    func `[array] no close 03`() throws {
        try invalidate(pathComponents: ["array", "no-close-03"])
    }

    @Test(.tags(.array))
    func `[array] no close 04`() throws {
        try invalidate(pathComponents: ["array", "no-close-04"])
    }

    @Test(.tags(.array))
    func `[array] no close 05`() throws {
        try invalidate(pathComponents: ["array", "no-close-05"])
    }

    @Test(.tags(.array))
    func `[array] no close 06`() throws {
        try invalidate(pathComponents: ["array", "no-close-06"])
    }

    @Test(.tags(.array))
    func `[array] no close 07`() throws {
        try invalidate(pathComponents: ["array", "no-close-07"])
    }

    @Test(.tags(.array))
    func `[array] no close 08`() throws {
        try invalidate(pathComponents: ["array", "no-close-08"])
    }

    @Test(.tags(.array))
    func `[array] no close 1`() throws {
        try invalidate(pathComponents: ["array", "no-close-1"])
    }

    @Test(.tags(.array))
    func `[array] no close 2`() throws {
        try invalidate(pathComponents: ["array", "no-close-2"])
    }

    @Test(.tags(.array))
    func `[array] no close 3`() throws {
        try invalidate(pathComponents: ["array", "no-close-3"])
    }

    @Test(.tags(.array))
    func `[array] no close 4`() throws {
        try invalidate(pathComponents: ["array", "no-close-4"])
    }

    @Test(.tags(.array))
    func `[array] no close 5`() throws {
        try invalidate(pathComponents: ["array", "no-close-5"])
    }

    @Test(.tags(.array))
    func `[array] no close 6`() throws {
        try invalidate(pathComponents: ["array", "no-close-6"])
    }

    @Test(.tags(.array))
    func `[array] no close 7`() throws {
        try invalidate(pathComponents: ["array", "no-close-7"])
    }

    @Test(.tags(.array))
    func `[array] no close 8`() throws {
        try invalidate(pathComponents: ["array", "no-close-8"])
    }

    @Test(.tags(.array))
    func `[array] no close table 01`() throws {
        try invalidate(pathComponents: ["array", "no-close-table-01"])
    }

    @Test(.tags(.array))
    func `[array] no close table 02`() throws {
        try invalidate(pathComponents: ["array", "no-close-table-02"])
    }

    @Test(.tags(.array))
    func `[array] no comma 01`() throws {
        try invalidate(pathComponents: ["array", "no-comma-01"])
    }

    @Test(.tags(.array))
    func `[array] no comma 02`() throws {
        try invalidate(pathComponents: ["array", "no-comma-02"])
    }

    @Test(.tags(.array))
    func `[array] no comma 03`() throws {
        try invalidate(pathComponents: ["array", "no-comma-03"])
    }

    @Test(.tags(.array))
    func `[array] no comma 1`() throws {
        try invalidate(pathComponents: ["array", "no-comma-1"])
    }

    @Test(.tags(.array))
    func `[array] no comma 2`() throws {
        try invalidate(pathComponents: ["array", "no-comma-2"])
    }

    @Test(.tags(.array))
    func `[array] no comma 3`() throws {
        try invalidate(pathComponents: ["array", "no-comma-3"])
    }

    @Test(.tags(.array))
    func `[array] only comma 01`() throws {
        try invalidate(pathComponents: ["array", "only-comma-01"])
    }

    @Test(.tags(.array))
    func `[array] only comma 02`() throws {
        try invalidate(pathComponents: ["array", "only-comma-02"])
    }

    @Test(.tags(.array))
    func `[array] only comma 1`() throws {
        try invalidate(pathComponents: ["array", "only-comma-1"])
    }

    @Test(.tags(.array))
    func `[array] only comma 2`() throws {
        try invalidate(pathComponents: ["array", "only-comma-2"])
    }

    @Test(.tags(.array))
    func `[array] tables 01`() throws {
        try invalidate(pathComponents: ["array", "tables-01"])
    }

    @Test(.tags(.array))
    func `[array] tables 02`() throws {
        try invalidate(pathComponents: ["array", "tables-02"])
    }

    @Test(.tags(.array))
    func `[array] text after array entries`() throws {
        try invalidate(pathComponents: ["array", "text-after-array-entries"])
    }

    @Test(.tags(.array))
    func `[array] text before array separator`() throws {
        try invalidate(pathComponents: ["array", "text-before-array-separator"])
    }

    @Test(.tags(.array))
    func `[array] text in array`() throws {
        try invalidate(pathComponents: ["array", "text-in-array"])
    }

    @Test(.tags(.bool))
    func `[bool] almost false`() throws {
        try invalidate(pathComponents: ["bool", "almost-false"])
    }

    @Test(.tags(.bool))
    func `[bool] almost false with extra`() throws {
        try invalidate(pathComponents: ["bool", "almost-false-with-extra"])
    }

    @Test(.tags(.bool))
    func `[bool] almost true`() throws {
        try invalidate(pathComponents: ["bool", "almost-true"])
    }

    @Test(.tags(.bool))
    func `[bool] almost true with extra`() throws {
        try invalidate(pathComponents: ["bool", "almost-true-with-extra"])
    }

    @Test(.tags(.bool))
    func `[bool] capitalized false`() throws {
        try invalidate(pathComponents: ["bool", "capitalized-false"])
    }

    @Test(.tags(.bool))
    func `[bool] capitalized true`() throws {
        try invalidate(pathComponents: ["bool", "capitalized-true"])
    }

    @Test(.tags(.bool))
    func `[bool] just f`() throws {
        try invalidate(pathComponents: ["bool", "just-f"])
    }

    @Test(.tags(.bool))
    func `[bool] just t`() throws {
        try invalidate(pathComponents: ["bool", "just-t"])
    }

    @Test(.tags(.bool))
    func `[bool] mixed case`() throws {
        try invalidate(pathComponents: ["bool", "mixed-case"])
    }

    @Test(.tags(.bool))
    func `[bool] mixed case false`() throws {
        try invalidate(pathComponents: ["bool", "mixed-case-false"])
    }

    @Test(.tags(.bool))
    func `[bool] mixed case true`() throws {
        try invalidate(pathComponents: ["bool", "mixed-case-true"])
    }

    @Test(.tags(.bool))
    func `[bool] starting same false`() throws {
        try invalidate(pathComponents: ["bool", "starting-same-false"])
    }

    @Test(.tags(.bool))
    func `[bool] starting same true`() throws {
        try invalidate(pathComponents: ["bool", "starting-same-true"])
    }

    @Test(.tags(.bool))
    func `[bool] wrong case false`() throws {
        try invalidate(pathComponents: ["bool", "wrong-case-false"])
    }

    @Test(.tags(.bool))
    func `[bool] wrong case true`() throws {
        try invalidate(pathComponents: ["bool", "wrong-case-true"])
    }

    @Test(.tags(.control))
    func `[control] bare cr`() throws {
        try invalidate(pathComponents: ["control", "bare-cr"])
    }

    @Test(.tags(.control))
    func `[control] bare formfeed`() throws {
        try invalidate(pathComponents: ["control", "bare-formfeed"])
    }

    @Test(.tags(.control))
    func `[control] bare null`() throws {
        try invalidate(pathComponents: ["control", "bare-null"])
    }

    @Test(.tags(.control))
    func `[control] bare vertical tab`() throws {
        try invalidate(pathComponents: ["control", "bare-vertical-tab"])
    }

    @Test(.tags(.control))
    func `[control] comment cr`() throws {
        try invalidate(pathComponents: ["control", "comment-cr"])
    }

    @Test(.tags(.control))
    func `[control] comment del`() throws {
        try invalidate(pathComponents: ["control", "comment-del"])
    }

    @Test(.tags(.control))
    func `[control] comment ff`() throws {
        try invalidate(pathComponents: ["control", "comment-ff"])
    }

    @Test(.tags(.control))
    func `[control] comment lf`() throws {
        try invalidate(pathComponents: ["control", "comment-lf"])
    }

    @Test(.tags(.control))
    func `[control] comment null`() throws {
        try invalidate(pathComponents: ["control", "comment-null"])
    }

    @Test(.tags(.control))
    func `[control] comment us`() throws {
        try invalidate(pathComponents: ["control", "comment-us"])
    }

    @Test(.tags(.control))
    func `[control] multi cr`() throws {
        try invalidate(pathComponents: ["control", "multi-cr"])
    }

    @Test(.tags(.control))
    func `[control] multi del`() throws {
        try invalidate(pathComponents: ["control", "multi-del"])
    }

    @Test(.tags(.control))
    func `[control] multi lf`() throws {
        try invalidate(pathComponents: ["control", "multi-lf"])
    }

    @Test(.tags(.control))
    func `[control] multi null`() throws {
        try invalidate(pathComponents: ["control", "multi-null"])
    }

    @Test(.tags(.control))
    func `[control] multi us`() throws {
        try invalidate(pathComponents: ["control", "multi-us"])
    }

    @Test(.tags(.control))
    func `[control] only ff`() throws {
        try invalidate(pathComponents: ["control", "only-ff"])
    }

    @Test(.tags(.control))
    func `[control] only null`() throws {
        try invalidate(pathComponents: ["control", "only-null"])
    }

    @Test(.tags(.control))
    func `[control] only vt`() throws {
        try invalidate(pathComponents: ["control", "only-vt"])
    }

    @Test(.tags(.control))
    func `[control] rawmulti cr`() throws {
        try invalidate(pathComponents: ["control", "rawmulti-cr"])
    }

    @Test(.tags(.control))
    func `[control] rawmulti del`() throws {
        try invalidate(pathComponents: ["control", "rawmulti-del"])
    }

    @Test(.tags(.control))
    func `[control] rawmulti lf`() throws {
        try invalidate(pathComponents: ["control", "rawmulti-lf"])
    }

    @Test(.tags(.control))
    func `[control] rawmulti null`() throws {
        try invalidate(pathComponents: ["control", "rawmulti-null"])
    }

    @Test(.tags(.control))
    func `[control] rawmulti us`() throws {
        try invalidate(pathComponents: ["control", "rawmulti-us"])
    }

    @Test(.tags(.control))
    func `[control] rawstring cr`() throws {
        try invalidate(pathComponents: ["control", "rawstring-cr"])
    }

    @Test(.tags(.control))
    func `[control] rawstring del`() throws {
        try invalidate(pathComponents: ["control", "rawstring-del"])
    }

    @Test(.tags(.control))
    func `[control] rawstring lf`() throws {
        try invalidate(pathComponents: ["control", "rawstring-lf"])
    }

    @Test(.tags(.control))
    func `[control] rawstring null`() throws {
        try invalidate(pathComponents: ["control", "rawstring-null"])
    }

    @Test(.tags(.control))
    func `[control] rawstring us`() throws {
        try invalidate(pathComponents: ["control", "rawstring-us"])
    }

    @Test(.tags(.control))
    func `[control] string bs`() throws {
        try invalidate(pathComponents: ["control", "string-bs"])
    }

    @Test(.tags(.control))
    func `[control] string cr`() throws {
        try invalidate(pathComponents: ["control", "string-cr"])
    }

    @Test(.tags(.control))
    func `[control] string del`() throws {
        try invalidate(pathComponents: ["control", "string-del"])
    }

    @Test(.tags(.control))
    func `[control] string lf`() throws {
        try invalidate(pathComponents: ["control", "string-lf"])
    }

    @Test(.tags(.control))
    func `[control] string null`() throws {
        try invalidate(pathComponents: ["control", "string-null"])
    }

    @Test(.tags(.control))
    func `[control] string us`() throws {
        try invalidate(pathComponents: ["control", "string-us"])
    }

    @Test(.tags(.datetime))
    func `[datetime] day zero`() throws {
        try invalidate(pathComponents: ["datetime", "day-zero"])
    }

    @Test(.tags(.datetime))
    func `[datetime] feb 29`() throws {
        try invalidate(pathComponents: ["datetime", "feb-29"])
    }

    @Test(.tags(.datetime))
    func `[datetime] feb 30`() throws {
        try invalidate(pathComponents: ["datetime", "feb-30"])
    }

    @Test(.tags(.datetime))
    func `[datetime] hour over`() throws {
        try invalidate(pathComponents: ["datetime", "hour-over"])
    }

    @Test(.tags(.datetime))
    func `[datetime] mday over`() throws {
        try invalidate(pathComponents: ["datetime", "mday-over"])
    }

    @Test(.tags(.datetime))
    func `[datetime] mday under`() throws {
        try invalidate(pathComponents: ["datetime", "mday-under"])
    }

    @Test(.tags(.datetime))
    func `[datetime] minute over`() throws {
        try invalidate(pathComponents: ["datetime", "minute-over"])
    }

    @Test(.tags(.datetime))
    func `[datetime] month over`() throws {
        try invalidate(pathComponents: ["datetime", "month-over"])
    }

    @Test(.tags(.datetime))
    func `[datetime] month under`() throws {
        try invalidate(pathComponents: ["datetime", "month-under"])
    }

    @Test(.tags(.datetime))
    func `[datetime] no date time sep`() throws {
        try invalidate(pathComponents: ["datetime", "no-date-time-sep"])
    }

    @Test(.tags(.datetime))
    func `[datetime] no leads`() throws {
        try invalidate(pathComponents: ["datetime", "no-leads"])
    }

    @Test(.tags(.datetime))
    func `[datetime] no leads month`() throws {
        try invalidate(pathComponents: ["datetime", "no-leads-month"])
    }

    @Test(.tags(.datetime))
    func `[datetime] no leads with milli`() throws {
        try invalidate(pathComponents: ["datetime", "no-leads-with-milli"])
    }

    @Test(.tags(.datetime))
    func `[datetime] no secs`() throws {
        try invalidate(pathComponents: ["datetime", "no-secs"])
    }

    @Test(.tags(.datetime))
    func `[datetime] no t`() throws {
        try invalidate(pathComponents: ["datetime", "no-t"])
    }

    @Test(.tags(.datetime))
    func `[datetime] no year month sep`() throws {
        try invalidate(pathComponents: ["datetime", "no-year-month-sep"])
    }

    @Test(.tags(.datetime))
    func `[datetime] offset minus minute 1digit`() throws {
        try invalidate(pathComponents: ["datetime", "offset-minus-minute-1digit"])
    }

    @Test(.tags(.datetime))
    func `[datetime] offset minus no hour minute`() throws {
        try invalidate(pathComponents: ["datetime", "offset-minus-no-hour-minute"])
    }

    @Test(.tags(.datetime))
    func `[datetime] offset minus no hour minute sep`() throws {
        try invalidate(pathComponents: ["datetime", "offset-minus-no-hour-minute-sep"])
    }

    @Test(.tags(.datetime))
    func `[datetime] offset minus no minute`() throws {
        try invalidate(pathComponents: ["datetime", "offset-minus-no-minute"])
    }

    @Test(.tags(.datetime))
    func `[datetime] offset overflow hour`() throws {
        try invalidate(pathComponents: ["datetime", "offset-overflow-hour"])
    }

    @Test(.tags(.datetime))
    func `[datetime] offset overflow minute`() throws {
        try invalidate(pathComponents: ["datetime", "offset-overflow-minute"])
    }

    @Test(.tags(.datetime))
    func `[datetime] offset plus minute 1digit`() throws {
        try invalidate(pathComponents: ["datetime", "offset-plus-minute-1digit"])
    }

    @Test(.tags(.datetime))
    func `[datetime] offset plus no hour minute`() throws {
        try invalidate(pathComponents: ["datetime", "offset-plus-no-hour-minute"])
    }

    @Test(.tags(.datetime))
    func `[datetime] offset plus no hour minute sep`() throws {
        try invalidate(pathComponents: ["datetime", "offset-plus-no-hour-minute-sep"])
    }

    @Test(.tags(.datetime))
    func `[datetime] offset plus no minute`() throws {
        try invalidate(pathComponents: ["datetime", "offset-plus-no-minute"])
    }

    @Test(.tags(.datetime))
    func `[datetime] only T`() throws {
        try invalidate(pathComponents: ["datetime", "only-T"])
    }

    @Test(.tags(.datetime))
    func `[datetime] only TZ`() throws {
        try invalidate(pathComponents: ["datetime", "only-TZ"])
    }

    @Test(.tags(.datetime))
    func `[datetime] only Tdot`() throws {
        try invalidate(pathComponents: ["datetime", "only-Tdot"])
    }

    @Test(.tags(.datetime))
    func `[datetime] second over`() throws {
        try invalidate(pathComponents: ["datetime", "second-over"])
    }

    @Test(.tags(.datetime))
    func `[datetime] second trailing dot`() throws {
        try invalidate(pathComponents: ["datetime", "second-trailing-dot"])
    }

    @Test(.tags(.datetime))
    func `[datetime] second trailing dotz`() throws {
        try invalidate(pathComponents: ["datetime", "second-trailing-dotz"])
    }

    @Test(.tags(.datetime))
    func `[datetime] time no leads`() throws {
        try invalidate(pathComponents: ["datetime", "time-no-leads"])
    }

    @Test(.tags(.datetime))
    func `[datetime] trailing x`() throws {
        try invalidate(pathComponents: ["datetime", "trailing-x"])
    }

    @Test(.tags(.datetime))
    func `[datetime] y10k`() throws {
        try invalidate(pathComponents: ["datetime", "y10k"])
    }

    @Test(.tags(.encoding))
    func `[encoding] bad codepoint`() throws {
        try invalidate(pathComponents: ["encoding", "bad-codepoint"])
    }

    @Test(.tags(.encoding))
    func `[encoding] bad utf8 at end`() throws {
        try invalidate(pathComponents: ["encoding", "bad-utf8-at-end"])
    }

    @Test(.tags(.encoding))
    func `[encoding] bad utf8 in array`() throws {
        try invalidate(pathComponents: ["encoding", "bad-utf8-in-array"])
    }

    @Test(.tags(.encoding))
    func `[encoding] bad utf8 in comment`() throws {
        try invalidate(pathComponents: ["encoding", "bad-utf8-in-comment"])
    }

    @Test(.tags(.encoding))
    func `[encoding] bad utf8 in multiline`() throws {
        try invalidate(pathComponents: ["encoding", "bad-utf8-in-multiline"])
    }

    @Test(.tags(.encoding))
    func `[encoding] bad utf8 in multiline literal`() throws {
        try invalidate(pathComponents: ["encoding", "bad-utf8-in-multiline-literal"])
    }

    @Test(.tags(.encoding))
    func `[encoding] bad utf8 in string`() throws {
        try invalidate(pathComponents: ["encoding", "bad-utf8-in-string"])
    }

    @Test(.tags(.encoding))
    func `[encoding] bad utf8 in string literal`() throws {
        try invalidate(pathComponents: ["encoding", "bad-utf8-in-string-literal"])
    }

    @Test(.tags(.encoding))
    func `[encoding] bom not at start 01`() throws {
        try invalidate(pathComponents: ["encoding", "bom-not-at-start-01"])
    }

    @Test(.tags(.encoding))
    func `[encoding] bom not at start 02`() throws {
        try invalidate(pathComponents: ["encoding", "bom-not-at-start-02"])
    }

    @Test(.tags(.encoding))
    func `[encoding] ideographic space`() throws {
        try invalidate(pathComponents: ["encoding", "ideographic-space"])
    }

    @Test(.tags(.encoding))
    func `[encoding] utf16 bom`() throws {
        try invalidate(pathComponents: ["encoding", "utf16-bom"])
    }

    @Test(.tags(.encoding))
    func `[encoding] utf16 comment`() throws {
        try invalidate(pathComponents: ["encoding", "utf16-comment"])
    }

    @Test(.tags(.encoding))
    func `[encoding] utf16 key`() throws {
        try invalidate(pathComponents: ["encoding", "utf16-key"])
    }

    @Test(.tags(.float))
    func `[float] double dot 01`() throws {
        try invalidate(pathComponents: ["float", "double-dot-01"])
    }

    @Test(.tags(.float))
    func `[float] double dot 02`() throws {
        try invalidate(pathComponents: ["float", "double-dot-02"])
    }

    @Test(.tags(.float))
    func `[float] double point 1`() throws {
        try invalidate(pathComponents: ["float", "double-point-1"])
    }

    @Test(.tags(.float))
    func `[float] double point 2`() throws {
        try invalidate(pathComponents: ["float", "double-point-2"])
    }

    @Test(.tags(.float))
    func `[float] exp dot 01`() throws {
        try invalidate(pathComponents: ["float", "exp-dot-01"])
    }

    @Test(.tags(.float))
    func `[float] exp dot 02`() throws {
        try invalidate(pathComponents: ["float", "exp-dot-02"])
    }

    @Test(.tags(.float))
    func `[float] exp dot 03`() throws {
        try invalidate(pathComponents: ["float", "exp-dot-03"])
    }

    @Test(.tags(.float))
    func `[float] exp double e 01`() throws {
        try invalidate(pathComponents: ["float", "exp-double-e-01"])
    }

    @Test(.tags(.float))
    func `[float] exp double e 02`() throws {
        try invalidate(pathComponents: ["float", "exp-double-e-02"])
    }

    @Test(.tags(.float))
    func `[float] exp double e 1`() throws {
        try invalidate(pathComponents: ["float", "exp-double-e-1"])
    }

    @Test(.tags(.float))
    func `[float] exp double e 2`() throws {
        try invalidate(pathComponents: ["float", "exp-double-e-2"])
    }

    @Test(.tags(.float))
    func `[float] exp double us`() throws {
        try invalidate(pathComponents: ["float", "exp-double-us"])
    }

    @Test(.tags(.float))
    func `[float] exp leading us`() throws {
        try invalidate(pathComponents: ["float", "exp-leading-us"])
    }

    @Test(.tags(.float))
    func `[float] exp point 1`() throws {
        try invalidate(pathComponents: ["float", "exp-point-1"])
    }

    @Test(.tags(.float))
    func `[float] exp point 2`() throws {
        try invalidate(pathComponents: ["float", "exp-point-2"])
    }

    @Test(.tags(.float))
    func `[float] exp point 3`() throws {
        try invalidate(pathComponents: ["float", "exp-point-3"])
    }

    @Test(.tags(.float))
    func `[float] exp trailing us`() throws {
        try invalidate(pathComponents: ["float", "exp-trailing-us"])
    }

    @Test(.tags(.float))
    func `[float] exp trailing us 01`() throws {
        try invalidate(pathComponents: ["float", "exp-trailing-us-01"])
    }

    @Test(.tags(.float))
    func `[float] exp trailing us 02`() throws {
        try invalidate(pathComponents: ["float", "exp-trailing-us-02"])
    }

    @Test(.tags(.float))
    func `[float] exp trailing us 1`() throws {
        try invalidate(pathComponents: ["float", "exp-trailing-us-1"])
    }

    @Test(.tags(.float))
    func `[float] exp trailing us 2`() throws {
        try invalidate(pathComponents: ["float", "exp-trailing-us-2"])
    }

    @Test(.tags(.float))
    func `[float] inf capital`() throws {
        try invalidate(pathComponents: ["float", "inf-capital"])
    }

    @Test(.tags(.float))
    func `[float] inf incomplete 01`() throws {
        try invalidate(pathComponents: ["float", "inf-incomplete-01"])
    }

    @Test(.tags(.float))
    func `[float] inf incomplete 02`() throws {
        try invalidate(pathComponents: ["float", "inf-incomplete-02"])
    }

    @Test(.tags(.float))
    func `[float] inf incomplete 03`() throws {
        try invalidate(pathComponents: ["float", "inf-incomplete-03"])
    }

    @Test(.tags(.float))
    func `[float] inf incomplete 1`() throws {
        try invalidate(pathComponents: ["float", "inf-incomplete-1"])
    }

    @Test(.tags(.float))
    func `[float] inf incomplete 2`() throws {
        try invalidate(pathComponents: ["float", "inf-incomplete-2"])
    }

    @Test(.tags(.float))
    func `[float] inf incomplete 3`() throws {
        try invalidate(pathComponents: ["float", "inf-incomplete-3"])
    }

    @Test(.tags(.float))
    func `[float] inf underscore`() throws {
        try invalidate(pathComponents: ["float", "inf_underscore"])
    }

    @Test(.tags(.float))
    func `[float] leading dot`() throws {
        try invalidate(pathComponents: ["float", "leading-dot"])
    }

    @Test(.tags(.float))
    func `[float] leading dot neg`() throws {
        try invalidate(pathComponents: ["float", "leading-dot-neg"])
    }

    @Test(.tags(.float))
    func `[float] leading dot plus`() throws {
        try invalidate(pathComponents: ["float", "leading-dot-plus"])
    }

    @Test(.tags(.float))
    func `[float] leading point`() throws {
        try invalidate(pathComponents: ["float", "leading-point"])
    }

    @Test(.tags(.float))
    func `[float] leading point neg`() throws {
        try invalidate(pathComponents: ["float", "leading-point-neg"])
    }

    @Test(.tags(.float))
    func `[float] leading point plus`() throws {
        try invalidate(pathComponents: ["float", "leading-point-plus"])
    }

    @Test(.tags(.float))
    func `[float] leading us`() throws {
        try invalidate(pathComponents: ["float", "leading-us"])
    }

    @Test(.tags(.float))
    func `[float] leading zero`() throws {
        try invalidate(pathComponents: ["float", "leading-zero"])
    }

    @Test(.tags(.float))
    func `[float] leading zero neg`() throws {
        try invalidate(pathComponents: ["float", "leading-zero-neg"])
    }

    @Test(.tags(.float))
    func `[float] leading zero plus`() throws {
        try invalidate(pathComponents: ["float", "leading-zero-plus"])
    }

    @Test(.tags(.float))
    func `[float] nan capital`() throws {
        try invalidate(pathComponents: ["float", "nan-capital"])
    }

    @Test(.tags(.float))
    func `[float] nan incomplete 01`() throws {
        try invalidate(pathComponents: ["float", "nan-incomplete-01"])
    }

    @Test(.tags(.float))
    func `[float] nan incomplete 02`() throws {
        try invalidate(pathComponents: ["float", "nan-incomplete-02"])
    }

    @Test(.tags(.float))
    func `[float] nan incomplete 03`() throws {
        try invalidate(pathComponents: ["float", "nan-incomplete-03"])
    }

    @Test(.tags(.float))
    func `[float] nan incomplete 1`() throws {
        try invalidate(pathComponents: ["float", "nan-incomplete-1"])
    }

    @Test(.tags(.float))
    func `[float] nan incomplete 2`() throws {
        try invalidate(pathComponents: ["float", "nan-incomplete-2"])
    }

    @Test(.tags(.float))
    func `[float] nan incomplete 3`() throws {
        try invalidate(pathComponents: ["float", "nan-incomplete-3"])
    }

    @Test(.tags(.float))
    func `[float] nan underscore`() throws {
        try invalidate(pathComponents: ["float", "nan_underscore"])
    }

    @Test(.tags(.float))
    func `[float] trailing dot 01`() throws {
        try invalidate(pathComponents: ["float", "trailing-dot-01"])
    }

    @Test(.tags(.float))
    func `[float] trailing dot 02`() throws {
        try invalidate(pathComponents: ["float", "trailing-dot-02"])
    }

    @Test(.tags(.float))
    func `[float] trailing dot min`() throws {
        try invalidate(pathComponents: ["float", "trailing-dot-min"])
    }

    @Test(.tags(.float))
    func `[float] trailing dot plus`() throws {
        try invalidate(pathComponents: ["float", "trailing-dot-plus"])
    }

    @Test(.tags(.float))
    func `[float] trailing exp`() throws {
        try invalidate(pathComponents: ["float", "trailing-exp"])
    }

    @Test(.tags(.float))
    func `[float] trailing exp minus`() throws {
        try invalidate(pathComponents: ["float", "trailing-exp-minus"])
    }

    @Test(.tags(.float))
    func `[float] trailing exp plus`() throws {
        try invalidate(pathComponents: ["float", "trailing-exp-plus"])
    }

    @Test(.tags(.float))
    func `[float] trailing exp point`() throws {
        try invalidate(pathComponents: ["float", "trailing-exp-point"])
    }

    @Test(.tags(.float))
    func `[float] trailing point`() throws {
        try invalidate(pathComponents: ["float", "trailing-point"])
    }

    @Test(.tags(.float))
    func `[float] trailing point min`() throws {
        try invalidate(pathComponents: ["float", "trailing-point-min"])
    }

    @Test(.tags(.float))
    func `[float] trailing point plus`() throws {
        try invalidate(pathComponents: ["float", "trailing-point-plus"])
    }

    @Test(.tags(.float))
    func `[float] trailing us`() throws {
        try invalidate(pathComponents: ["float", "trailing-us"])
    }

    @Test(.tags(.float))
    func `[float] trailing us exp 01`() throws {
        try invalidate(pathComponents: ["float", "trailing-us-exp-01"])
    }

    @Test(.tags(.float))
    func `[float] trailing us exp 02`() throws {
        try invalidate(pathComponents: ["float", "trailing-us-exp-02"])
    }

    @Test(.tags(.float))
    func `[float] us after dot`() throws {
        try invalidate(pathComponents: ["float", "us-after-dot"])
    }

    @Test(.tags(.float))
    func `[float] us after point`() throws {
        try invalidate(pathComponents: ["float", "us-after-point"])
    }

    @Test(.tags(.float))
    func `[float] us before dot`() throws {
        try invalidate(pathComponents: ["float", "us-before-dot"])
    }

    @Test(.tags(.float))
    func `[float] us before point`() throws {
        try invalidate(pathComponents: ["float", "us-before-point"])
    }

    @Test(.tags(.inline_table))
    func `[inline-table] bad key syntax`() throws {
        try invalidate(pathComponents: ["inline-table", "bad-key-syntax"])
    }

    @Test(.tags(.inline_table))
    func `[inline-table] double comma`() throws {
        try invalidate(pathComponents: ["inline-table", "double-comma"])
    }

    @Test(.tags(.inline_table))
    func `[inline-table] duplicate key 01`() throws {
        try invalidate(pathComponents: ["inline-table", "duplicate-key-01"])
    }

    @Test(.tags(.inline_table))
    func `[inline-table] duplicate key 02`() throws {
        try invalidate(pathComponents: ["inline-table", "duplicate-key-02"])
    }

    @Test(.tags(.inline_table))
    func `[inline-table] duplicate key 03`() throws {
        try invalidate(pathComponents: ["inline-table", "duplicate-key-03"])
    }

    @Test(.tags(.inline_table))
    func `[inline-table] duplicate key 04`() throws {
        try invalidate(pathComponents: ["inline-table", "duplicate-key-04"])
    }

    @Test(.tags(.inline_table))
    func `[inline-table] empty 01`() throws {
        try invalidate(pathComponents: ["inline-table", "empty-01"])
    }

    @Test(.tags(.inline_table))
    func `[inline-table] empty 02`() throws {
        try invalidate(pathComponents: ["inline-table", "empty-02"])
    }

    @Test(.tags(.inline_table))
    func `[inline-table] empty 03`() throws {
        try invalidate(pathComponents: ["inline-table", "empty-03"])
    }

    @Test(.tags(.inline_table))
    func `[inline-table] linebreak 01`() throws {
        try invalidate(pathComponents: ["inline-table", "linebreak-01"])
    }

    @Test(.tags(.inline_table))
    func `[inline-table] linebreak 02`() throws {
        try invalidate(pathComponents: ["inline-table", "linebreak-02"])
    }

    @Test(.tags(.inline_table))
    func `[inline-table] linebreak 03`() throws {
        try invalidate(pathComponents: ["inline-table", "linebreak-03"])
    }

    @Test(.tags(.inline_table))
    func `[inline-table] linebreak 04`() throws {
        try invalidate(pathComponents: ["inline-table", "linebreak-04"])
    }

    @Test(.tags(.inline_table))
    func `[inline-table] no close 01`() throws {
        try invalidate(pathComponents: ["inline-table", "no-close-01"])
    }

    @Test(.tags(.inline_table))
    func `[inline-table] no close 02`() throws {
        try invalidate(pathComponents: ["inline-table", "no-close-02"])
    }

    @Test(.tags(.inline_table))
    func `[inline-table] no comma 01`() throws {
        try invalidate(pathComponents: ["inline-table", "no-comma-01"])
    }

    @Test(.tags(.inline_table))
    func `[inline-table] no comma 02`() throws {
        try invalidate(pathComponents: ["inline-table", "no-comma-02"])
    }

    @Test(.tags(.inline_table))
    func `[inline-table] overwrite 01`() throws {
        try invalidate(pathComponents: ["inline-table", "overwrite-01"])
    }

    @Test(.tags(.inline_table))
    func `[inline-table] overwrite 02`() throws {
        try invalidate(pathComponents: ["inline-table", "overwrite-02"])
    }

    @Test(.tags(.inline_table))
    func `[inline-table] overwrite 03`() throws {
        try invalidate(pathComponents: ["inline-table", "overwrite-03"])
    }

    @Test(.tags(.inline_table))
    func `[inline-table] overwrite 04`() throws {
        try invalidate(pathComponents: ["inline-table", "overwrite-04"])
    }

    @Test(.tags(.inline_table))
    func `[inline-table] overwrite 05`() throws {
        try invalidate(pathComponents: ["inline-table", "overwrite-05"])
    }

    @Test(.tags(.inline_table))
    func `[inline-table] overwrite 06`() throws {
        try invalidate(pathComponents: ["inline-table", "overwrite-06"])
    }

    @Test(.tags(.inline_table))
    func `[inline-table] overwrite 07`() throws {
        try invalidate(pathComponents: ["inline-table", "overwrite-07"])
    }

    @Test(.tags(.inline_table))
    func `[inline-table] overwrite 08`() throws {
        try invalidate(pathComponents: ["inline-table", "overwrite-08"])
    }

    @Test(.tags(.inline_table))
    func `[inline-table] overwrite 09`() throws {
        try invalidate(pathComponents: ["inline-table", "overwrite-09"])
    }

    @Test(.tags(.inline_table))
    func `[inline-table] overwrite 10`() throws {
        try invalidate(pathComponents: ["inline-table", "overwrite-10"])
    }

    @Test(.tags(.inline_table))
    func `[inline-table] trailing comma`() throws {
        try invalidate(pathComponents: ["inline-table", "trailing-comma"])
    }

    @Test(.tags(.integer))
    func `[integer] capital bin`() throws {
        try invalidate(pathComponents: ["integer", "capital-bin"])
    }

    @Test(.tags(.integer))
    func `[integer] capital hex`() throws {
        try invalidate(pathComponents: ["integer", "capital-hex"])
    }

    @Test(.tags(.integer))
    func `[integer] capital oct`() throws {
        try invalidate(pathComponents: ["integer", "capital-oct"])
    }

    @Test(.tags(.integer))
    func `[integer] double sign nex`() throws {
        try invalidate(pathComponents: ["integer", "double-sign-nex"])
    }

    @Test(.tags(.integer))
    func `[integer] double sign plus`() throws {
        try invalidate(pathComponents: ["integer", "double-sign-plus"])
    }

    @Test(.tags(.integer))
    func `[integer] double us`() throws {
        try invalidate(pathComponents: ["integer", "double-us"])
    }

    @Test(.tags(.integer))
    func `[integer] incomplete bin`() throws {
        try invalidate(pathComponents: ["integer", "incomplete-bin"])
    }

    @Test(.tags(.integer))
    func `[integer] incomplete hex`() throws {
        try invalidate(pathComponents: ["integer", "incomplete-hex"])
    }

    @Test(.tags(.integer))
    func `[integer] incomplete oct`() throws {
        try invalidate(pathComponents: ["integer", "incomplete-oct"])
    }

    @Test(.tags(.integer))
    func `[integer] invalid bin`() throws {
        try invalidate(pathComponents: ["integer", "invalid-bin"])
    }

    @Test(.tags(.integer))
    func `[integer] invalid hex 01`() throws {
        try invalidate(pathComponents: ["integer", "invalid-hex-01"])
    }

    @Test(.tags(.integer))
    func `[integer] invalid hex 02`() throws {
        try invalidate(pathComponents: ["integer", "invalid-hex-02"])
    }

    @Test(.tags(.integer))
    func `[integer] invalid hex 03`() throws {
        try invalidate(pathComponents: ["integer", "invalid-hex-03"])
    }

    @Test(.tags(.integer))
    func `[integer] invalid hex 1`() throws {
        try invalidate(pathComponents: ["integer", "invalid-hex-1"])
    }

    @Test(.tags(.integer))
    func `[integer] invalid hex 2`() throws {
        try invalidate(pathComponents: ["integer", "invalid-hex-2"])
    }

    @Test(.tags(.integer))
    func `[integer] invalid oct`() throws {
        try invalidate(pathComponents: ["integer", "invalid-oct"])
    }

    @Test(.tags(.integer))
    func `[integer] leading us`() throws {
        try invalidate(pathComponents: ["integer", "leading-us"])
    }

    @Test(.tags(.integer))
    func `[integer] leading us bin`() throws {
        try invalidate(pathComponents: ["integer", "leading-us-bin"])
    }

    @Test(.tags(.integer))
    func `[integer] leading us hex`() throws {
        try invalidate(pathComponents: ["integer", "leading-us-hex"])
    }

    @Test(.tags(.integer))
    func `[integer] leading us oct`() throws {
        try invalidate(pathComponents: ["integer", "leading-us-oct"])
    }

    @Test(.tags(.integer))
    func `[integer] leading zero 01`() throws {
        try invalidate(pathComponents: ["integer", "leading-zero-01"])
    }

    @Test(.tags(.integer))
    func `[integer] leading zero 02`() throws {
        try invalidate(pathComponents: ["integer", "leading-zero-02"])
    }

    @Test(.tags(.integer))
    func `[integer] leading zero 03`() throws {
        try invalidate(pathComponents: ["integer", "leading-zero-03"])
    }

    @Test(.tags(.integer))
    func `[integer] leading zero 1`() throws {
        try invalidate(pathComponents: ["integer", "leading-zero-1"])
    }

    @Test(.tags(.integer))
    func `[integer] leading zero 2`() throws {
        try invalidate(pathComponents: ["integer", "leading-zero-2"])
    }

    @Test(.tags(.integer))
    func `[integer] leading zero 3`() throws {
        try invalidate(pathComponents: ["integer", "leading-zero-3"])
    }

    @Test(.tags(.integer))
    func `[integer] leading zero sign 01`() throws {
        try invalidate(pathComponents: ["integer", "leading-zero-sign-01"])
    }

    @Test(.tags(.integer))
    func `[integer] leading zero sign 02`() throws {
        try invalidate(pathComponents: ["integer", "leading-zero-sign-02"])
    }

    @Test(.tags(.integer))
    func `[integer] leading zero sign 03`() throws {
        try invalidate(pathComponents: ["integer", "leading-zero-sign-03"])
    }

    @Test(.tags(.integer))
    func `[integer] leading zero sign 1`() throws {
        try invalidate(pathComponents: ["integer", "leading-zero-sign-1"])
    }

    @Test(.tags(.integer))
    func `[integer] leading zero sign 2`() throws {
        try invalidate(pathComponents: ["integer", "leading-zero-sign-2"])
    }

    @Test(.tags(.integer))
    func `[integer] leading zero sign 3`() throws {
        try invalidate(pathComponents: ["integer", "leading-zero-sign-3"])
    }

    @Test(.tags(.integer))
    func `[integer] negative bin`() throws {
        try invalidate(pathComponents: ["integer", "negative-bin"])
    }

    @Test(.tags(.integer))
    func `[integer] negative hex`() throws {
        try invalidate(pathComponents: ["integer", "negative-hex"])
    }

    @Test(.tags(.integer))
    func `[integer] negative oct`() throws {
        try invalidate(pathComponents: ["integer", "negative-oct"])
    }

    @Test(.tags(.integer))
    func `[integer] positive bin`() throws {
        try invalidate(pathComponents: ["integer", "positive-bin"])
    }

    @Test(.tags(.integer))
    func `[integer] positive hex`() throws {
        try invalidate(pathComponents: ["integer", "positive-hex"])
    }

    @Test(.tags(.integer))
    func `[integer] positive oct`() throws {
        try invalidate(pathComponents: ["integer", "positive-oct"])
    }

    @Test(.tags(.integer))
    func `[integer] text after integer`() throws {
        try invalidate(pathComponents: ["integer", "text-after-integer"])
    }

    @Test(.tags(.integer))
    func `[integer] trailing us`() throws {
        try invalidate(pathComponents: ["integer", "trailing-us"])
    }

    @Test(.tags(.integer))
    func `[integer] trailing us bin`() throws {
        try invalidate(pathComponents: ["integer", "trailing-us-bin"])
    }

    @Test(.tags(.integer))
    func `[integer] trailing us hex`() throws {
        try invalidate(pathComponents: ["integer", "trailing-us-hex"])
    }

    @Test(.tags(.integer))
    func `[integer] trailing us oct`() throws {
        try invalidate(pathComponents: ["integer", "trailing-us-oct"])
    }

    @Test(.tags(.integer))
    func `[integer] us after bin`() throws {
        try invalidate(pathComponents: ["integer", "us-after-bin"])
    }

    @Test(.tags(.integer))
    func `[integer] us after hex`() throws {
        try invalidate(pathComponents: ["integer", "us-after-hex"])
    }

    @Test(.tags(.integer))
    func `[integer] us after oct`() throws {
        try invalidate(pathComponents: ["integer", "us-after-oct"])
    }

    @Test(.tags(.key))
    func `[key] after array`() throws {
        try invalidate(pathComponents: ["key", "after-array"])
    }

    @Test(.tags(.key))
    func `[key] after table`() throws {
        try invalidate(pathComponents: ["key", "after-table"])
    }

    @Test(.tags(.key))
    func `[key] after value`() throws {
        try invalidate(pathComponents: ["key", "after-value"])
    }

    @Test(.tags(.key))
    func `[key] bare invalid character 01`() throws {
        try invalidate(pathComponents: ["key", "bare-invalid-character-01"])
    }

    @Test(.tags(.key))
    func `[key] bare invalid character 02`() throws {
        try invalidate(pathComponents: ["key", "bare-invalid-character-02"])
    }

    @Test(.tags(.key))
    func `[key] dot`() throws {
        try invalidate(pathComponents: ["key", "dot"])
    }

    @Test(.tags(.key))
    func `[key] dotdot`() throws {
        try invalidate(pathComponents: ["key", "dotdot"])
    }

    @Test(.tags(.key))
    func `[key] dotted redefine table 01`() throws {
        try invalidate(pathComponents: ["key", "dotted-redefine-table-01"])
    }

    @Test(.tags(.key))
    func `[key] dotted redefine table 02`() throws {
        try invalidate(pathComponents: ["key", "dotted-redefine-table-02"])
    }

    @Test(.tags(.key))
    func `[key] duplicate keys 01`() throws {
        try invalidate(pathComponents: ["key", "duplicate-keys-01"])
    }

    @Test(.tags(.key))
    func `[key] duplicate keys 02`() throws {
        try invalidate(pathComponents: ["key", "duplicate-keys-02"])
    }

    @Test(.tags(.key))
    func `[key] duplicate keys 03`() throws {
        try invalidate(pathComponents: ["key", "duplicate-keys-03"])
    }

    @Test(.tags(.key))
    func `[key] duplicate keys 04`() throws {
        try invalidate(pathComponents: ["key", "duplicate-keys-04"])
    }

    @Test(.tags(.key))
    func `[key] duplicate keys 05`() throws {
        try invalidate(pathComponents: ["key", "duplicate-keys-05"])
    }

    @Test(.tags(.key))
    func `[key] duplicate keys 06`() throws {
        try invalidate(pathComponents: ["key", "duplicate-keys-06"])
    }

    @Test(.tags(.key))
    func `[key] duplicate keys 07`() throws {
        try invalidate(pathComponents: ["key", "duplicate-keys-07"])
    }

    @Test(.tags(.key))
    func `[key] empty`() throws {
        try invalidate(pathComponents: ["key", "empty"])
    }

    @Test(.tags(.key))
    func `[key] end in escape`() throws {
        try invalidate(pathComponents: ["key", "end-in-escape"])
    }

    @Test(.tags(.key))
    func `[key] escape`() throws {
        try invalidate(pathComponents: ["key", "escape"])
    }

    @Test(.tags(.key))
    func `[key] hash`() throws {
        try invalidate(pathComponents: ["key", "hash"])
    }

    @Test(.tags(.key))
    func `[key] multiline key 01`() throws {
        try invalidate(pathComponents: ["key", "multiline-key-01"])
    }

    @Test(.tags(.key))
    func `[key] multiline key 02`() throws {
        try invalidate(pathComponents: ["key", "multiline-key-02"])
    }

    @Test(.tags(.key))
    func `[key] multiline key 03`() throws {
        try invalidate(pathComponents: ["key", "multiline-key-03"])
    }

    @Test(.tags(.key))
    func `[key] multiline key 04`() throws {
        try invalidate(pathComponents: ["key", "multiline-key-04"])
    }

    @Test(.tags(.key))
    func `[key] newline 01`() throws {
        try invalidate(pathComponents: ["key", "newline-01"])
    }

    @Test(.tags(.key))
    func `[key] newline 02`() throws {
        try invalidate(pathComponents: ["key", "newline-02"])
    }

    @Test(.tags(.key))
    func `[key] newline 03`() throws {
        try invalidate(pathComponents: ["key", "newline-03"])
    }

    @Test(.tags(.key))
    func `[key] newline 04`() throws {
        try invalidate(pathComponents: ["key", "newline-04"])
    }

    @Test(.tags(.key))
    func `[key] newline 05`() throws {
        try invalidate(pathComponents: ["key", "newline-05"])
    }

    @Test(.tags(.key))
    func `[key] newline 06`() throws {
        try invalidate(pathComponents: ["key", "newline-06"])
    }

    @Test(.tags(.key))
    func `[key] no eol 01`() throws {
        try invalidate(pathComponents: ["key", "no-eol-01"])
    }

    @Test(.tags(.key))
    func `[key] no eol 02`() throws {
        try invalidate(pathComponents: ["key", "no-eol-02"])
    }

    @Test(.tags(.key))
    func `[key] no eol 03`() throws {
        try invalidate(pathComponents: ["key", "no-eol-03"])
    }

    @Test(.tags(.key))
    func `[key] no eol 04`() throws {
        try invalidate(pathComponents: ["key", "no-eol-04"])
    }

    @Test(.tags(.key))
    func `[key] no eol 05`() throws {
        try invalidate(pathComponents: ["key", "no-eol-05"])
    }

    @Test(.tags(.key))
    func `[key] no eol 06`() throws {
        try invalidate(pathComponents: ["key", "no-eol-06"])
    }

    @Test(.tags(.key))
    func `[key] no eol 07`() throws {
        try invalidate(pathComponents: ["key", "no-eol-07"])
    }

    @Test(.tags(.key))
    func `[key] only float`() throws {
        try invalidate(pathComponents: ["key", "only-float"])
    }

    @Test(.tags(.key))
    func `[key] only int`() throws {
        try invalidate(pathComponents: ["key", "only-int"])
    }

    @Test(.tags(.key))
    func `[key] only str`() throws {
        try invalidate(pathComponents: ["key", "only-str"])
    }

    @Test(.tags(.key))
    func `[key] open bracket`() throws {
        try invalidate(pathComponents: ["key", "open-bracket"])
    }

    @Test(.tags(.key))
    func `[key] partial quoted`() throws {
        try invalidate(pathComponents: ["key", "partial-quoted"])
    }

    @Test(.tags(.key))
    func `[key] quoted unclosed 01`() throws {
        try invalidate(pathComponents: ["key", "quoted-unclosed-01"])
    }

    @Test(.tags(.key))
    func `[key] quoted unclosed 02`() throws {
        try invalidate(pathComponents: ["key", "quoted-unclosed-02"])
    }

    @Test(.tags(.key))
    func `[key] single open bracket`() throws {
        try invalidate(pathComponents: ["key", "single-open-bracket"])
    }

    @Test(.tags(.key))
    func `[key] space`() throws {
        try invalidate(pathComponents: ["key", "space"])
    }

    @Test(.tags(.key))
    func `[key] special character`() throws {
        try invalidate(pathComponents: ["key", "special-character"])
    }

    @Test(.tags(.key))
    func `[key] start bracket`() throws {
        try invalidate(pathComponents: ["key", "start-bracket"])
    }

    @Test(.tags(.key))
    func `[key] start dot`() throws {
        try invalidate(pathComponents: ["key", "start-dot"])
    }

    @Test(.tags(.key))
    func `[key] two equals 01`() throws {
        try invalidate(pathComponents: ["key", "two-equals-01"])
    }

    @Test(.tags(.key))
    func `[key] two equals 02`() throws {
        try invalidate(pathComponents: ["key", "two-equals-02"])
    }

    @Test(.tags(.key))
    func `[key] two equals 03`() throws {
        try invalidate(pathComponents: ["key", "two-equals-03"])
    }

    @Test(.tags(.key))
    func `[key] without value 01`() throws {
        try invalidate(pathComponents: ["key", "without-value-01"])
    }

    @Test(.tags(.key))
    func `[key] without value 02`() throws {
        try invalidate(pathComponents: ["key", "without-value-02"])
    }

    @Test(.tags(.key))
    func `[key] without value 03`() throws {
        try invalidate(pathComponents: ["key", "without-value-03"])
    }

    @Test(.tags(.key))
    func `[key] without value 04`() throws {
        try invalidate(pathComponents: ["key", "without-value-04"])
    }

    @Test(.tags(.key))
    func `[key] without value 05`() throws {
        try invalidate(pathComponents: ["key", "without-value-05"])
    }

    @Test(.tags(.key))
    func `[key] without value 06`() throws {
        try invalidate(pathComponents: ["key", "without-value-06"])
    }

    @Test(.tags(.key))
    func `[key] without value 07`() throws {
        try invalidate(pathComponents: ["key", "without-value-07"])
    }

    @Test(.tags(.local_date))
    func `[local-date] day 1digit`() throws {
        try invalidate(pathComponents: ["local-date", "day-1digit"])
    }

    @Test(.tags(.local_date))
    func `[local-date] feb 29`() throws {
        try invalidate(pathComponents: ["local-date", "feb-29"])
    }

    @Test(.tags(.local_date))
    func `[local-date] feb 30`() throws {
        try invalidate(pathComponents: ["local-date", "feb-30"])
    }

    @Test(.tags(.local_date))
    func `[local-date] mday over`() throws {
        try invalidate(pathComponents: ["local-date", "mday-over"])
    }

    @Test(.tags(.local_date))
    func `[local-date] mday under`() throws {
        try invalidate(pathComponents: ["local-date", "mday-under"])
    }

    @Test(.tags(.local_date))
    func `[local-date] month over`() throws {
        try invalidate(pathComponents: ["local-date", "month-over"])
    }

    @Test(.tags(.local_date))
    func `[local-date] month under`() throws {
        try invalidate(pathComponents: ["local-date", "month-under"])
    }

    @Test(.tags(.local_date))
    func `[local-date] no leads`() throws {
        try invalidate(pathComponents: ["local-date", "no-leads"])
    }

    @Test(.tags(.local_date))
    func `[local-date] no leads with milli`() throws {
        try invalidate(pathComponents: ["local-date", "no-leads-with-milli"])
    }

    @Test(.tags(.local_date))
    func `[local-date] trailing t`() throws {
        try invalidate(pathComponents: ["local-date", "trailing-t"])
    }

    @Test(.tags(.local_date))
    func `[local-date] y10k`() throws {
        try invalidate(pathComponents: ["local-date", "y10k"])
    }

    @Test(.tags(.local_date))
    func `[local-date] year 3digits`() throws {
        try invalidate(pathComponents: ["local-date", "year-3digits"])
    }

    @Test(.tags(.local_datetime))
    func `[local-datetime] feb 29`() throws {
        try invalidate(pathComponents: ["local-datetime", "feb-29"])
    }

    @Test(.tags(.local_datetime))
    func `[local-datetime] feb 30`() throws {
        try invalidate(pathComponents: ["local-datetime", "feb-30"])
    }

    @Test(.tags(.local_datetime))
    func `[local-datetime] hour over`() throws {
        try invalidate(pathComponents: ["local-datetime", "hour-over"])
    }

    @Test(.tags(.local_datetime))
    func `[local-datetime] mday over`() throws {
        try invalidate(pathComponents: ["local-datetime", "mday-over"])
    }

    @Test(.tags(.local_datetime))
    func `[local-datetime] mday under`() throws {
        try invalidate(pathComponents: ["local-datetime", "mday-under"])
    }

    @Test(.tags(.local_datetime))
    func `[local-datetime] minute over`() throws {
        try invalidate(pathComponents: ["local-datetime", "minute-over"])
    }

    @Test(.tags(.local_datetime))
    func `[local-datetime] month over`() throws {
        try invalidate(pathComponents: ["local-datetime", "month-over"])
    }

    @Test(.tags(.local_datetime))
    func `[local-datetime] month under`() throws {
        try invalidate(pathComponents: ["local-datetime", "month-under"])
    }

    @Test(.tags(.local_datetime))
    func `[local-datetime] no leads`() throws {
        try invalidate(pathComponents: ["local-datetime", "no-leads"])
    }

    @Test(.tags(.local_datetime))
    func `[local-datetime] no leads with milli`() throws {
        try invalidate(pathComponents: ["local-datetime", "no-leads-with-milli"])
    }

    @Test(.tags(.local_datetime))
    func `[local-datetime] no secs`() throws {
        try invalidate(pathComponents: ["local-datetime", "no-secs"])
    }

    @Test(.tags(.local_datetime))
    func `[local-datetime] no t`() throws {
        try invalidate(pathComponents: ["local-datetime", "no-t"])
    }

    @Test(.tags(.local_datetime))
    func `[local-datetime] second over`() throws {
        try invalidate(pathComponents: ["local-datetime", "second-over"])
    }

    @Test(.tags(.local_datetime))
    func `[local-datetime] time no leads`() throws {
        try invalidate(pathComponents: ["local-datetime", "time-no-leads"])
    }

    @Test(.tags(.local_datetime))
    func `[local-datetime] y10k`() throws {
        try invalidate(pathComponents: ["local-datetime", "y10k"])
    }

    @Test(.tags(.local_time))
    func `[local-time] hour over`() throws {
        try invalidate(pathComponents: ["local-time", "hour-over"])
    }

    @Test(.tags(.local_time))
    func `[local-time] minute over`() throws {
        try invalidate(pathComponents: ["local-time", "minute-over"])
    }

    @Test(.tags(.local_time))
    func `[local-time] no secs`() throws {
        try invalidate(pathComponents: ["local-time", "no-secs"])
    }

    @Test(.tags(.local_time))
    func `[local-time] second over`() throws {
        try invalidate(pathComponents: ["local-time", "second-over"])
    }

    @Test(.tags(.local_time))
    func `[local-time] time no leads 01`() throws {
        try invalidate(pathComponents: ["local-time", "time-no-leads-01"])
    }

    @Test(.tags(.local_time))
    func `[local-time] time no leads 02`() throws {
        try invalidate(pathComponents: ["local-time", "time-no-leads-02"])
    }

    @Test(.tags(.local_time))
    func `[local-time] trailing dot`() throws {
        try invalidate(pathComponents: ["local-time", "trailing-dot"])
    }

    @Test(.tags(.local_time))
    func `[local-time] trailing dotdot`() throws {
        try invalidate(pathComponents: ["local-time", "trailing-dotdot"])
    }

    @Test(.tags(.spec_1_0_0))
    func `[spec-1.0.0] inline table 2 0`() throws {
        try invalidate(pathComponents: ["spec-1.0.0", "inline-table-2-0"])
    }

    @Test(.tags(.spec_1_0_0))
    func `[spec-1.0.0] inline table 3 0`() throws {
        try invalidate(pathComponents: ["spec-1.0.0", "inline-table-3-0"])
    }

    @Test(.tags(.spec_1_0_0))
    func `[spec-1.0.0] key value pair 1`() throws {
        try invalidate(pathComponents: ["spec-1.0.0", "key-value-pair-1"])
    }

    @Test(.tags(.spec_1_0_0))
    func `[spec-1.0.0] keys 2`() throws {
        try invalidate(pathComponents: ["spec-1.0.0", "keys-2"])
    }

    @Test(.tags(.spec_1_0_0))
    func `[spec-1.0.0] string 4 0`() throws {
        try invalidate(pathComponents: ["spec-1.0.0", "string-4-0"])
    }

    @Test(.tags(.spec_1_0_0))
    func `[spec-1.0.0] string 7 0`() throws {
        try invalidate(pathComponents: ["spec-1.0.0", "string-7-0"])
    }

    @Test(.tags(.spec_1_0_0))
    func `[spec-1.0.0] table 9 0`() throws {
        try invalidate(pathComponents: ["spec-1.0.0", "table-9-0"])
    }

    @Test(.tags(.spec_1_0_0))
    func `[spec-1.0.0] table 9 1`() throws {
        try invalidate(pathComponents: ["spec-1.0.0", "table-9-1"])
    }

    @Test(.tags(.string))
    func `[string] bad byte escape`() throws {
        try invalidate(pathComponents: ["string", "bad-byte-escape"])
    }

    @Test(.tags(.string))
    func `[string] bad concat`() throws {
        try invalidate(pathComponents: ["string", "bad-concat"])
    }

    @Test(.tags(.string))
    func `[string] bad escape 01`() throws {
        try invalidate(pathComponents: ["string", "bad-escape-01"])
    }

    @Test(.tags(.string))
    func `[string] bad escape 02`() throws {
        try invalidate(pathComponents: ["string", "bad-escape-02"])
    }

    @Test(.tags(.string))
    func `[string] bad escape 03`() throws {
        try invalidate(pathComponents: ["string", "bad-escape-03"])
    }

    @Test(.tags(.string))
    func `[string] bad escape 04`() throws {
        try invalidate(pathComponents: ["string", "bad-escape-04"])
    }

    @Test(.tags(.string))
    func `[string] bad escape 05`() throws {
        try invalidate(pathComponents: ["string", "bad-escape-05"])
    }

    @Test(.tags(.string))
    func `[string] bad hex esc 01`() throws {
        try invalidate(pathComponents: ["string", "bad-hex-esc-01"])
    }

    @Test(.tags(.string))
    func `[string] bad hex esc 02`() throws {
        try invalidate(pathComponents: ["string", "bad-hex-esc-02"])
    }

    @Test(.tags(.string))
    func `[string] bad hex esc 03`() throws {
        try invalidate(pathComponents: ["string", "bad-hex-esc-03"])
    }

    @Test(.tags(.string))
    func `[string] bad hex esc 04`() throws {
        try invalidate(pathComponents: ["string", "bad-hex-esc-04"])
    }

    @Test(.tags(.string))
    func `[string] bad hex esc 05`() throws {
        try invalidate(pathComponents: ["string", "bad-hex-esc-05"])
    }

    @Test(.tags(.string))
    func `[string] bad hex esc 1`() throws {
        try invalidate(pathComponents: ["string", "bad-hex-esc-1"])
    }

    @Test(.tags(.string))
    func `[string] bad hex esc 2`() throws {
        try invalidate(pathComponents: ["string", "bad-hex-esc-2"])
    }

    @Test(.tags(.string))
    func `[string] bad hex esc 3`() throws {
        try invalidate(pathComponents: ["string", "bad-hex-esc-3"])
    }

    @Test(.tags(.string))
    func `[string] bad hex esc 4`() throws {
        try invalidate(pathComponents: ["string", "bad-hex-esc-4"])
    }

    @Test(.tags(.string))
    func `[string] bad multiline`() throws {
        try invalidate(pathComponents: ["string", "bad-multiline"])
    }

    @Test(.tags(.string))
    func `[string] bad slash escape`() throws {
        try invalidate(pathComponents: ["string", "bad-slash-escape"])
    }

    @Test(.tags(.string))
    func `[string] bad uni esc 01`() throws {
        try invalidate(pathComponents: ["string", "bad-uni-esc-01"])
    }

    @Test(.tags(.string))
    func `[string] bad uni esc 02`() throws {
        try invalidate(pathComponents: ["string", "bad-uni-esc-02"])
    }

    @Test(.tags(.string))
    func `[string] bad uni esc 03`() throws {
        try invalidate(pathComponents: ["string", "bad-uni-esc-03"])
    }

    @Test(.tags(.string))
    func `[string] bad uni esc 04`() throws {
        try invalidate(pathComponents: ["string", "bad-uni-esc-04"])
    }

    @Test(.tags(.string))
    func `[string] bad uni esc 05`() throws {
        try invalidate(pathComponents: ["string", "bad-uni-esc-05"])
    }

    @Test(.tags(.string))
    func `[string] bad uni esc 06`() throws {
        try invalidate(pathComponents: ["string", "bad-uni-esc-06"])
    }

    @Test(.tags(.string))
    func `[string] bad uni esc 07`() throws {
        try invalidate(pathComponents: ["string", "bad-uni-esc-07"])
    }

    @Test(.tags(.string))
    func `[string] bad uni esc 1`() throws {
        try invalidate(pathComponents: ["string", "bad-uni-esc-1"])
    }

    @Test(.tags(.string))
    func `[string] bad uni esc 2`() throws {
        try invalidate(pathComponents: ["string", "bad-uni-esc-2"])
    }

    @Test(.tags(.string))
    func `[string] bad uni esc 3`() throws {
        try invalidate(pathComponents: ["string", "bad-uni-esc-3"])
    }

    @Test(.tags(.string))
    func `[string] bad uni esc 4`() throws {
        try invalidate(pathComponents: ["string", "bad-uni-esc-4"])
    }

    @Test(.tags(.string))
    func `[string] bad uni esc 5`() throws {
        try invalidate(pathComponents: ["string", "bad-uni-esc-5"])
    }

    @Test(.tags(.string))
    func `[string] bad uni esc 6`() throws {
        try invalidate(pathComponents: ["string", "bad-uni-esc-6"])
    }

    @Test(.tags(.string))
    func `[string] bad uni esc 7`() throws {
        try invalidate(pathComponents: ["string", "bad-uni-esc-7"])
    }

    @Test(.tags(.string))
    func `[string] bad uni esc ml 1`() throws {
        try invalidate(pathComponents: ["string", "bad-uni-esc-ml-1"])
    }

    @Test(.tags(.string))
    func `[string] bad uni esc ml 2`() throws {
        try invalidate(pathComponents: ["string", "bad-uni-esc-ml-2"])
    }

    @Test(.tags(.string))
    func `[string] bad uni esc ml 3`() throws {
        try invalidate(pathComponents: ["string", "bad-uni-esc-ml-3"])
    }

    @Test(.tags(.string))
    func `[string] bad uni esc ml 4`() throws {
        try invalidate(pathComponents: ["string", "bad-uni-esc-ml-4"])
    }

    @Test(.tags(.string))
    func `[string] bad uni esc ml 5`() throws {
        try invalidate(pathComponents: ["string", "bad-uni-esc-ml-5"])
    }

    @Test(.tags(.string))
    func `[string] bad uni esc ml 6`() throws {
        try invalidate(pathComponents: ["string", "bad-uni-esc-ml-6"])
    }

    @Test(.tags(.string))
    func `[string] bad uni esc ml 7`() throws {
        try invalidate(pathComponents: ["string", "bad-uni-esc-ml-7"])
    }

    @Test(.tags(.string))
    func `[string] basic byte escapes`() throws {
        try invalidate(pathComponents: ["string", "basic-byte-escapes"])
    }

    @Test(.tags(.string))
    func `[string] basic multiline out of range unicode escape 01`() throws {
        try invalidate(pathComponents: ["string", "basic-multiline-out-of-range-unicode-escape-01"])
    }

    @Test(.tags(.string))
    func `[string] basic multiline out of range unicode escape 02`() throws {
        try invalidate(pathComponents: ["string", "basic-multiline-out-of-range-unicode-escape-02"])
    }

    @Test(.tags(.string))
    func `[string] basic multiline quotes`() throws {
        try invalidate(pathComponents: ["string", "basic-multiline-quotes"])
    }

    @Test(.tags(.string))
    func `[string] basic multiline unknown escape`() throws {
        try invalidate(pathComponents: ["string", "basic-multiline-unknown-escape"])
    }

    @Test(.tags(.string))
    func `[string] basic out of range unicode escape 01`() throws {
        try invalidate(pathComponents: ["string", "basic-out-of-range-unicode-escape-01"])
    }

    @Test(.tags(.string))
    func `[string] basic out of range unicode escape 02`() throws {
        try invalidate(pathComponents: ["string", "basic-out-of-range-unicode-escape-02"])
    }

    @Test(.tags(.string))
    func `[string] basic unknown escape`() throws {
        try invalidate(pathComponents: ["string", "basic-unknown-escape"])
    }

    @Test(.tags(.string))
    func `[string] literal multiline quotes 01`() throws {
        try invalidate(pathComponents: ["string", "literal-multiline-quotes-01"])
    }

    @Test(.tags(.string))
    func `[string] literal multiline quotes 02`() throws {
        try invalidate(pathComponents: ["string", "literal-multiline-quotes-02"])
    }

    @Test(.tags(.string))
    func `[string] missing quotes`() throws {
        try invalidate(pathComponents: ["string", "missing-quotes"])
    }

    @Test(.tags(.string))
    func `[string] missing quotes array`() throws {
        try invalidate(pathComponents: ["string", "missing-quotes-array"])
    }

    @Test(.tags(.string))
    func `[string] missing quotes inline table`() throws {
        try invalidate(pathComponents: ["string", "missing-quotes-inline-table"])
    }

    @Test(.tags(.string))
    func `[string] multiline bad escape 01`() throws {
        try invalidate(pathComponents: ["string", "multiline-bad-escape-01"])
    }

    @Test(.tags(.string))
    func `[string] multiline bad escape 02`() throws {
        try invalidate(pathComponents: ["string", "multiline-bad-escape-02"])
    }

    @Test(.tags(.string))
    func `[string] multiline bad escape 03`() throws {
        try invalidate(pathComponents: ["string", "multiline-bad-escape-03"])
    }

    @Test(.tags(.string))
    func `[string] multiline bad escape 04`() throws {
        try invalidate(pathComponents: ["string", "multiline-bad-escape-04"])
    }

    @Test(.tags(.string))
    func `[string] multiline escape space 01`() throws {
        try invalidate(pathComponents: ["string", "multiline-escape-space-01"])
    }

    @Test(.tags(.string))
    func `[string] multiline escape space 02`() throws {
        try invalidate(pathComponents: ["string", "multiline-escape-space-02"])
    }

    @Test(.tags(.string))
    func `[string] multiline lit no close 01`() throws {
        try invalidate(pathComponents: ["string", "multiline-lit-no-close-01"])
    }

    @Test(.tags(.string))
    func `[string] multiline lit no close 02`() throws {
        try invalidate(pathComponents: ["string", "multiline-lit-no-close-02"])
    }

    @Test(.tags(.string))
    func `[string] multiline lit no close 03`() throws {
        try invalidate(pathComponents: ["string", "multiline-lit-no-close-03"])
    }

    @Test(.tags(.string))
    func `[string] multiline lit no close 04`() throws {
        try invalidate(pathComponents: ["string", "multiline-lit-no-close-04"])
    }

    @Test(.tags(.string))
    func `[string] multiline no close 01`() throws {
        try invalidate(pathComponents: ["string", "multiline-no-close-01"])
    }

    @Test(.tags(.string))
    func `[string] multiline no close 02`() throws {
        try invalidate(pathComponents: ["string", "multiline-no-close-02"])
    }

    @Test(.tags(.string))
    func `[string] multiline no close 03`() throws {
        try invalidate(pathComponents: ["string", "multiline-no-close-03"])
    }

    @Test(.tags(.string))
    func `[string] multiline no close 04`() throws {
        try invalidate(pathComponents: ["string", "multiline-no-close-04"])
    }

    @Test(.tags(.string))
    func `[string] multiline no close 05`() throws {
        try invalidate(pathComponents: ["string", "multiline-no-close-05"])
    }

    @Test(.tags(.string))
    func `[string] multiline quotes 01`() throws {
        try invalidate(pathComponents: ["string", "multiline-quotes-01"])
    }

    @Test(.tags(.string))
    func `[string] no close 01`() throws {
        try invalidate(pathComponents: ["string", "no-close-01"])
    }

    @Test(.tags(.string))
    func `[string] no close 02`() throws {
        try invalidate(pathComponents: ["string", "no-close-02"])
    }

    @Test(.tags(.string))
    func `[string] no close 03`() throws {
        try invalidate(pathComponents: ["string", "no-close-03"])
    }

    @Test(.tags(.string))
    func `[string] no close 04`() throws {
        try invalidate(pathComponents: ["string", "no-close-04"])
    }

    @Test(.tags(.string))
    func `[string] no close 05`() throws {
        try invalidate(pathComponents: ["string", "no-close-05"])
    }

    @Test(.tags(.string))
    func `[string] no close 06`() throws {
        try invalidate(pathComponents: ["string", "no-close-06"])
    }

    @Test(.tags(.string))
    func `[string] no close 07`() throws {
        try invalidate(pathComponents: ["string", "no-close-07"])
    }

    @Test(.tags(.string))
    func `[string] no close 08`() throws {
        try invalidate(pathComponents: ["string", "no-close-08"])
    }

    @Test(.tags(.string))
    func `[string] no close 09`() throws {
        try invalidate(pathComponents: ["string", "no-close-09"])
    }

    @Test(.tags(.string))
    func `[string] no close 10`() throws {
        try invalidate(pathComponents: ["string", "no-close-10"])
    }

    @Test(.tags(.string))
    func `[string] no open 01`() throws {
        try invalidate(pathComponents: ["string", "no-open-01"])
    }

    @Test(.tags(.string))
    func `[string] no open 02`() throws {
        try invalidate(pathComponents: ["string", "no-open-02"])
    }

    @Test(.tags(.string))
    func `[string] no open 03`() throws {
        try invalidate(pathComponents: ["string", "no-open-03"])
    }

    @Test(.tags(.string))
    func `[string] no open 04`() throws {
        try invalidate(pathComponents: ["string", "no-open-04"])
    }

    @Test(.tags(.string))
    func `[string] no open 05`() throws {
        try invalidate(pathComponents: ["string", "no-open-05"])
    }

    @Test(.tags(.string))
    func `[string] no open 06`() throws {
        try invalidate(pathComponents: ["string", "no-open-06"])
    }

    @Test(.tags(.string))
    func `[string] no open 07`() throws {
        try invalidate(pathComponents: ["string", "no-open-07"])
    }

    @Test(.tags(.string))
    func `[string] no open 08`() throws {
        try invalidate(pathComponents: ["string", "no-open-08"])
    }

    @Test(.tags(.string))
    func `[string] text after string`() throws {
        try invalidate(pathComponents: ["string", "text-after-string"])
    }

    @Test(.tags(.string))
    func `[string] wrong close`() throws {
        try invalidate(pathComponents: ["string", "wrong-close"])
    }

    @Test(.tags(.table))
    func `[table] append with dotted keys 01`() throws {
        try invalidate(pathComponents: ["table", "append-with-dotted-keys-01"])
    }

    @Test(.tags(.table))
    func `[table] append with dotted keys 02`() throws {
        try invalidate(pathComponents: ["table", "append-with-dotted-keys-02"])
    }

    @Test(.tags(.table))
    func `[table] append with dotted keys 03`() throws {
        try invalidate(pathComponents: ["table", "append-with-dotted-keys-03"])
    }

    @Test(.tags(.table))
    func `[table] append with dotted keys 04`() throws {
        try invalidate(pathComponents: ["table", "append-with-dotted-keys-04"])
    }

    @Test(.tags(.table))
    func `[table] append with dotted keys 05`() throws {
        try invalidate(pathComponents: ["table", "append-with-dotted-keys-05"])
    }

    @Test(.tags(.table))
    func `[table] append with dotted keys 06`() throws {
        try invalidate(pathComponents: ["table", "append-with-dotted-keys-06"])
    }

    @Test(.tags(.table))
    func `[table] append with dotted keys 07`() throws {
        try invalidate(pathComponents: ["table", "append-with-dotted-keys-07"])
    }

    @Test(.tags(.table))
    func `[table] array empty`() throws {
        try invalidate(pathComponents: ["table", "array-empty"])
    }

    @Test(.tags(.table))
    func `[table] array implicit`() throws {
        try invalidate(pathComponents: ["table", "array-implicit"])
    }

    @Test(.tags(.table))
    func `[table] array no close 01`() throws {
        try invalidate(pathComponents: ["table", "array-no-close-01"])
    }

    @Test(.tags(.table))
    func `[table] array no close 02`() throws {
        try invalidate(pathComponents: ["table", "array-no-close-02"])
    }

    @Test(.tags(.table))
    func `[table] array no close 03`() throws {
        try invalidate(pathComponents: ["table", "array-no-close-03"])
    }

    @Test(.tags(.table))
    func `[table] array no close 04`() throws {
        try invalidate(pathComponents: ["table", "array-no-close-04"])
    }

    @Test(.tags(.table))
    func `[table] bare invalid character 01`() throws {
        try invalidate(pathComponents: ["table", "bare-invalid-character-01"])
    }

    @Test(.tags(.table))
    func `[table] bare invalid character 02`() throws {
        try invalidate(pathComponents: ["table", "bare-invalid-character-02"])
    }

    @Test(.tags(.table))
    func `[table] dot`() throws {
        try invalidate(pathComponents: ["table", "dot"])
    }

    @Test(.tags(.table))
    func `[table] dotdot`() throws {
        try invalidate(pathComponents: ["table", "dotdot"])
    }

    @Test(.tags(.table))
    func `[table] duplicate key 01`() throws {
        try invalidate(pathComponents: ["table", "duplicate-key-01"])
    }

    @Test(.tags(.table))
    func `[table] duplicate key 02`() throws {
        try invalidate(pathComponents: ["table", "duplicate-key-02"])
    }

    @Test(.tags(.table))
    func `[table] duplicate key 03`() throws {
        try invalidate(pathComponents: ["table", "duplicate-key-03"])
    }

    @Test(.tags(.table))
    func `[table] duplicate key 04`() throws {
        try invalidate(pathComponents: ["table", "duplicate-key-04"])
    }

    @Test(.tags(.table))
    func `[table] duplicate key 05`() throws {
        try invalidate(pathComponents: ["table", "duplicate-key-05"])
    }

    @Test(.tags(.table))
    func `[table] duplicate key 06`() throws {
        try invalidate(pathComponents: ["table", "duplicate-key-06"])
    }

    @Test(.tags(.table))
    func `[table] duplicate key 07`() throws {
        try invalidate(pathComponents: ["table", "duplicate-key-07"])
    }

    @Test(.tags(.table))
    func `[table] duplicate key 08`() throws {
        try invalidate(pathComponents: ["table", "duplicate-key-08"])
    }

    @Test(.tags(.table))
    func `[table] duplicate key 09`() throws {
        try invalidate(pathComponents: ["table", "duplicate-key-09"])
    }

    @Test(.tags(.table))
    func `[table] duplicate key 10`() throws {
        try invalidate(pathComponents: ["table", "duplicate-key-10"])
    }

    @Test(.tags(.table))
    func `[table] empty`() throws {
        try invalidate(pathComponents: ["table", "empty"])
    }

    @Test(.tags(.table))
    func `[table] empty implicit table`() throws {
        try invalidate(pathComponents: ["table", "empty-implicit-table"])
    }

    @Test(.tags(.table))
    func `[table] equals sign`() throws {
        try invalidate(pathComponents: ["table", "equals-sign"])
    }

    @Test(.tags(.table))
    func `[table] llbrace`() throws {
        try invalidate(pathComponents: ["table", "llbrace"])
    }

    @Test(.tags(.table))
    func `[table] multiline key 01`() throws {
        try invalidate(pathComponents: ["table", "multiline-key-01"])
    }

    @Test(.tags(.table))
    func `[table] multiline key 02`() throws {
        try invalidate(pathComponents: ["table", "multiline-key-02"])
    }

    @Test(.tags(.table))
    func `[table] nested brackets close`() throws {
        try invalidate(pathComponents: ["table", "nested-brackets-close"])
    }

    @Test(.tags(.table))
    func `[table] nested brackets open`() throws {
        try invalidate(pathComponents: ["table", "nested-brackets-open"])
    }

    @Test(.tags(.table))
    func `[table] newline 01`() throws {
        try invalidate(pathComponents: ["table", "newline-01"])
    }

    @Test(.tags(.table))
    func `[table] newline 02`() throws {
        try invalidate(pathComponents: ["table", "newline-02"])
    }

    @Test(.tags(.table))
    func `[table] newline 03`() throws {
        try invalidate(pathComponents: ["table", "newline-03"])
    }

    @Test(.tags(.table))
    func `[table] newline 04`() throws {
        try invalidate(pathComponents: ["table", "newline-04"])
    }

    @Test(.tags(.table))
    func `[table] newline 05`() throws {
        try invalidate(pathComponents: ["table", "newline-05"])
    }

    @Test(.tags(.table))
    func `[table] no close 01`() throws {
        try invalidate(pathComponents: ["table", "no-close-01"])
    }

    @Test(.tags(.table))
    func `[table] no close 02`() throws {
        try invalidate(pathComponents: ["table", "no-close-02"])
    }

    @Test(.tags(.table))
    func `[table] no close 03`() throws {
        try invalidate(pathComponents: ["table", "no-close-03"])
    }

    @Test(.tags(.table))
    func `[table] no close 04`() throws {
        try invalidate(pathComponents: ["table", "no-close-04"])
    }

    @Test(.tags(.table))
    func `[table] no close 05`() throws {
        try invalidate(pathComponents: ["table", "no-close-05"])
    }

    @Test(.tags(.table))
    func `[table] no close 06`() throws {
        try invalidate(pathComponents: ["table", "no-close-06"])
    }

    @Test(.tags(.table))
    func `[table] no close 07`() throws {
        try invalidate(pathComponents: ["table", "no-close-07"])
    }

    @Test(.tags(.table))
    func `[table] no close 08`() throws {
        try invalidate(pathComponents: ["table", "no-close-08"])
    }

    @Test(.tags(.table))
    func `[table] no close 09`() throws {
        try invalidate(pathComponents: ["table", "no-close-09"])
    }

    @Test(.tags(.table))
    func `[table] overwrite array in parent`() throws {
        try invalidate(pathComponents: ["table", "overwrite-array-in-parent"])
    }

    @Test(.tags(.table))
    func `[table] overwrite bool with array`() throws {
        try invalidate(pathComponents: ["table", "overwrite-bool-with-array"])
    }

    @Test(.tags(.table))
    func `[table] overwrite with deep table`() throws {
        try invalidate(pathComponents: ["table", "overwrite-with-deep-table"])
    }

    @Test(.tags(.table))
    func `[table] redefine 01`() throws {
        try invalidate(pathComponents: ["table", "redefine-01"])
    }

    @Test(.tags(.table))
    func `[table] redefine 02`() throws {
        try invalidate(pathComponents: ["table", "redefine-02"])
    }

    @Test(.tags(.table))
    func `[table] redefine 03`() throws {
        try invalidate(pathComponents: ["table", "redefine-03"])
    }

    @Test(.tags(.table))
    func `[table] rrbrace`() throws {
        try invalidate(pathComponents: ["table", "rrbrace"])
    }

    @Test(.tags(.table))
    func `[table] super twice`() throws {
        try invalidate(pathComponents: ["table", "super-twice"])
    }

    @Test(.tags(.table))
    func `[table] text after table`() throws {
        try invalidate(pathComponents: ["table", "text-after-table"])
    }

    @Test(.tags(.table))
    func `[table] trailing dot`() throws {
        try invalidate(pathComponents: ["table", "trailing-dot"])
    }

    @Test(.tags(.table))
    func `[table] whitespace`() throws {
        try invalidate(pathComponents: ["table", "whitespace"])
    }

    @Test(.tags(.table))
    func `[table] with pound`() throws {
        try invalidate(pathComponents: ["table", "with-pound"])
    }
}
