// Generated by Scripts/generate-tests.py
// Source: toml-test commit 0ee318ae97ae5dec5f74aeccafbdc75f435580e2 (spec 1.1.0)

import Foundation
import Testing
import TOMLDecoder

@Suite
struct TOMLValidationTests {
    private var directoryURL: URL {
        URL(fileURLWithPath: #filePath)
            .deletingLastPathComponent()
            .appendingPathComponent("valid_fixtures")
    }

    private func verifyByFixture(pathComponents: [String], sourceLocation: SourceLocation = #_sourceLocation) throws {
        let baseURL = pathComponents.reduce(directoryURL) { $0.appendingPathComponent($1) }
        let jsonURL = baseURL.appendingPathExtension("json")
        let tomlURL = baseURL.appendingPathExtension("toml")
        try TOMLComplianceSupport.verifyValidFixture(jsonURL: jsonURL, tomlURL: tomlURL, sourceLocation: sourceLocation)
    }

    @Test("[array] array", .tags(.array))
    func array__array() throws {
        try verifyByFixture(pathComponents: ["array", "array"])
    }

    @Test("[array] array subtables", .tags(.array))
    func array__array_subtables() throws {
        try verifyByFixture(pathComponents: ["array", "array-subtables"])
    }

    @Test("[array] bool", .tags(.array))
    func array__bool() throws {
        try verifyByFixture(pathComponents: ["array", "bool"])
    }

    @Test("[array] empty", .tags(.array))
    func array__empty() throws {
        try verifyByFixture(pathComponents: ["array", "empty"])
    }

    @Test("[array] hetergeneous", .tags(.array))
    func array__hetergeneous() throws {
        try verifyByFixture(pathComponents: ["array", "hetergeneous"])
    }

    @Test("[array] mixed int array", .tags(.array))
    func array__mixed_int_array() throws {
        try verifyByFixture(pathComponents: ["array", "mixed-int-array"])
    }

    @Test("[array] mixed int float", .tags(.array))
    func array__mixed_int_float() throws {
        try verifyByFixture(pathComponents: ["array", "mixed-int-float"])
    }

    @Test("[array] mixed int string", .tags(.array))
    func array__mixed_int_string() throws {
        try verifyByFixture(pathComponents: ["array", "mixed-int-string"])
    }

    @Test("[array] mixed string table", .tags(.array))
    func array__mixed_string_table() throws {
        try verifyByFixture(pathComponents: ["array", "mixed-string-table"])
    }

    @Test("[array] nested", .tags(.array))
    func array__nested() throws {
        try verifyByFixture(pathComponents: ["array", "nested"])
    }

    @Test("[array] nested double", .tags(.array))
    func array__nested_double() throws {
        try verifyByFixture(pathComponents: ["array", "nested-double"])
    }

    @Test("[array] nested inline table", .tags(.array))
    func array__nested_inline_table() throws {
        try verifyByFixture(pathComponents: ["array", "nested-inline-table"])
    }

    @Test("[array] nospaces", .tags(.array))
    func array__nospaces() throws {
        try verifyByFixture(pathComponents: ["array", "nospaces"])
    }

    @Test("[array] open parent table", .tags(.array))
    func array__open_parent_table() throws {
        try verifyByFixture(pathComponents: ["array", "open-parent-table"])
    }

    @Test("[array] string quote comma 01", .tags(.array))
    func array__string_quote_comma_01() throws {
        try verifyByFixture(pathComponents: ["array", "string-quote-comma-01"])
    }

    @Test("[array] string quote comma 02", .tags(.array))
    func array__string_quote_comma_02() throws {
        try verifyByFixture(pathComponents: ["array", "string-quote-comma-02"])
    }

    @Test("[array] string with comma 01", .tags(.array))
    func array__string_with_comma_01() throws {
        try verifyByFixture(pathComponents: ["array", "string-with-comma-01"])
    }

    @Test("[array] string with comma 02", .tags(.array))
    func array__string_with_comma_02() throws {
        try verifyByFixture(pathComponents: ["array", "string-with-comma-02"])
    }

    @Test("[array] strings", .tags(.array))
    func array__strings() throws {
        try verifyByFixture(pathComponents: ["array", "strings"])
    }

    @Test("[array] table array string backslash", .tags(.array))
    func array__table_array_string_backslash() throws {
        try verifyByFixture(pathComponents: ["array", "table-array-string-backslash"])
    }

    @Test("[array] trailing comma", .tags(.array))
    func array__trailing_comma() throws {
        try verifyByFixture(pathComponents: ["array", "trailing-comma"])
    }

    @Test("[bool] bool", .tags(.bool))
    func bool__bool() throws {
        try verifyByFixture(pathComponents: ["bool", "bool"])
    }

    @Test("[comment] after literal no ws", .tags(.comment))
    func comment__after_literal_no_ws() throws {
        try verifyByFixture(pathComponents: ["comment", "after-literal-no-ws"])
    }

    @Test("[comment] at eof", .tags(.comment))
    func comment__at_eof() throws {
        try verifyByFixture(pathComponents: ["comment", "at-eof"])
    }

    @Test("[comment] at eof2", .tags(.comment))
    func comment__at_eof2() throws {
        try verifyByFixture(pathComponents: ["comment", "at-eof2"])
    }

    @Test("[comment] everywhere", .tags(.comment))
    func comment__everywhere() throws {
        try verifyByFixture(pathComponents: ["comment", "everywhere"])
    }

    @Test("[comment] noeol", .tags(.comment))
    func comment__noeol() throws {
        try verifyByFixture(pathComponents: ["comment", "noeol"])
    }

    @Test("[comment] nonascii", .tags(.comment))
    func comment__nonascii() throws {
        try verifyByFixture(pathComponents: ["comment", "nonascii"])
    }

    @Test("[comment] tricky", .tags(.comment))
    func comment__tricky() throws {
        try verifyByFixture(pathComponents: ["comment", "tricky"])
    }

    @Test("[datetime] datetime", .tags(.datetime))
    func datetime__datetime() throws {
        try verifyByFixture(pathComponents: ["datetime", "datetime"])
    }

    @Test("[datetime] edge", .tags(.datetime))
    func datetime__edge() throws {
        try verifyByFixture(pathComponents: ["datetime", "edge"])
    }

    @Test("[datetime] invalid date in string", .tags(.datetime))
    func datetime__invalid_date_in_string() throws {
        try verifyByFixture(pathComponents: ["datetime", "invalid-date-in-string"])
    }

    @Test("[datetime] leap year", .tags(.datetime))
    func datetime__leap_year() throws {
        try verifyByFixture(pathComponents: ["datetime", "leap-year"])
    }

    @Test("[datetime] local", .tags(.datetime))
    func datetime__local() throws {
        try verifyByFixture(pathComponents: ["datetime", "local"])
    }

    @Test("[datetime] local date", .tags(.datetime))
    func datetime__local_date() throws {
        try verifyByFixture(pathComponents: ["datetime", "local-date"])
    }

    @Test("[datetime] local time", .tags(.datetime))
    func datetime__local_time() throws {
        try verifyByFixture(pathComponents: ["datetime", "local-time"])
    }

    @Test("[datetime] milliseconds", .tags(.datetime))
    func datetime__milliseconds() throws {
        try verifyByFixture(pathComponents: ["datetime", "milliseconds"])
    }

    @Test("[datetime] no seconds", .tags(.datetime))
    func datetime__no_seconds() throws {
        try verifyByFixture(pathComponents: ["datetime", "no-seconds"])
    }

    @Test("[datetime] timezone", .tags(.datetime))
    func datetime__timezone() throws {
        try verifyByFixture(pathComponents: ["datetime", "timezone"])
    }

    @Test("empty crlf")
    func empty_crlf() throws {
        try verifyByFixture(pathComponents: ["empty-crlf"])
    }

    @Test("empty lf")
    func empty_lf() throws {
        try verifyByFixture(pathComponents: ["empty-lf"])
    }

    @Test("empty nothing")
    func empty_nothing() throws {
        try verifyByFixture(pathComponents: ["empty-nothing"])
    }

    @Test("empty space")
    func empty_space() throws {
        try verifyByFixture(pathComponents: ["empty-space"])
    }

    @Test("empty tab")
    func empty_tab() throws {
        try verifyByFixture(pathComponents: ["empty-tab"])
    }

    @Test("example")
    func example() throws {
        try verifyByFixture(pathComponents: ["example"])
    }

    @Test("[float] exponent", .tags(.float))
    func float__exponent() throws {
        try verifyByFixture(pathComponents: ["float", "exponent"])
    }

    @Test("[float] float", .tags(.float))
    func float__float() throws {
        try verifyByFixture(pathComponents: ["float", "float"])
    }

    @Test("[float] inf and nan", .tags(.float))
    func float__inf_and_nan() throws {
        try verifyByFixture(pathComponents: ["float", "inf-and-nan"])
    }

    @Test("[float] long", .tags(.float))
    func float__long() throws {
        try verifyByFixture(pathComponents: ["float", "long"])
    }

    @Test("[float] max int", .tags(.float))
    func float__max_int() throws {
        try verifyByFixture(pathComponents: ["float", "max-int"])
    }

    @Test("[float] underscore", .tags(.float))
    func float__underscore() throws {
        try verifyByFixture(pathComponents: ["float", "underscore"])
    }

    @Test("[float] zero", .tags(.float))
    func float__zero() throws {
        try verifyByFixture(pathComponents: ["float", "zero"])
    }

    @Test("implicit and explicit after")
    func implicit_and_explicit_after() throws {
        try verifyByFixture(pathComponents: ["implicit-and-explicit-after"])
    }

    @Test("implicit and explicit before")
    func implicit_and_explicit_before() throws {
        try verifyByFixture(pathComponents: ["implicit-and-explicit-before"])
    }

    @Test("implicit groups")
    func implicit_groups() throws {
        try verifyByFixture(pathComponents: ["implicit-groups"])
    }

    @Test("[inline-table] array 01", .tags(.inline_table))
    func inline_table__array_01() throws {
        try verifyByFixture(pathComponents: ["inline-table", "array-01"])
    }

    @Test("[inline-table] array 02", .tags(.inline_table))
    func inline_table__array_02() throws {
        try verifyByFixture(pathComponents: ["inline-table", "array-02"])
    }

    @Test("[inline-table] array 03", .tags(.inline_table))
    func inline_table__array_03() throws {
        try verifyByFixture(pathComponents: ["inline-table", "array-03"])
    }

    @Test("[inline-table] bool", .tags(.inline_table))
    func inline_table__bool() throws {
        try verifyByFixture(pathComponents: ["inline-table", "bool"])
    }

    @Test("[inline-table] empty", .tags(.inline_table))
    func inline_table__empty() throws {
        try verifyByFixture(pathComponents: ["inline-table", "empty"])
    }

    @Test("[inline-table] end in bool", .tags(.inline_table))
    func inline_table__end_in_bool() throws {
        try verifyByFixture(pathComponents: ["inline-table", "end-in-bool"])
    }

    @Test("[inline-table] inline table", .tags(.inline_table))
    func inline_table__inline_table() throws {
        try verifyByFixture(pathComponents: ["inline-table", "inline-table"])
    }

    @Test("[inline-table] key dotted 01", .tags(.inline_table))
    func inline_table__key_dotted_01() throws {
        try verifyByFixture(pathComponents: ["inline-table", "key-dotted-01"])
    }

    @Test("[inline-table] key dotted 02", .tags(.inline_table))
    func inline_table__key_dotted_02() throws {
        try verifyByFixture(pathComponents: ["inline-table", "key-dotted-02"])
    }

    @Test("[inline-table] key dotted 03", .tags(.inline_table))
    func inline_table__key_dotted_03() throws {
        try verifyByFixture(pathComponents: ["inline-table", "key-dotted-03"])
    }

    @Test("[inline-table] key dotted 04", .tags(.inline_table))
    func inline_table__key_dotted_04() throws {
        try verifyByFixture(pathComponents: ["inline-table", "key-dotted-04"])
    }

    @Test("[inline-table] key dotted 05", .tags(.inline_table))
    func inline_table__key_dotted_05() throws {
        try verifyByFixture(pathComponents: ["inline-table", "key-dotted-05"])
    }

    @Test("[inline-table] key dotted 06", .tags(.inline_table))
    func inline_table__key_dotted_06() throws {
        try verifyByFixture(pathComponents: ["inline-table", "key-dotted-06"])
    }

    @Test("[inline-table] key dotted 07", .tags(.inline_table))
    func inline_table__key_dotted_07() throws {
        try verifyByFixture(pathComponents: ["inline-table", "key-dotted-07"])
    }

    @Test("[inline-table] multiline", .tags(.inline_table))
    func inline_table__multiline() throws {
        try verifyByFixture(pathComponents: ["inline-table", "multiline"])
    }

    @Test("[inline-table] nest", .tags(.inline_table))
    func inline_table__nest() throws {
        try verifyByFixture(pathComponents: ["inline-table", "nest"])
    }

    @Test("[inline-table] newline", .tags(.inline_table))
    func inline_table__newline() throws {
        try verifyByFixture(pathComponents: ["inline-table", "newline"])
    }

    @Test("[inline-table] newline comment", .tags(.inline_table))
    func inline_table__newline_comment() throws {
        try verifyByFixture(pathComponents: ["inline-table", "newline-comment"])
    }

    @Test("[inline-table] spaces", .tags(.inline_table))
    func inline_table__spaces() throws {
        try verifyByFixture(pathComponents: ["inline-table", "spaces"])
    }

    @Test("[integer] float64 max", .tags(.integer))
    func integer__float64_max() throws {
        try verifyByFixture(pathComponents: ["integer", "float64-max"])
    }

    @Test("[integer] integer", .tags(.integer))
    func integer__integer() throws {
        try verifyByFixture(pathComponents: ["integer", "integer"])
    }

    @Test("[integer] literals", .tags(.integer))
    func integer__literals() throws {
        try verifyByFixture(pathComponents: ["integer", "literals"])
    }

    @Test("[integer] long", .tags(.integer))
    func integer__long() throws {
        try verifyByFixture(pathComponents: ["integer", "long"])
    }

    @Test("[integer] underscore", .tags(.integer))
    func integer__underscore() throws {
        try verifyByFixture(pathComponents: ["integer", "underscore"])
    }

    @Test("[integer] zero", .tags(.integer))
    func integer__zero() throws {
        try verifyByFixture(pathComponents: ["integer", "zero"])
    }

    @Test("[key] alphanum", .tags(.key))
    func key__alphanum() throws {
        try verifyByFixture(pathComponents: ["key", "alphanum"])
    }

    @Test("[key] case sensitive", .tags(.key))
    func key__case_sensitive() throws {
        try verifyByFixture(pathComponents: ["key", "case-sensitive"])
    }

    @Test("[key] dotted 01", .tags(.key))
    func key__dotted_01() throws {
        try verifyByFixture(pathComponents: ["key", "dotted-01"])
    }

    @Test("[key] dotted 02", .tags(.key))
    func key__dotted_02() throws {
        try verifyByFixture(pathComponents: ["key", "dotted-02"])
    }

    @Test("[key] dotted 03", .tags(.key))
    func key__dotted_03() throws {
        try verifyByFixture(pathComponents: ["key", "dotted-03"])
    }

    @Test("[key] dotted 04", .tags(.key))
    func key__dotted_04() throws {
        try verifyByFixture(pathComponents: ["key", "dotted-04"])
    }

    @Test("[key] dotted empty", .tags(.key))
    func key__dotted_empty() throws {
        try verifyByFixture(pathComponents: ["key", "dotted-empty"])
    }

    @Test("[key] empty 01", .tags(.key))
    func key__empty_01() throws {
        try verifyByFixture(pathComponents: ["key", "empty-01"])
    }

    @Test("[key] empty 02", .tags(.key))
    func key__empty_02() throws {
        try verifyByFixture(pathComponents: ["key", "empty-02"])
    }

    @Test("[key] empty 03", .tags(.key))
    func key__empty_03() throws {
        try verifyByFixture(pathComponents: ["key", "empty-03"])
    }

    @Test("[key] equals nospace", .tags(.key))
    func key__equals_nospace() throws {
        try verifyByFixture(pathComponents: ["key", "equals-nospace"])
    }

    @Test("[key] escapes", .tags(.key))
    func key__escapes() throws {
        try verifyByFixture(pathComponents: ["key", "escapes"])
    }

    @Test("[key] like date", .tags(.key))
    func key__like_date() throws {
        try verifyByFixture(pathComponents: ["key", "like-date"])
    }

    @Test("[key] numeric 01", .tags(.key))
    func key__numeric_01() throws {
        try verifyByFixture(pathComponents: ["key", "numeric-01"])
    }

    @Test("[key] numeric 02", .tags(.key))
    func key__numeric_02() throws {
        try verifyByFixture(pathComponents: ["key", "numeric-02"])
    }

    @Test("[key] numeric 03", .tags(.key))
    func key__numeric_03() throws {
        try verifyByFixture(pathComponents: ["key", "numeric-03"])
    }

    @Test("[key] numeric 04", .tags(.key))
    func key__numeric_04() throws {
        try verifyByFixture(pathComponents: ["key", "numeric-04"])
    }

    @Test("[key] numeric 05", .tags(.key))
    func key__numeric_05() throws {
        try verifyByFixture(pathComponents: ["key", "numeric-05"])
    }

    @Test("[key] numeric 06", .tags(.key))
    func key__numeric_06() throws {
        try verifyByFixture(pathComponents: ["key", "numeric-06"])
    }

    @Test("[key] numeric 07", .tags(.key))
    func key__numeric_07() throws {
        try verifyByFixture(pathComponents: ["key", "numeric-07"])
    }

    @Test("[key] numeric 08", .tags(.key))
    func key__numeric_08() throws {
        try verifyByFixture(pathComponents: ["key", "numeric-08"])
    }

    @Test("[key] quoted dots", .tags(.key))
    func key__quoted_dots() throws {
        try verifyByFixture(pathComponents: ["key", "quoted-dots"])
    }

    @Test("[key] quoted unicode", .tags(.key))
    func key__quoted_unicode() throws {
        try verifyByFixture(pathComponents: ["key", "quoted-unicode"])
    }

    @Test("[key] space", .tags(.key))
    func key__space() throws {
        try verifyByFixture(pathComponents: ["key", "space"])
    }

    @Test("[key] special chars", .tags(.key))
    func key__special_chars() throws {
        try verifyByFixture(pathComponents: ["key", "special-chars"])
    }

    @Test("[key] special word", .tags(.key))
    func key__special_word() throws {
        try verifyByFixture(pathComponents: ["key", "special-word"])
    }

    @Test("[key] start", .tags(.key))
    func key__start() throws {
        try verifyByFixture(pathComponents: ["key", "start"])
    }

    @Test("[key] zero", .tags(.key))
    func key__zero() throws {
        try verifyByFixture(pathComponents: ["key", "zero"])
    }

    @Test("multibyte")
    func multibyte() throws {
        try verifyByFixture(pathComponents: ["multibyte"])
    }

    @Test("newline crlf")
    func newline_crlf() throws {
        try verifyByFixture(pathComponents: ["newline-crlf"])
    }

    @Test("newline lf")
    func newline_lf() throws {
        try verifyByFixture(pathComponents: ["newline-lf"])
    }

    @Test("[spec-1.1.0] common 0", .tags(.spec_1_1_0))
    func spec_1_1_0__common_0() throws {
        try verifyByFixture(pathComponents: ["spec-1.1.0", "common-0"])
    }

    @Test("[spec-1.1.0] common 1", .tags(.spec_1_1_0))
    func spec_1_1_0__common_1() throws {
        try verifyByFixture(pathComponents: ["spec-1.1.0", "common-1"])
    }

    @Test("[spec-1.1.0] common 10", .tags(.spec_1_1_0))
    func spec_1_1_0__common_10() throws {
        try verifyByFixture(pathComponents: ["spec-1.1.0", "common-10"])
    }

    @Test("[spec-1.1.0] common 11", .tags(.spec_1_1_0))
    func spec_1_1_0__common_11() throws {
        try verifyByFixture(pathComponents: ["spec-1.1.0", "common-11"])
    }

    @Test("[spec-1.1.0] common 12", .tags(.spec_1_1_0))
    func spec_1_1_0__common_12() throws {
        try verifyByFixture(pathComponents: ["spec-1.1.0", "common-12"])
    }

    @Test("[spec-1.1.0] common 13", .tags(.spec_1_1_0))
    func spec_1_1_0__common_13() throws {
        try verifyByFixture(pathComponents: ["spec-1.1.0", "common-13"])
    }

    @Test("[spec-1.1.0] common 14", .tags(.spec_1_1_0))
    func spec_1_1_0__common_14() throws {
        try verifyByFixture(pathComponents: ["spec-1.1.0", "common-14"])
    }

    @Test("[spec-1.1.0] common 15", .tags(.spec_1_1_0))
    func spec_1_1_0__common_15() throws {
        try verifyByFixture(pathComponents: ["spec-1.1.0", "common-15"])
    }

    @Test("[spec-1.1.0] common 16", .tags(.spec_1_1_0))
    func spec_1_1_0__common_16() throws {
        try verifyByFixture(pathComponents: ["spec-1.1.0", "common-16"])
    }

    @Test("[spec-1.1.0] common 17", .tags(.spec_1_1_0))
    func spec_1_1_0__common_17() throws {
        try verifyByFixture(pathComponents: ["spec-1.1.0", "common-17"])
    }

    @Test("[spec-1.1.0] common 18", .tags(.spec_1_1_0))
    func spec_1_1_0__common_18() throws {
        try verifyByFixture(pathComponents: ["spec-1.1.0", "common-18"])
    }

    @Test("[spec-1.1.0] common 19", .tags(.spec_1_1_0))
    func spec_1_1_0__common_19() throws {
        try verifyByFixture(pathComponents: ["spec-1.1.0", "common-19"])
    }

    @Test("[spec-1.1.0] common 20", .tags(.spec_1_1_0))
    func spec_1_1_0__common_20() throws {
        try verifyByFixture(pathComponents: ["spec-1.1.0", "common-20"])
    }

    @Test("[spec-1.1.0] common 21", .tags(.spec_1_1_0))
    func spec_1_1_0__common_21() throws {
        try verifyByFixture(pathComponents: ["spec-1.1.0", "common-21"])
    }

    @Test("[spec-1.1.0] common 22", .tags(.spec_1_1_0))
    func spec_1_1_0__common_22() throws {
        try verifyByFixture(pathComponents: ["spec-1.1.0", "common-22"])
    }

    @Test("[spec-1.1.0] common 23", .tags(.spec_1_1_0))
    func spec_1_1_0__common_23() throws {
        try verifyByFixture(pathComponents: ["spec-1.1.0", "common-23"])
    }

    @Test("[spec-1.1.0] common 24", .tags(.spec_1_1_0))
    func spec_1_1_0__common_24() throws {
        try verifyByFixture(pathComponents: ["spec-1.1.0", "common-24"])
    }

    @Test("[spec-1.1.0] common 25", .tags(.spec_1_1_0))
    func spec_1_1_0__common_25() throws {
        try verifyByFixture(pathComponents: ["spec-1.1.0", "common-25"])
    }

    @Test("[spec-1.1.0] common 26", .tags(.spec_1_1_0))
    func spec_1_1_0__common_26() throws {
        try verifyByFixture(pathComponents: ["spec-1.1.0", "common-26"])
    }

    @Test("[spec-1.1.0] common 27", .tags(.spec_1_1_0))
    func spec_1_1_0__common_27() throws {
        try verifyByFixture(pathComponents: ["spec-1.1.0", "common-27"])
    }

    @Test("[spec-1.1.0] common 28", .tags(.spec_1_1_0))
    func spec_1_1_0__common_28() throws {
        try verifyByFixture(pathComponents: ["spec-1.1.0", "common-28"])
    }

    @Test("[spec-1.1.0] common 29", .tags(.spec_1_1_0))
    func spec_1_1_0__common_29() throws {
        try verifyByFixture(pathComponents: ["spec-1.1.0", "common-29"])
    }

    @Test("[spec-1.1.0] common 3", .tags(.spec_1_1_0))
    func spec_1_1_0__common_3() throws {
        try verifyByFixture(pathComponents: ["spec-1.1.0", "common-3"])
    }

    @Test("[spec-1.1.0] common 30", .tags(.spec_1_1_0))
    func spec_1_1_0__common_30() throws {
        try verifyByFixture(pathComponents: ["spec-1.1.0", "common-30"])
    }

    @Test("[spec-1.1.0] common 31", .tags(.spec_1_1_0))
    func spec_1_1_0__common_31() throws {
        try verifyByFixture(pathComponents: ["spec-1.1.0", "common-31"])
    }

    @Test("[spec-1.1.0] common 32", .tags(.spec_1_1_0))
    func spec_1_1_0__common_32() throws {
        try verifyByFixture(pathComponents: ["spec-1.1.0", "common-32"])
    }

    @Test("[spec-1.1.0] common 33", .tags(.spec_1_1_0))
    func spec_1_1_0__common_33() throws {
        try verifyByFixture(pathComponents: ["spec-1.1.0", "common-33"])
    }

    @Test("[spec-1.1.0] common 34", .tags(.spec_1_1_0))
    func spec_1_1_0__common_34() throws {
        try verifyByFixture(pathComponents: ["spec-1.1.0", "common-34"])
    }

    @Test("[spec-1.1.0] common 35", .tags(.spec_1_1_0))
    func spec_1_1_0__common_35() throws {
        try verifyByFixture(pathComponents: ["spec-1.1.0", "common-35"])
    }

    @Test("[spec-1.1.0] common 36", .tags(.spec_1_1_0))
    func spec_1_1_0__common_36() throws {
        try verifyByFixture(pathComponents: ["spec-1.1.0", "common-36"])
    }

    @Test("[spec-1.1.0] common 37", .tags(.spec_1_1_0))
    func spec_1_1_0__common_37() throws {
        try verifyByFixture(pathComponents: ["spec-1.1.0", "common-37"])
    }

    @Test("[spec-1.1.0] common 38", .tags(.spec_1_1_0))
    func spec_1_1_0__common_38() throws {
        try verifyByFixture(pathComponents: ["spec-1.1.0", "common-38"])
    }

    @Test("[spec-1.1.0] common 39", .tags(.spec_1_1_0))
    func spec_1_1_0__common_39() throws {
        try verifyByFixture(pathComponents: ["spec-1.1.0", "common-39"])
    }

    @Test("[spec-1.1.0] common 4", .tags(.spec_1_1_0))
    func spec_1_1_0__common_4() throws {
        try verifyByFixture(pathComponents: ["spec-1.1.0", "common-4"])
    }

    @Test("[spec-1.1.0] common 40", .tags(.spec_1_1_0))
    func spec_1_1_0__common_40() throws {
        try verifyByFixture(pathComponents: ["spec-1.1.0", "common-40"])
    }

    @Test("[spec-1.1.0] common 41", .tags(.spec_1_1_0))
    func spec_1_1_0__common_41() throws {
        try verifyByFixture(pathComponents: ["spec-1.1.0", "common-41"])
    }

    @Test("[spec-1.1.0] common 42", .tags(.spec_1_1_0))
    func spec_1_1_0__common_42() throws {
        try verifyByFixture(pathComponents: ["spec-1.1.0", "common-42"])
    }

    @Test("[spec-1.1.0] common 43", .tags(.spec_1_1_0))
    func spec_1_1_0__common_43() throws {
        try verifyByFixture(pathComponents: ["spec-1.1.0", "common-43"])
    }

    @Test("[spec-1.1.0] common 44", .tags(.spec_1_1_0))
    func spec_1_1_0__common_44() throws {
        try verifyByFixture(pathComponents: ["spec-1.1.0", "common-44"])
    }

    @Test("[spec-1.1.0] common 45", .tags(.spec_1_1_0))
    func spec_1_1_0__common_45() throws {
        try verifyByFixture(pathComponents: ["spec-1.1.0", "common-45"])
    }

    @Test("[spec-1.1.0] common 46", .tags(.spec_1_1_0))
    func spec_1_1_0__common_46() throws {
        try verifyByFixture(pathComponents: ["spec-1.1.0", "common-46"])
    }

    @Test("[spec-1.1.0] common 47", .tags(.spec_1_1_0))
    func spec_1_1_0__common_47() throws {
        try verifyByFixture(pathComponents: ["spec-1.1.0", "common-47"])
    }

    @Test("[spec-1.1.0] common 48", .tags(.spec_1_1_0))
    func spec_1_1_0__common_48() throws {
        try verifyByFixture(pathComponents: ["spec-1.1.0", "common-48"])
    }

    @Test("[spec-1.1.0] common 49", .tags(.spec_1_1_0))
    func spec_1_1_0__common_49() throws {
        try verifyByFixture(pathComponents: ["spec-1.1.0", "common-49"])
    }

    @Test("[spec-1.1.0] common 50", .tags(.spec_1_1_0))
    func spec_1_1_0__common_50() throws {
        try verifyByFixture(pathComponents: ["spec-1.1.0", "common-50"])
    }

    @Test("[spec-1.1.0] common 51", .tags(.spec_1_1_0))
    func spec_1_1_0__common_51() throws {
        try verifyByFixture(pathComponents: ["spec-1.1.0", "common-51"])
    }

    @Test("[spec-1.1.0] common 52", .tags(.spec_1_1_0))
    func spec_1_1_0__common_52() throws {
        try verifyByFixture(pathComponents: ["spec-1.1.0", "common-52"])
    }

    @Test("[spec-1.1.0] common 53", .tags(.spec_1_1_0))
    func spec_1_1_0__common_53() throws {
        try verifyByFixture(pathComponents: ["spec-1.1.0", "common-53"])
    }

    @Test("[spec-1.1.0] common 6", .tags(.spec_1_1_0))
    func spec_1_1_0__common_6() throws {
        try verifyByFixture(pathComponents: ["spec-1.1.0", "common-6"])
    }

    @Test("[spec-1.1.0] common 7", .tags(.spec_1_1_0))
    func spec_1_1_0__common_7() throws {
        try verifyByFixture(pathComponents: ["spec-1.1.0", "common-7"])
    }

    @Test("[spec-1.1.0] common 8", .tags(.spec_1_1_0))
    func spec_1_1_0__common_8() throws {
        try verifyByFixture(pathComponents: ["spec-1.1.0", "common-8"])
    }

    @Test("[spec-1.1.0] common 9", .tags(.spec_1_1_0))
    func spec_1_1_0__common_9() throws {
        try verifyByFixture(pathComponents: ["spec-1.1.0", "common-9"])
    }

    @Test("spec example 1")
    func spec_example_1() throws {
        try verifyByFixture(pathComponents: ["spec-example-1"])
    }

    @Test("spec example 1 compact")
    func spec_example_1_compact() throws {
        try verifyByFixture(pathComponents: ["spec-example-1-compact"])
    }

    @Test("[string] basic escape 01", .tags(.string))
    func string__basic_escape_01() throws {
        try verifyByFixture(pathComponents: ["string", "basic-escape-01"])
    }

    @Test("[string] basic escape 02", .tags(.string))
    func string__basic_escape_02() throws {
        try verifyByFixture(pathComponents: ["string", "basic-escape-02"])
    }

    @Test("[string] basic escape 03", .tags(.string))
    func string__basic_escape_03() throws {
        try verifyByFixture(pathComponents: ["string", "basic-escape-03"])
    }

    @Test("[string] empty", .tags(.string))
    func string__empty() throws {
        try verifyByFixture(pathComponents: ["string", "empty"])
    }

    @Test("[string] ends in whitespace escape", .tags(.string))
    func string__ends_in_whitespace_escape() throws {
        try verifyByFixture(pathComponents: ["string", "ends-in-whitespace-escape"])
    }

    @Test("[string] escape esc", .tags(.string))
    func string__escape_esc() throws {
        try verifyByFixture(pathComponents: ["string", "escape-esc"])
    }

    @Test("[string] escape tricky", .tags(.string))
    func string__escape_tricky() throws {
        try verifyByFixture(pathComponents: ["string", "escape-tricky"])
    }

    @Test("[string] escaped escape", .tags(.string))
    func string__escaped_escape() throws {
        try verifyByFixture(pathComponents: ["string", "escaped-escape"])
    }

    @Test("[string] escapes", .tags(.string))
    func string__escapes() throws {
        try verifyByFixture(pathComponents: ["string", "escapes"])
    }

    @Test("[string] hex escape", .tags(.string))
    func string__hex_escape() throws {
        try verifyByFixture(pathComponents: ["string", "hex-escape"])
    }

    @Test("[string] multibyte", .tags(.string))
    func string__multibyte() throws {
        try verifyByFixture(pathComponents: ["string", "multibyte"])
    }

    @Test("[string] multibyte escape", .tags(.string))
    func string__multibyte_escape() throws {
        try verifyByFixture(pathComponents: ["string", "multibyte-escape"])
    }

    @Test("[string] multiline", .tags(.string))
    func string__multiline() throws {
        try verifyByFixture(pathComponents: ["string", "multiline"])
    }

    @Test("[string] multiline empty", .tags(.string))
    func string__multiline_empty() throws {
        try verifyByFixture(pathComponents: ["string", "multiline-empty"])
    }

    @Test("[string] multiline escaped crlf", .tags(.string))
    func string__multiline_escaped_crlf() throws {
        try verifyByFixture(pathComponents: ["string", "multiline-escaped-crlf"])
    }

    @Test("[string] multiline quotes", .tags(.string))
    func string__multiline_quotes() throws {
        try verifyByFixture(pathComponents: ["string", "multiline-quotes"])
    }

    @Test("[string] nl", .tags(.string))
    func string__nl() throws {
        try verifyByFixture(pathComponents: ["string", "nl"])
    }

    @Test("[string] quoted unicode", .tags(.string))
    func string__quoted_unicode() throws {
        try verifyByFixture(pathComponents: ["string", "quoted-unicode"])
    }

    @Test("[string] raw", .tags(.string))
    func string__raw() throws {
        try verifyByFixture(pathComponents: ["string", "raw"])
    }

    @Test("[string] raw empty", .tags(.string))
    func string__raw_empty() throws {
        try verifyByFixture(pathComponents: ["string", "raw-empty"])
    }

    @Test("[string] raw multiline", .tags(.string))
    func string__raw_multiline() throws {
        try verifyByFixture(pathComponents: ["string", "raw-multiline"])
    }

    @Test("[string] simple", .tags(.string))
    func string__simple() throws {
        try verifyByFixture(pathComponents: ["string", "simple"])
    }

    @Test("[string] start mb", .tags(.string))
    func string__start_mb() throws {
        try verifyByFixture(pathComponents: ["string", "start-mb"])
    }

    @Test("[string] unicode escape", .tags(.string))
    func string__unicode_escape() throws {
        try verifyByFixture(pathComponents: ["string", "unicode-escape"])
    }

    @Test("[string] with pound", .tags(.string))
    func string__with_pound() throws {
        try verifyByFixture(pathComponents: ["string", "with-pound"])
    }

    @Test("[table] array empty", .tags(.table))
    func table__array_empty() throws {
        try verifyByFixture(pathComponents: ["table", "array-empty"])
    }

    @Test("[table] array empty name", .tags(.table))
    func table__array_empty_name() throws {
        try verifyByFixture(pathComponents: ["table", "array-empty-name"])
    }

    @Test("[table] array implicit", .tags(.table))
    func table__array_implicit() throws {
        try verifyByFixture(pathComponents: ["table", "array-implicit"])
    }

    @Test("[table] array implicit and explicit after", .tags(.table))
    func table__array_implicit_and_explicit_after() throws {
        try verifyByFixture(pathComponents: ["table", "array-implicit-and-explicit-after"])
    }

    @Test("[table] array many", .tags(.table))
    func table__array_many() throws {
        try verifyByFixture(pathComponents: ["table", "array-many"])
    }

    @Test("[table] array nest", .tags(.table))
    func table__array_nest() throws {
        try verifyByFixture(pathComponents: ["table", "array-nest"])
    }

    @Test("[table] array one", .tags(.table))
    func table__array_one() throws {
        try verifyByFixture(pathComponents: ["table", "array-one"])
    }

    @Test("[table] array table array", .tags(.table))
    func table__array_table_array() throws {
        try verifyByFixture(pathComponents: ["table", "array-table-array"])
    }

    @Test("[table] array within dotted", .tags(.table))
    func table__array_within_dotted() throws {
        try verifyByFixture(pathComponents: ["table", "array-within-dotted"])
    }

    @Test("[table] empty", .tags(.table))
    func table__empty() throws {
        try verifyByFixture(pathComponents: ["table", "empty"])
    }

    @Test("[table] empty name", .tags(.table))
    func table__empty_name() throws {
        try verifyByFixture(pathComponents: ["table", "empty-name"])
    }

    @Test("[table] keyword", .tags(.table))
    func table__keyword() throws {
        try verifyByFixture(pathComponents: ["table", "keyword"])
    }

    @Test("[table] keyword with values", .tags(.table))
    func table__keyword_with_values() throws {
        try verifyByFixture(pathComponents: ["table", "keyword-with-values"])
    }

    @Test("[table] names", .tags(.table))
    func table__names() throws {
        try verifyByFixture(pathComponents: ["table", "names"])
    }

    @Test("[table] names with values", .tags(.table))
    func table__names_with_values() throws {
        try verifyByFixture(pathComponents: ["table", "names-with-values"])
    }

    @Test("[table] no eol", .tags(.table))
    func table__no_eol() throws {
        try verifyByFixture(pathComponents: ["table", "no-eol"])
    }

    @Test("[table] sub", .tags(.table))
    func table__sub() throws {
        try verifyByFixture(pathComponents: ["table", "sub"])
    }

    @Test("[table] sub empty", .tags(.table))
    func table__sub_empty() throws {
        try verifyByFixture(pathComponents: ["table", "sub-empty"])
    }

    @Test("[table] whitespace", .tags(.table))
    func table__whitespace() throws {
        try verifyByFixture(pathComponents: ["table", "whitespace"])
    }

    @Test("[table] with literal string", .tags(.table))
    func table__with_literal_string() throws {
        try verifyByFixture(pathComponents: ["table", "with-literal-string"])
    }

    @Test("[table] with pound", .tags(.table))
    func table__with_pound() throws {
        try verifyByFixture(pathComponents: ["table", "with-pound"])
    }

    @Test("[table] with single quotes", .tags(.table))
    func table__with_single_quotes() throws {
        try verifyByFixture(pathComponents: ["table", "with-single-quotes"])
    }

    @Test("[table] without super", .tags(.table))
    func table__without_super() throws {
        try verifyByFixture(pathComponents: ["table", "without-super"])
    }

    @Test("[table] without super with values", .tags(.table))
    func table__without_super_with_values() throws {
        try verifyByFixture(pathComponents: ["table", "without-super-with-values"])
    }
}
