// Generated by Scripts/generate-tests.py
// Source: toml-test commit 0ee318ae97ae5dec5f74aeccafbdc75f435580e2 (spec 1.1.0)

import Foundation
import Testing
import TOMLDecoder

struct TOMLValidationTests {
    private var directoryURL: URL {
        URL(fileURLWithPath: #filePath)
            .deletingLastPathComponent()
            .appendingPathComponent("valid_fixtures")
    }

    private func verifyByFixture(pathComponents: [String], sourceLocation: SourceLocation = #_sourceLocation) throws {
        let baseURL = pathComponents.reduce(directoryURL) { $0.appendingPathComponent($1) }
        let jsonURL = baseURL.appendingPathExtension("json")
        let tomlURL = baseURL.appendingPathExtension("toml")
        try TOMLComplianceSupport.verifyValidFixture(jsonURL: jsonURL, tomlURL: tomlURL, sourceLocation: sourceLocation)
    }

    @Test(.tags(.array))
    func `[array] array`() throws {
        try verifyByFixture(pathComponents: ["array", "array"])
    }

    @Test(.tags(.array))
    func `[array] array subtables`() throws {
        try verifyByFixture(pathComponents: ["array", "array-subtables"])
    }

    @Test(.tags(.array))
    func `[array] bool`() throws {
        try verifyByFixture(pathComponents: ["array", "bool"])
    }

    @Test(.tags(.array))
    func `[array] empty`() throws {
        try verifyByFixture(pathComponents: ["array", "empty"])
    }

    @Test(.tags(.array))
    func `[array] hetergeneous`() throws {
        try verifyByFixture(pathComponents: ["array", "hetergeneous"])
    }

    @Test(.tags(.array))
    func `[array] mixed int array`() throws {
        try verifyByFixture(pathComponents: ["array", "mixed-int-array"])
    }

    @Test(.tags(.array))
    func `[array] mixed int float`() throws {
        try verifyByFixture(pathComponents: ["array", "mixed-int-float"])
    }

    @Test(.tags(.array))
    func `[array] mixed int string`() throws {
        try verifyByFixture(pathComponents: ["array", "mixed-int-string"])
    }

    @Test(.tags(.array))
    func `[array] mixed string table`() throws {
        try verifyByFixture(pathComponents: ["array", "mixed-string-table"])
    }

    @Test(.tags(.array))
    func `[array] nested`() throws {
        try verifyByFixture(pathComponents: ["array", "nested"])
    }

    @Test(.tags(.array))
    func `[array] nested double`() throws {
        try verifyByFixture(pathComponents: ["array", "nested-double"])
    }

    @Test(.tags(.array))
    func `[array] nested inline table`() throws {
        try verifyByFixture(pathComponents: ["array", "nested-inline-table"])
    }

    @Test(.tags(.array))
    func `[array] nospaces`() throws {
        try verifyByFixture(pathComponents: ["array", "nospaces"])
    }

    @Test(.tags(.array))
    func `[array] open parent table`() throws {
        try verifyByFixture(pathComponents: ["array", "open-parent-table"])
    }

    @Test(.tags(.array))
    func `[array] string quote comma 01`() throws {
        try verifyByFixture(pathComponents: ["array", "string-quote-comma-01"])
    }

    @Test(.tags(.array))
    func `[array] string quote comma 02`() throws {
        try verifyByFixture(pathComponents: ["array", "string-quote-comma-02"])
    }

    @Test(.tags(.array))
    func `[array] string with comma 01`() throws {
        try verifyByFixture(pathComponents: ["array", "string-with-comma-01"])
    }

    @Test(.tags(.array))
    func `[array] string with comma 02`() throws {
        try verifyByFixture(pathComponents: ["array", "string-with-comma-02"])
    }

    @Test(.tags(.array))
    func `[array] strings`() throws {
        try verifyByFixture(pathComponents: ["array", "strings"])
    }

    @Test(.tags(.array))
    func `[array] table array string backslash`() throws {
        try verifyByFixture(pathComponents: ["array", "table-array-string-backslash"])
    }

    @Test(.tags(.array))
    func `[array] trailing comma`() throws {
        try verifyByFixture(pathComponents: ["array", "trailing-comma"])
    }

    @Test(.tags(.bool))
    func `[bool] bool`() throws {
        try verifyByFixture(pathComponents: ["bool", "bool"])
    }

    @Test(.tags(.comment))
    func `[comment] after literal no ws`() throws {
        try verifyByFixture(pathComponents: ["comment", "after-literal-no-ws"])
    }

    @Test(.tags(.comment))
    func `[comment] at eof`() throws {
        try verifyByFixture(pathComponents: ["comment", "at-eof"])
    }

    @Test(.tags(.comment))
    func `[comment] at eof2`() throws {
        try verifyByFixture(pathComponents: ["comment", "at-eof2"])
    }

    @Test(.tags(.comment))
    func `[comment] everywhere`() throws {
        try verifyByFixture(pathComponents: ["comment", "everywhere"])
    }

    @Test(.tags(.comment))
    func `[comment] noeol`() throws {
        try verifyByFixture(pathComponents: ["comment", "noeol"])
    }

    @Test(.tags(.comment))
    func `[comment] nonascii`() throws {
        try verifyByFixture(pathComponents: ["comment", "nonascii"])
    }

    @Test(.tags(.comment))
    func `[comment] tricky`() throws {
        try verifyByFixture(pathComponents: ["comment", "tricky"])
    }

    @Test(.tags(.datetime))
    func `[datetime] datetime`() throws {
        try verifyByFixture(pathComponents: ["datetime", "datetime"])
    }

    @Test(.tags(.datetime))
    func `[datetime] edge`() throws {
        try verifyByFixture(pathComponents: ["datetime", "edge"])
    }

    @Test(.tags(.datetime))
    func `[datetime] invalid date in string`() throws {
        try verifyByFixture(pathComponents: ["datetime", "invalid-date-in-string"])
    }

    @Test(.tags(.datetime))
    func `[datetime] leap year`() throws {
        try verifyByFixture(pathComponents: ["datetime", "leap-year"])
    }

    @Test(.tags(.datetime))
    func `[datetime] local`() throws {
        try verifyByFixture(pathComponents: ["datetime", "local"])
    }

    @Test(.tags(.datetime))
    func `[datetime] local date`() throws {
        try verifyByFixture(pathComponents: ["datetime", "local-date"])
    }

    @Test(.tags(.datetime))
    func `[datetime] local time`() throws {
        try verifyByFixture(pathComponents: ["datetime", "local-time"])
    }

    @Test(.tags(.datetime))
    func `[datetime] milliseconds`() throws {
        try verifyByFixture(pathComponents: ["datetime", "milliseconds"])
    }

    @Test(.tags(.datetime))
    func `[datetime] no seconds`() throws {
        try verifyByFixture(pathComponents: ["datetime", "no-seconds"])
    }

    @Test(.tags(.datetime))
    func `[datetime] timezone`() throws {
        try verifyByFixture(pathComponents: ["datetime", "timezone"])
    }

    @Test
    func `empty crlf`() throws {
        try verifyByFixture(pathComponents: ["empty-crlf"])
    }

    @Test
    func `empty lf`() throws {
        try verifyByFixture(pathComponents: ["empty-lf"])
    }

    @Test
    func `empty nothing`() throws {
        try verifyByFixture(pathComponents: ["empty-nothing"])
    }

    @Test
    func `empty space`() throws {
        try verifyByFixture(pathComponents: ["empty-space"])
    }

    @Test
    func `empty tab`() throws {
        try verifyByFixture(pathComponents: ["empty-tab"])
    }

    @Test
    func example() throws {
        try verifyByFixture(pathComponents: ["example"])
    }

    @Test(.tags(.float))
    func `[float] exponent`() throws {
        try verifyByFixture(pathComponents: ["float", "exponent"])
    }

    @Test(.tags(.float))
    func `[float] float`() throws {
        try verifyByFixture(pathComponents: ["float", "float"])
    }

    @Test(.tags(.float))
    func `[float] inf and nan`() throws {
        try verifyByFixture(pathComponents: ["float", "inf-and-nan"])
    }

    @Test(.tags(.float))
    func `[float] long`() throws {
        try verifyByFixture(pathComponents: ["float", "long"])
    }

    @Test(.tags(.float))
    func `[float] max int`() throws {
        try verifyByFixture(pathComponents: ["float", "max-int"])
    }

    @Test(.tags(.float))
    func `[float] underscore`() throws {
        try verifyByFixture(pathComponents: ["float", "underscore"])
    }

    @Test(.tags(.float))
    func `[float] zero`() throws {
        try verifyByFixture(pathComponents: ["float", "zero"])
    }

    @Test
    func `implicit and explicit after`() throws {
        try verifyByFixture(pathComponents: ["implicit-and-explicit-after"])
    }

    @Test
    func `implicit and explicit before`() throws {
        try verifyByFixture(pathComponents: ["implicit-and-explicit-before"])
    }

    @Test
    func `implicit groups`() throws {
        try verifyByFixture(pathComponents: ["implicit-groups"])
    }

    @Test(.tags(.inline_table))
    func `[inline-table] array 01`() throws {
        try verifyByFixture(pathComponents: ["inline-table", "array-01"])
    }

    @Test(.tags(.inline_table))
    func `[inline-table] array 02`() throws {
        try verifyByFixture(pathComponents: ["inline-table", "array-02"])
    }

    @Test(.tags(.inline_table))
    func `[inline-table] array 03`() throws {
        try verifyByFixture(pathComponents: ["inline-table", "array-03"])
    }

    @Test(.tags(.inline_table))
    func `[inline-table] bool`() throws {
        try verifyByFixture(pathComponents: ["inline-table", "bool"])
    }

    @Test(.tags(.inline_table))
    func `[inline-table] empty`() throws {
        try verifyByFixture(pathComponents: ["inline-table", "empty"])
    }

    @Test(.tags(.inline_table))
    func `[inline-table] end in bool`() throws {
        try verifyByFixture(pathComponents: ["inline-table", "end-in-bool"])
    }

    @Test(.tags(.inline_table))
    func `[inline-table] inline table`() throws {
        try verifyByFixture(pathComponents: ["inline-table", "inline-table"])
    }

    @Test(.tags(.inline_table))
    func `[inline-table] key dotted 01`() throws {
        try verifyByFixture(pathComponents: ["inline-table", "key-dotted-01"])
    }

    @Test(.tags(.inline_table))
    func `[inline-table] key dotted 02`() throws {
        try verifyByFixture(pathComponents: ["inline-table", "key-dotted-02"])
    }

    @Test(.tags(.inline_table))
    func `[inline-table] key dotted 03`() throws {
        try verifyByFixture(pathComponents: ["inline-table", "key-dotted-03"])
    }

    @Test(.tags(.inline_table))
    func `[inline-table] key dotted 04`() throws {
        try verifyByFixture(pathComponents: ["inline-table", "key-dotted-04"])
    }

    @Test(.tags(.inline_table))
    func `[inline-table] key dotted 05`() throws {
        try verifyByFixture(pathComponents: ["inline-table", "key-dotted-05"])
    }

    @Test(.tags(.inline_table))
    func `[inline-table] key dotted 06`() throws {
        try verifyByFixture(pathComponents: ["inline-table", "key-dotted-06"])
    }

    @Test(.tags(.inline_table))
    func `[inline-table] key dotted 07`() throws {
        try verifyByFixture(pathComponents: ["inline-table", "key-dotted-07"])
    }

    @Test(.tags(.inline_table))
    func `[inline-table] multiline`() throws {
        try verifyByFixture(pathComponents: ["inline-table", "multiline"])
    }

    @Test(.tags(.inline_table))
    func `[inline-table] nest`() throws {
        try verifyByFixture(pathComponents: ["inline-table", "nest"])
    }

    @Test(.tags(.inline_table))
    func `[inline-table] newline`() throws {
        try verifyByFixture(pathComponents: ["inline-table", "newline"])
    }

    @Test(.tags(.inline_table))
    func `[inline-table] newline comment`() throws {
        try verifyByFixture(pathComponents: ["inline-table", "newline-comment"])
    }

    @Test(.tags(.inline_table))
    func `[inline-table] spaces`() throws {
        try verifyByFixture(pathComponents: ["inline-table", "spaces"])
    }

    @Test(.tags(.integer))
    func `[integer] float64 max`() throws {
        try verifyByFixture(pathComponents: ["integer", "float64-max"])
    }

    @Test(.tags(.integer))
    func `[integer] integer`() throws {
        try verifyByFixture(pathComponents: ["integer", "integer"])
    }

    @Test(.tags(.integer))
    func `[integer] literals`() throws {
        try verifyByFixture(pathComponents: ["integer", "literals"])
    }

    @Test(.tags(.integer))
    func `[integer] long`() throws {
        try verifyByFixture(pathComponents: ["integer", "long"])
    }

    @Test(.tags(.integer))
    func `[integer] underscore`() throws {
        try verifyByFixture(pathComponents: ["integer", "underscore"])
    }

    @Test(.tags(.integer))
    func `[integer] zero`() throws {
        try verifyByFixture(pathComponents: ["integer", "zero"])
    }

    @Test(.tags(.key))
    func `[key] alphanum`() throws {
        try verifyByFixture(pathComponents: ["key", "alphanum"])
    }

    @Test(.tags(.key))
    func `[key] case sensitive`() throws {
        try verifyByFixture(pathComponents: ["key", "case-sensitive"])
    }

    @Test(.tags(.key))
    func `[key] dotted 01`() throws {
        try verifyByFixture(pathComponents: ["key", "dotted-01"])
    }

    @Test(.tags(.key))
    func `[key] dotted 02`() throws {
        try verifyByFixture(pathComponents: ["key", "dotted-02"])
    }

    @Test(.tags(.key))
    func `[key] dotted 03`() throws {
        try verifyByFixture(pathComponents: ["key", "dotted-03"])
    }

    @Test(.tags(.key))
    func `[key] dotted 04`() throws {
        try verifyByFixture(pathComponents: ["key", "dotted-04"])
    }

    @Test(.tags(.key))
    func `[key] dotted empty`() throws {
        try verifyByFixture(pathComponents: ["key", "dotted-empty"])
    }

    @Test(.tags(.key))
    func `[key] empty 01`() throws {
        try verifyByFixture(pathComponents: ["key", "empty-01"])
    }

    @Test(.tags(.key))
    func `[key] empty 02`() throws {
        try verifyByFixture(pathComponents: ["key", "empty-02"])
    }

    @Test(.tags(.key))
    func `[key] empty 03`() throws {
        try verifyByFixture(pathComponents: ["key", "empty-03"])
    }

    @Test(.tags(.key))
    func `[key] equals nospace`() throws {
        try verifyByFixture(pathComponents: ["key", "equals-nospace"])
    }

    @Test(.tags(.key))
    func `[key] escapes`() throws {
        try verifyByFixture(pathComponents: ["key", "escapes"])
    }

    @Test(.tags(.key))
    func `[key] like date`() throws {
        try verifyByFixture(pathComponents: ["key", "like-date"])
    }

    @Test(.tags(.key))
    func `[key] numeric 01`() throws {
        try verifyByFixture(pathComponents: ["key", "numeric-01"])
    }

    @Test(.tags(.key))
    func `[key] numeric 02`() throws {
        try verifyByFixture(pathComponents: ["key", "numeric-02"])
    }

    @Test(.tags(.key))
    func `[key] numeric 03`() throws {
        try verifyByFixture(pathComponents: ["key", "numeric-03"])
    }

    @Test(.tags(.key))
    func `[key] numeric 04`() throws {
        try verifyByFixture(pathComponents: ["key", "numeric-04"])
    }

    @Test(.tags(.key))
    func `[key] numeric 05`() throws {
        try verifyByFixture(pathComponents: ["key", "numeric-05"])
    }

    @Test(.tags(.key))
    func `[key] numeric 06`() throws {
        try verifyByFixture(pathComponents: ["key", "numeric-06"])
    }

    @Test(.tags(.key))
    func `[key] numeric 07`() throws {
        try verifyByFixture(pathComponents: ["key", "numeric-07"])
    }

    @Test(.tags(.key))
    func `[key] numeric 08`() throws {
        try verifyByFixture(pathComponents: ["key", "numeric-08"])
    }

    @Test(.tags(.key))
    func `[key] quoted dots`() throws {
        try verifyByFixture(pathComponents: ["key", "quoted-dots"])
    }

    @Test(.tags(.key))
    func `[key] quoted unicode`() throws {
        try verifyByFixture(pathComponents: ["key", "quoted-unicode"])
    }

    @Test(.tags(.key))
    func `[key] space`() throws {
        try verifyByFixture(pathComponents: ["key", "space"])
    }

    @Test(.tags(.key))
    func `[key] special chars`() throws {
        try verifyByFixture(pathComponents: ["key", "special-chars"])
    }

    @Test(.tags(.key))
    func `[key] special word`() throws {
        try verifyByFixture(pathComponents: ["key", "special-word"])
    }

    @Test(.tags(.key))
    func `[key] start`() throws {
        try verifyByFixture(pathComponents: ["key", "start"])
    }

    @Test(.tags(.key))
    func `[key] zero`() throws {
        try verifyByFixture(pathComponents: ["key", "zero"])
    }

    @Test
    func multibyte() throws {
        try verifyByFixture(pathComponents: ["multibyte"])
    }

    @Test
    func `newline crlf`() throws {
        try verifyByFixture(pathComponents: ["newline-crlf"])
    }

    @Test
    func `newline lf`() throws {
        try verifyByFixture(pathComponents: ["newline-lf"])
    }

    @Test(.tags(.spec_1_1_0))
    func `[spec-1.1.0] common 0`() throws {
        try verifyByFixture(pathComponents: ["spec-1.1.0", "common-0"])
    }

    @Test(.tags(.spec_1_1_0))
    func `[spec-1.1.0] common 1`() throws {
        try verifyByFixture(pathComponents: ["spec-1.1.0", "common-1"])
    }

    @Test(.tags(.spec_1_1_0))
    func `[spec-1.1.0] common 10`() throws {
        try verifyByFixture(pathComponents: ["spec-1.1.0", "common-10"])
    }

    @Test(.tags(.spec_1_1_0))
    func `[spec-1.1.0] common 11`() throws {
        try verifyByFixture(pathComponents: ["spec-1.1.0", "common-11"])
    }

    @Test(.tags(.spec_1_1_0))
    func `[spec-1.1.0] common 12`() throws {
        try verifyByFixture(pathComponents: ["spec-1.1.0", "common-12"])
    }

    @Test(.tags(.spec_1_1_0))
    func `[spec-1.1.0] common 13`() throws {
        try verifyByFixture(pathComponents: ["spec-1.1.0", "common-13"])
    }

    @Test(.tags(.spec_1_1_0))
    func `[spec-1.1.0] common 14`() throws {
        try verifyByFixture(pathComponents: ["spec-1.1.0", "common-14"])
    }

    @Test(.tags(.spec_1_1_0))
    func `[spec-1.1.0] common 15`() throws {
        try verifyByFixture(pathComponents: ["spec-1.1.0", "common-15"])
    }

    @Test(.tags(.spec_1_1_0))
    func `[spec-1.1.0] common 16`() throws {
        try verifyByFixture(pathComponents: ["spec-1.1.0", "common-16"])
    }

    @Test(.tags(.spec_1_1_0))
    func `[spec-1.1.0] common 17`() throws {
        try verifyByFixture(pathComponents: ["spec-1.1.0", "common-17"])
    }

    @Test(.tags(.spec_1_1_0))
    func `[spec-1.1.0] common 18`() throws {
        try verifyByFixture(pathComponents: ["spec-1.1.0", "common-18"])
    }

    @Test(.tags(.spec_1_1_0))
    func `[spec-1.1.0] common 19`() throws {
        try verifyByFixture(pathComponents: ["spec-1.1.0", "common-19"])
    }

    @Test(.tags(.spec_1_1_0))
    func `[spec-1.1.0] common 20`() throws {
        try verifyByFixture(pathComponents: ["spec-1.1.0", "common-20"])
    }

    @Test(.tags(.spec_1_1_0))
    func `[spec-1.1.0] common 21`() throws {
        try verifyByFixture(pathComponents: ["spec-1.1.0", "common-21"])
    }

    @Test(.tags(.spec_1_1_0))
    func `[spec-1.1.0] common 22`() throws {
        try verifyByFixture(pathComponents: ["spec-1.1.0", "common-22"])
    }

    @Test(.tags(.spec_1_1_0))
    func `[spec-1.1.0] common 23`() throws {
        try verifyByFixture(pathComponents: ["spec-1.1.0", "common-23"])
    }

    @Test(.tags(.spec_1_1_0))
    func `[spec-1.1.0] common 24`() throws {
        try verifyByFixture(pathComponents: ["spec-1.1.0", "common-24"])
    }

    @Test(.tags(.spec_1_1_0))
    func `[spec-1.1.0] common 25`() throws {
        try verifyByFixture(pathComponents: ["spec-1.1.0", "common-25"])
    }

    @Test(.tags(.spec_1_1_0))
    func `[spec-1.1.0] common 26`() throws {
        try verifyByFixture(pathComponents: ["spec-1.1.0", "common-26"])
    }

    @Test(.tags(.spec_1_1_0))
    func `[spec-1.1.0] common 27`() throws {
        try verifyByFixture(pathComponents: ["spec-1.1.0", "common-27"])
    }

    @Test(.tags(.spec_1_1_0))
    func `[spec-1.1.0] common 28`() throws {
        try verifyByFixture(pathComponents: ["spec-1.1.0", "common-28"])
    }

    @Test(.tags(.spec_1_1_0))
    func `[spec-1.1.0] common 29`() throws {
        try verifyByFixture(pathComponents: ["spec-1.1.0", "common-29"])
    }

    @Test(.tags(.spec_1_1_0))
    func `[spec-1.1.0] common 3`() throws {
        try verifyByFixture(pathComponents: ["spec-1.1.0", "common-3"])
    }

    @Test(.tags(.spec_1_1_0))
    func `[spec-1.1.0] common 30`() throws {
        try verifyByFixture(pathComponents: ["spec-1.1.0", "common-30"])
    }

    @Test(.tags(.spec_1_1_0))
    func `[spec-1.1.0] common 31`() throws {
        try verifyByFixture(pathComponents: ["spec-1.1.0", "common-31"])
    }

    @Test(.tags(.spec_1_1_0))
    func `[spec-1.1.0] common 32`() throws {
        try verifyByFixture(pathComponents: ["spec-1.1.0", "common-32"])
    }

    @Test(.tags(.spec_1_1_0))
    func `[spec-1.1.0] common 33`() throws {
        try verifyByFixture(pathComponents: ["spec-1.1.0", "common-33"])
    }

    @Test(.tags(.spec_1_1_0))
    func `[spec-1.1.0] common 34`() throws {
        try verifyByFixture(pathComponents: ["spec-1.1.0", "common-34"])
    }

    @Test(.tags(.spec_1_1_0))
    func `[spec-1.1.0] common 35`() throws {
        try verifyByFixture(pathComponents: ["spec-1.1.0", "common-35"])
    }

    @Test(.tags(.spec_1_1_0))
    func `[spec-1.1.0] common 36`() throws {
        try verifyByFixture(pathComponents: ["spec-1.1.0", "common-36"])
    }

    @Test(.tags(.spec_1_1_0))
    func `[spec-1.1.0] common 37`() throws {
        try verifyByFixture(pathComponents: ["spec-1.1.0", "common-37"])
    }

    @Test(.tags(.spec_1_1_0))
    func `[spec-1.1.0] common 38`() throws {
        try verifyByFixture(pathComponents: ["spec-1.1.0", "common-38"])
    }

    @Test(.tags(.spec_1_1_0))
    func `[spec-1.1.0] common 39`() throws {
        try verifyByFixture(pathComponents: ["spec-1.1.0", "common-39"])
    }

    @Test(.tags(.spec_1_1_0))
    func `[spec-1.1.0] common 4`() throws {
        try verifyByFixture(pathComponents: ["spec-1.1.0", "common-4"])
    }

    @Test(.tags(.spec_1_1_0))
    func `[spec-1.1.0] common 40`() throws {
        try verifyByFixture(pathComponents: ["spec-1.1.0", "common-40"])
    }

    @Test(.tags(.spec_1_1_0))
    func `[spec-1.1.0] common 41`() throws {
        try verifyByFixture(pathComponents: ["spec-1.1.0", "common-41"])
    }

    @Test(.tags(.spec_1_1_0))
    func `[spec-1.1.0] common 42`() throws {
        try verifyByFixture(pathComponents: ["spec-1.1.0", "common-42"])
    }

    @Test(.tags(.spec_1_1_0))
    func `[spec-1.1.0] common 43`() throws {
        try verifyByFixture(pathComponents: ["spec-1.1.0", "common-43"])
    }

    @Test(.tags(.spec_1_1_0))
    func `[spec-1.1.0] common 44`() throws {
        try verifyByFixture(pathComponents: ["spec-1.1.0", "common-44"])
    }

    @Test(.tags(.spec_1_1_0))
    func `[spec-1.1.0] common 45`() throws {
        try verifyByFixture(pathComponents: ["spec-1.1.0", "common-45"])
    }

    @Test(.tags(.spec_1_1_0))
    func `[spec-1.1.0] common 46`() throws {
        try verifyByFixture(pathComponents: ["spec-1.1.0", "common-46"])
    }

    @Test(.tags(.spec_1_1_0))
    func `[spec-1.1.0] common 47`() throws {
        try verifyByFixture(pathComponents: ["spec-1.1.0", "common-47"])
    }

    @Test(.tags(.spec_1_1_0))
    func `[spec-1.1.0] common 48`() throws {
        try verifyByFixture(pathComponents: ["spec-1.1.0", "common-48"])
    }

    @Test(.tags(.spec_1_1_0))
    func `[spec-1.1.0] common 49`() throws {
        try verifyByFixture(pathComponents: ["spec-1.1.0", "common-49"])
    }

    @Test(.tags(.spec_1_1_0))
    func `[spec-1.1.0] common 50`() throws {
        try verifyByFixture(pathComponents: ["spec-1.1.0", "common-50"])
    }

    @Test(.tags(.spec_1_1_0))
    func `[spec-1.1.0] common 51`() throws {
        try verifyByFixture(pathComponents: ["spec-1.1.0", "common-51"])
    }

    @Test(.tags(.spec_1_1_0))
    func `[spec-1.1.0] common 52`() throws {
        try verifyByFixture(pathComponents: ["spec-1.1.0", "common-52"])
    }

    @Test(.tags(.spec_1_1_0))
    func `[spec-1.1.0] common 53`() throws {
        try verifyByFixture(pathComponents: ["spec-1.1.0", "common-53"])
    }

    @Test(.tags(.spec_1_1_0))
    func `[spec-1.1.0] common 6`() throws {
        try verifyByFixture(pathComponents: ["spec-1.1.0", "common-6"])
    }

    @Test(.tags(.spec_1_1_0))
    func `[spec-1.1.0] common 7`() throws {
        try verifyByFixture(pathComponents: ["spec-1.1.0", "common-7"])
    }

    @Test(.tags(.spec_1_1_0))
    func `[spec-1.1.0] common 8`() throws {
        try verifyByFixture(pathComponents: ["spec-1.1.0", "common-8"])
    }

    @Test(.tags(.spec_1_1_0))
    func `[spec-1.1.0] common 9`() throws {
        try verifyByFixture(pathComponents: ["spec-1.1.0", "common-9"])
    }

    @Test
    func `spec example 1`() throws {
        try verifyByFixture(pathComponents: ["spec-example-1"])
    }

    @Test
    func `spec example 1 compact`() throws {
        try verifyByFixture(pathComponents: ["spec-example-1-compact"])
    }

    @Test(.tags(.string))
    func `[string] basic escape 01`() throws {
        try verifyByFixture(pathComponents: ["string", "basic-escape-01"])
    }

    @Test(.tags(.string))
    func `[string] basic escape 02`() throws {
        try verifyByFixture(pathComponents: ["string", "basic-escape-02"])
    }

    @Test(.tags(.string))
    func `[string] basic escape 03`() throws {
        try verifyByFixture(pathComponents: ["string", "basic-escape-03"])
    }

    @Test(.tags(.string))
    func `[string] empty`() throws {
        try verifyByFixture(pathComponents: ["string", "empty"])
    }

    @Test(.tags(.string))
    func `[string] ends in whitespace escape`() throws {
        try verifyByFixture(pathComponents: ["string", "ends-in-whitespace-escape"])
    }

    @Test(.tags(.string))
    func `[string] escape esc`() throws {
        try verifyByFixture(pathComponents: ["string", "escape-esc"])
    }

    @Test(.tags(.string))
    func `[string] escape tricky`() throws {
        try verifyByFixture(pathComponents: ["string", "escape-tricky"])
    }

    @Test(.tags(.string))
    func `[string] escaped escape`() throws {
        try verifyByFixture(pathComponents: ["string", "escaped-escape"])
    }

    @Test(.tags(.string))
    func `[string] escapes`() throws {
        try verifyByFixture(pathComponents: ["string", "escapes"])
    }

    @Test(.tags(.string))
    func `[string] hex escape`() throws {
        try verifyByFixture(pathComponents: ["string", "hex-escape"])
    }

    @Test(.tags(.string))
    func `[string] multibyte`() throws {
        try verifyByFixture(pathComponents: ["string", "multibyte"])
    }

    @Test(.tags(.string))
    func `[string] multibyte escape`() throws {
        try verifyByFixture(pathComponents: ["string", "multibyte-escape"])
    }

    @Test(.tags(.string))
    func `[string] multiline`() throws {
        try verifyByFixture(pathComponents: ["string", "multiline"])
    }

    @Test(.tags(.string))
    func `[string] multiline empty`() throws {
        try verifyByFixture(pathComponents: ["string", "multiline-empty"])
    }

    @Test(.tags(.string))
    func `[string] multiline escaped crlf`() throws {
        try verifyByFixture(pathComponents: ["string", "multiline-escaped-crlf"])
    }

    @Test(.tags(.string))
    func `[string] multiline quotes`() throws {
        try verifyByFixture(pathComponents: ["string", "multiline-quotes"])
    }

    @Test(.tags(.string))
    func `[string] nl`() throws {
        try verifyByFixture(pathComponents: ["string", "nl"])
    }

    @Test(.tags(.string))
    func `[string] quoted unicode`() throws {
        try verifyByFixture(pathComponents: ["string", "quoted-unicode"])
    }

    @Test(.tags(.string))
    func `[string] raw`() throws {
        try verifyByFixture(pathComponents: ["string", "raw"])
    }

    @Test(.tags(.string))
    func `[string] raw empty`() throws {
        try verifyByFixture(pathComponents: ["string", "raw-empty"])
    }

    @Test(.tags(.string))
    func `[string] raw multiline`() throws {
        try verifyByFixture(pathComponents: ["string", "raw-multiline"])
    }

    @Test(.tags(.string))
    func `[string] simple`() throws {
        try verifyByFixture(pathComponents: ["string", "simple"])
    }

    @Test(.tags(.string))
    func `[string] start mb`() throws {
        try verifyByFixture(pathComponents: ["string", "start-mb"])
    }

    @Test(.tags(.string))
    func `[string] unicode escape`() throws {
        try verifyByFixture(pathComponents: ["string", "unicode-escape"])
    }

    @Test(.tags(.string))
    func `[string] with pound`() throws {
        try verifyByFixture(pathComponents: ["string", "with-pound"])
    }

    @Test(.tags(.table))
    func `[table] array empty`() throws {
        try verifyByFixture(pathComponents: ["table", "array-empty"])
    }

    @Test(.tags(.table))
    func `[table] array empty name`() throws {
        try verifyByFixture(pathComponents: ["table", "array-empty-name"])
    }

    @Test(.tags(.table))
    func `[table] array implicit`() throws {
        try verifyByFixture(pathComponents: ["table", "array-implicit"])
    }

    @Test(.tags(.table))
    func `[table] array implicit and explicit after`() throws {
        try verifyByFixture(pathComponents: ["table", "array-implicit-and-explicit-after"])
    }

    @Test(.tags(.table))
    func `[table] array many`() throws {
        try verifyByFixture(pathComponents: ["table", "array-many"])
    }

    @Test(.tags(.table))
    func `[table] array nest`() throws {
        try verifyByFixture(pathComponents: ["table", "array-nest"])
    }

    @Test(.tags(.table))
    func `[table] array one`() throws {
        try verifyByFixture(pathComponents: ["table", "array-one"])
    }

    @Test(.tags(.table))
    func `[table] array table array`() throws {
        try verifyByFixture(pathComponents: ["table", "array-table-array"])
    }

    @Test(.tags(.table))
    func `[table] array within dotted`() throws {
        try verifyByFixture(pathComponents: ["table", "array-within-dotted"])
    }

    @Test(.tags(.table))
    func `[table] empty`() throws {
        try verifyByFixture(pathComponents: ["table", "empty"])
    }

    @Test(.tags(.table))
    func `[table] empty name`() throws {
        try verifyByFixture(pathComponents: ["table", "empty-name"])
    }

    @Test(.tags(.table))
    func `[table] keyword`() throws {
        try verifyByFixture(pathComponents: ["table", "keyword"])
    }

    @Test(.tags(.table))
    func `[table] keyword with values`() throws {
        try verifyByFixture(pathComponents: ["table", "keyword-with-values"])
    }

    @Test(.tags(.table))
    func `[table] names`() throws {
        try verifyByFixture(pathComponents: ["table", "names"])
    }

    @Test(.tags(.table))
    func `[table] names with values`() throws {
        try verifyByFixture(pathComponents: ["table", "names-with-values"])
    }

    @Test(.tags(.table))
    func `[table] no eol`() throws {
        try verifyByFixture(pathComponents: ["table", "no-eol"])
    }

    @Test(.tags(.table))
    func `[table] sub`() throws {
        try verifyByFixture(pathComponents: ["table", "sub"])
    }

    @Test(.tags(.table))
    func `[table] sub empty`() throws {
        try verifyByFixture(pathComponents: ["table", "sub-empty"])
    }

    @Test(.tags(.table))
    func `[table] whitespace`() throws {
        try verifyByFixture(pathComponents: ["table", "whitespace"])
    }

    @Test(.tags(.table))
    func `[table] with literal string`() throws {
        try verifyByFixture(pathComponents: ["table", "with-literal-string"])
    }

    @Test(.tags(.table))
    func `[table] with pound`() throws {
        try verifyByFixture(pathComponents: ["table", "with-pound"])
    }

    @Test(.tags(.table))
    func `[table] with single quotes`() throws {
        try verifyByFixture(pathComponents: ["table", "with-single-quotes"])
    }

    @Test(.tags(.table))
    func `[table] without super`() throws {
        try verifyByFixture(pathComponents: ["table", "without-super"])
    }

    @Test(.tags(.table))
    func `[table] without super with values`() throws {
        try verifyByFixture(pathComponents: ["table", "without-super-with-values"])
    }
}
