#if !canImport(ObjectiveC)
import XCTest

extension TOMLDecoderTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__TOMLDecoderTests = [
        ("testBasicGeneratedCodables", testBasicGeneratedCodables),
        ("testDecodingContainerKeyed", testDecodingContainerKeyed),
        ("testDecodingCustomKeyStrategy", testDecodingCustomKeyStrategy),
        ("testDecodingFoundationDataWithBase64", testDecodingFoundationDataWithBase64),
        ("testDecodingFoundationDataWithCustom", testDecodingFoundationDataWithCustom),
        ("testDecodingSnakeCaseKeyStrategy", testDecodingSnakeCaseKeyStrategy),
        ("testFoundationDateComponentsFromLocalDateDecoding", testFoundationDateComponentsFromLocalDateDecoding),
        ("testFoundationDateComponentsFromLocalDateTimeDecoding", testFoundationDateComponentsFromLocalDateTimeDecoding),
        ("testFoundationDateComponentsFromLocalTimeDecoding", testFoundationDateComponentsFromLocalTimeDecoding),
        ("testFoundationDateDecoding", testFoundationDateDecoding),
        ("testFoundationDateDecodingWithStrictStrategy", testFoundationDateDecodingWithStrictStrategy),
        ("testLenientIntegerDecodingStrategy", testLenientIntegerDecodingStrategy),
        ("testNestedUnkeyedDecodingContainer", testNestedUnkeyedDecodingContainer),
        ("testNetTimeDateDecoding", testNetTimeDateDecoding),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(TOMLDecoderTests.__allTests__TOMLDecoderTests),
    ]
}
#endif
