name: CentOS 7

on: [push, pull_request]

jobs:
  linux:
    name: CentOS 7
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Test
      run: Scripts/docker.sh TOMLDecoder 'swift test -Xswiftc -warnings-as-errors --enable-test-discovery' 5.5.3 centos7
