name: Continuous Integration

on: [push, pull_request]

jobs:
  macos:
    name: macOS
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - name: Xcode version
      run: sudo xcode-select -s /Applications/Xcode_12.3.app
    - name: Run Tests
      run: make test

  docker:
    name: Ubuntu
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Test
      run: make test-docker
