name: macOS

on: [push]

jobs:
  macos:
    name: macOS
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Xcode version
      run: sudo xcode-select -s /Applications/Xcode_13.2.app
    - name: Test
      run: make test-SwiftPM
