name: Windows 2019

on: [push]

jobs:
  Windows:
    name: Windows
    runs-on: windows-2019
    steps:
    - name: Check out
      uses: actions/checkout@v2
    - name: Install Swift
      uses: compnerd/gha-setup-swift@cf2a61060c146203ea6fe10cce367979ae4ec0b1
      with:
        branch: swift-5.5.3-release
        tag: 5.5.3-RELEASE
    - name: Test
      shell: cmd
      run: |
        echo on
        swift test -Xswiftc -warnings-as-errors
